"""Clinical Reasoning Engine models.

Continuously updated per-patient profiles aggregating data from all
clinical modules into structured reasoning artifacts.
"""
from django.db import models

from patients.models import Patient


class ClinicalProfile(models.Model):
    """Per-patient continuously updated clinical intelligence profile.

    Aggregates features from all engines: rule evaluation, lab trends,
    pathology, treatment response, disease trajectory.
    """
    patient = models.OneToOneField(Patient, on_delete=models.CASCADE, related_name="clinical_profile")
    features_snapshot = models.JSONField(default=dict, blank=True, help_text="Current patient features")
    differential = models.JSONField(default=list, blank=True, help_text="Ranked disease differential with scores")
    disease_trajectory = models.JSONField(default=dict, blank=True, help_text="Per-disease trajectory assessment")
    care_pathway = models.JSONField(default=dict, blank=True, help_text="Current care stage and recommendations")
    risk_assessment = models.JSONField(default=dict, blank=True, help_text="Risk scores: progression, relapse, kidney survival")
    evidence_summary = models.JSONField(default=dict, blank=True, help_text="GRADE evidence for top diagnoses")
    reasoning_chain = models.JSONField(default=list, blank=True, help_text="Full reasoning trace")
    information_gaps = models.JSONField(default=list, blank=True, help_text="Missing data that would improve confidence")
    milestones = models.JSONField(default=list, blank=True, help_text="Longitudinal disease milestones")
    last_updated = models.DateTimeField(auto_now=True)
    version = models.PositiveIntegerField(default=0, help_text="Incrementing version for change tracking")

    class Meta:
        verbose_name = "clinical profile"
        verbose_name_plural = "clinical profiles"
        indexes = [
            models.Index(fields=["last_updated"]),
        ]

    def __str__(self):
        return f"ClinicalProfile({self.patient.patient_id}) v{self.version}"


class ClinicalInsight(models.Model):
    """Individual clinical insight/recommendation generated by the reasoning engine."""
    class InsightCategory(models.TextChoices):
        DIAGNOSTIC = "diagnostic", "Diagnostic insight"
        PROGNOSTIC = "prognostic", "Prognostic assessment"
        THERAPEUTIC = "therapeutic", "Therapeutic recommendation"
        MONITORING = "monitoring", "Monitoring recommendation"
        SAFETY = "safety", "Safety alert"
        CARE_GAP = "care_gap", "Care gap detected"
        RESEARCH = "research", "Research opportunity"

    class Priority(models.TextChoices):
        CRITICAL = "critical", "Critical"
        HIGH = "high", "High"
        MEDIUM = "medium", "Medium"
        LOW = "low", "Low"
        INFO = "info", "Informational"

    patient = models.ForeignKey(Patient, on_delete=models.CASCADE, related_name="clinical_insights")
    category = models.CharField(max_length=20, choices=InsightCategory.choices, db_index=True)
    priority = models.CharField(max_length=10, choices=Priority.choices, default=Priority.INFO)
    title = models.CharField(max_length=300)
    description = models.TextField(blank=True)
    evidence = models.JSONField(default=list, blank=True, help_text="Supporting evidence items")
    guidelines = models.JSONField(default=list, blank=True, help_text="Guideline references")
    reasoning = models.TextField(blank=True, help_text="Why this insight was generated")
    actionable = models.BooleanField(default=True)
    dismissed = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    expires_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ["-priority", "-created_at"]
        indexes = [
            models.Index(fields=["patient", "category"]),
            models.Index(fields=["patient", "priority", "dismissed"]),
        ]

    def __str__(self):
        return f"[{self.get_priority_display()}] {self.title}"
