# Generated by Django 6.0.6 on 2026-06-19 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiomarkerKinetics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pla2r_baseline', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True)),
                ('pla2r_latest', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True)),
                ('pla2r_nadir', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True)),
                ('pla2r_baseline_date', models.DateField(blank=True, null=True)),
                ('pla2r_pct_decline', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('pla2r_50pct_decline', models.BooleanField(default=False)),
                ('pla2r_50pct_date', models.DateField(blank=True, null=True)),
                ('pla2r_50pct_days', models.IntegerField(blank=True, help_text='Days from baseline to >=50% decline.', null=True)),
                ('pla2r_immunological_remission', models.BooleanField(default=False)),
                ('pla2r_remission_date', models.DateField(blank=True, null=True)),
                ('c3_recovered', models.BooleanField(default=False)),
                ('c3_recovered_date', models.DateField(blank=True, null=True)),
                ('c4_recovered', models.BooleanField(default=False)),
                ('c4_recovered_date', models.DateField(blank=True, null=True)),
                ('dsdna_baseline', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True)),
                ('dsdna_latest', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True)),
                ('dsdna_normalized', models.BooleanField(default=False)),
                ('dsdna_normalized_date', models.DateField(blank=True, null=True)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='biomarker_kinetics', to='patients.patient')),
            ],
            options={
                'verbose_name_plural': 'biomarker kinetics',
                'ordering': ['patient'],
            },
        ),
    ]
