# Generated by Django 6.0.6 on 2026-06-19 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('encounters', '0002_clinicalevent'),
        ('patients', '0001_initial'),
        ('treatments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdverseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onset_date', models.DateField()),
                ('category', models.CharField(choices=[('infection', 'Infection'), ('steroid_toxicity', 'Steroid toxicity'), ('hematologic', 'Haematologic'), ('hepatic', 'Hepatotoxicity'), ('nephrotoxicity', 'Nephrotoxicity'), ('cardiovascular', 'Cardiovascular'), ('malignancy', 'Malignancy'), ('infusion_reaction', 'Infusion reaction'), ('other', 'Other')], max_length=20)),
                ('infection_type', models.CharField(blank=True, choices=[('tb', 'Tuberculosis'), ('pjp', 'Pneumocystis (PJP)'), ('cmv', 'CMV'), ('zoster', 'Herpes zoster'), ('pneumonia', 'Pneumonia'), ('cellulitis', 'Cellulitis'), ('sepsis', 'Sepsis'), ('uti', 'Urinary tract infection'), ('fungal', 'Invasive fungal'), ('hepatitis_flare', 'Hepatitis B/C reactivation'), ('other', 'Other infection')], help_text='Only when category = infection.', max_length=16)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('severity', models.CharField(choices=[('mild', 'Mild (G1)'), ('moderate', 'Moderate (G2)'), ('severe', 'Severe (G3)'), ('life_threatening', 'Life-threatening (G4)'), ('fatal', 'Fatal (G5)')], max_length=18)),
                ('serious', models.BooleanField(default=False, help_text='SAE: death, life-threatening, hospitalisation, disability, or other medically important event.')),
                ('hospitalization', models.BooleanField(default=False)),
                ('outcome', models.CharField(blank=True, choices=[('recovered', 'Recovered/resolved'), ('recovering', 'Recovering'), ('sequelae', 'Recovered with sequelae'), ('ongoing', 'Ongoing'), ('fatal', 'Fatal')], max_length=12)),
                ('relatedness', models.CharField(choices=[('unrelated', 'Unrelated'), ('unlikely', 'Unlikely'), ('possible', 'Possible'), ('probable', 'Probable'), ('definite', 'Definite'), ('not_assessed', 'Not assessed')], default='not_assessed', max_length=14)),
                ('notes', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adverse_events', to='encounters.clinicalencounter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adverse_events', to='patients.patient')),
                ('suspected_drug', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adverse_events', to='treatments.drugmaster')),
            ],
            options={
                'ordering': ['patient', '-onset_date'],
                'indexes': [models.Index(fields=['patient', 'onset_date'], name='safety_adve_patient_f0a338_idx'), models.Index(fields=['category', 'onset_date'], name='safety_adve_categor_7ea596_idx')],
            },
        ),
    ]
