# Generated by Django 6.0.6 on 2026-07-08 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('encounters', '0003_clinicalencounter_clinician_response_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VitalSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bp_systolic', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bp_diastolic', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('heart_rate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='encounters.clinicalencounter')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicalAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chief_complaint', models.TextField(blank=True)),
                ('time_course', models.CharField(choices=[('acute', 'Acute days to weeks'), ('subacute', 'Subacute weeks to months'), ('chronic', 'Chronic or incidental'), ('relapsing', 'Relapsing')], default='subacute', max_length=20)),
                ('features', models.JSONField(blank=True, default=list, help_text='Clinical feature codes: edema, hypertension, grossHematuria, purpura, arthritis, sinopulmonary, hemoptysis, sle, diabetes')),
                ('syndrome_classification', models.CharField(blank=True, help_text='e.g. Nephrotic syndrome, Rapidly progressive nephritic syndrome', max_length=100)),
                ('syndrome_classified_at', models.DateTimeField(blank=True, null=True)),
                ('severity_flags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('encounter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_assessment', to='encounters.clinicalencounter')),
            ],
            options={
                'indexes': [models.Index(fields=['encounter'], name='clinical_cl_encount_511544_idx')],
            },
        ),
    ]
