# Generated by Django 5.2.16 on 2026-09-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vitalsign',
            options={'ordering': ['encounter', 'measured_at', 'recorded_at', 'id']},
        ),
        migrations.AddField(
            model_name='vitalsign',
            name='measured_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vitalsign',
            name='source',
            field=models.CharField(blank=True, choices=[('visit_form', 'Follow-up form'), ('api', 'API'), ('admin', 'Admin'), ('legacy', 'Legacy encounter fields')], max_length=10),
        ),
    ]
