# Generated by Django 6.0.6 on 2026-06-19 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('encounters', '0002_clinicalevent'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('routine', 'Routine follow-up'), ('early_safety', 'Early safety visit')], default='routine', max_length=12)),
                ('label', models.CharField(max_length=20)),
                ('target_date', models.DateField()),
                ('window_start', models.DateField()),
                ('window_end', models.DateField()),
                ('clinic_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('missed', 'Missed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilled_visits', to='encounters.clinicalencounter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_visits', to='patients.patient')),
            ],
            options={
                'ordering': ['patient', 'target_date'],
                'indexes': [models.Index(fields=['status', 'window_end'], name='scheduling__status_891484_idx'), models.Index(fields=['clinic_date'], name='scheduling__clinic__110d1a_idx')],
                'constraints': [models.UniqueConstraint(fields=('patient', 'label'), name='uniq_patient_visit_label')],
            },
        ),
    ]
