# Generated by Django 6.0.6 on 2026-06-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='role',
            field=models.CharField(blank=True, choices=[('', '— no role —'), ('data_manager', 'Data Manager'), ('statistician', 'Statistician'), ('readonly', 'Read-only'), ('coordinator', 'Coordinator'), ('investigator', 'Investigator'), ('pathologist', 'Pathologist')], max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('', '— no role —'), ('data_manager', 'Data Manager'), ('statistician', 'Statistician'), ('readonly', 'Read-only'), ('coordinator', 'Coordinator'), ('investigator', 'Investigator'), ('pathologist', 'Pathologist')], help_text='Determines permissions (seeded by seed_roles).', max_length=30),
        ),
    ]
