# Generated by Django 6.0.6 on 2026-07-09 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0005_site_patient_site_usersiterole'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('diagnostic', 'Diagnostic insight'), ('prognostic', 'Prognostic assessment'), ('therapeutic', 'Therapeutic recommendation'), ('monitoring', 'Monitoring recommendation'), ('safety', 'Safety alert'), ('care_gap', 'Care gap detected'), ('research', 'Research opportunity')], db_index=True, max_length=20)),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Informational')], default='info', max_length=10)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('evidence', models.JSONField(blank=True, default=list, help_text='Supporting evidence items')),
                ('guidelines', models.JSONField(blank=True, default=list, help_text='Guideline references')),
                ('reasoning', models.TextField(blank=True, help_text='Why this insight was generated')),
                ('actionable', models.BooleanField(default=True)),
                ('dismissed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_insights', to='patients.patient')),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['patient', 'category'], name='clinical_re_patient_be9993_idx'), models.Index(fields=['patient', 'priority', 'dismissed'], name='clinical_re_patient_947c68_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClinicalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('features_snapshot', models.JSONField(blank=True, default=dict, help_text='Current patient features')),
                ('differential', models.JSONField(blank=True, default=list, help_text='Ranked disease differential with scores')),
                ('disease_trajectory', models.JSONField(blank=True, default=dict, help_text='Per-disease trajectory assessment')),
                ('care_pathway', models.JSONField(blank=True, default=dict, help_text='Current care stage and recommendations')),
                ('risk_assessment', models.JSONField(blank=True, default=dict, help_text='Risk scores: progression, relapse, kidney survival')),
                ('evidence_summary', models.JSONField(blank=True, default=dict, help_text='GRADE evidence for top diagnoses')),
                ('reasoning_chain', models.JSONField(blank=True, default=list, help_text='Full reasoning trace')),
                ('information_gaps', models.JSONField(blank=True, default=list, help_text='Missing data that would improve confidence')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=0, help_text='Incrementing version for change tracking')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_profile', to='patients.patient')),
            ],
            options={
                'verbose_name': 'clinical profile',
                'verbose_name_plural': 'clinical profiles',
                'indexes': [models.Index(fields=['last_updated'], name='clinical_re_last_up_79080c_idx')],
            },
        ),
    ]
