# Generated by Django 6.0.6 on 2026-07-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_reasoning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalprofile',
            name='milestones',
            field=models.JSONField(blank=True, default=list, help_text='Longitudinal disease milestones'),
        ),
    ]
