# GDES server install / repair. Run from an ELEVATED PowerShell:
#
#     powershell -ExecutionPolicy Bypass -File "E:\GDES server\deploy\windows\install.ps1"
#
# Safe to re-run: existing secrets, database and data are kept; tasks and the
# firewall rule are re-registered. What it does:
#
#   1. writes E:\GDES server\.env on first run, generating DJANGO_SECRET_KEY
#      and the database password itself (never printed), and locks the file
#      down to SYSTEM + Administrators + you;
#   2. creates the "gdes" login and "gdes" database on the PostgreSQL 16 that
#      already serves DKD (DKD's database and login are not touched);
#   3. migrates and seeds reference data (manage.py server_init);
#   4. stages gdes-caddy.exe and registers four SYSTEM tasks - GDES Server,
#      GDES Caddy, GDES Watchdog, GDES Backup - plus one firewall rule for
#      TCP 8080 from the clinic subnet only;
#   5. starts them and checks both the app and the clinic address answer.
#
# It does NOT create a GDES user account. Do that yourself afterwards (the
# password must not pass through a script or a chat window):
#
#     & "E:\GDES server\deploy\windows\gdes-manage.bat" createsuperuser
#
# PURE ASCII on purpose (PowerShell 5.1 reads BOM-less UTF-8 as ANSI).

$ErrorActionPreference = 'Stop'
$Root      = 'E:\GDES server'
$Data      = 'E:\gdes-data'
$App       = Join-Path $Data 'app'
$PgBin     = 'C:\Program Files\PostgreSQL\16\bin'
$SuperFile = 'E:\dkdr-data\postgres-superuser.txt'
$DkdCaddy  = 'E:\dkdr-data\bin\caddy.exe'
$Py        = Join-Path $Root '.venv\Scripts\python.exe'
$EnvFile   = Join-Path $Root '.env'
# Clinic networks allowed in. 192.168.10.0/24 is the second clinic LAN,
# routed through 192.168.7.1 (added 2026-09-28).
$LanSubnet = @('192.168.7.0/24', '192.168.10.0/24')
$Port      = 8080

if (-not ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    throw "Run this from an elevated PowerShell (Run as administrator)."
}
foreach ($p in @($Py, $SuperFile, $DkdCaddy, (Join-Path $PgBin 'psql.exe'))) {
    if (-not (Test-Path -LiteralPath $p)) { throw "Missing prerequisite: $p" }
}

function Step($m) { Write-Output "`n== $m" }
function New-Secret([int]$bytes) {
    $b = New-Object byte[] $bytes
    [Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($b)
    return -join ($b | ForEach-Object { $_.ToString('x2') })
}
function Get-EnvValue($name) {
    $m = Select-String -Path $EnvFile -Pattern "^$name=(.*)$"
    if ($m) { return $m.Matches[0].Groups[1].Value.Trim() }
    return ''
}

# --- 1. folders and .env -------------------------------------------------------
Step 'folders'
foreach ($d in @($Data, $App, (Join-Path $Data 'backups'), (Join-Path $Data 'bin'),
                 (Join-Path $Data 'caddy'), (Join-Path $App 'Logs'), (Join-Path $App 'Media'))) {
    New-Item -ItemType Directory -Force -Path $d | Out-Null
}
Write-Output "ok  $Data"

Step '.env'
if (-not (Test-Path -LiteralPath $EnvFile)) {
    $lines = @(
        '# GDES server settings. Secrets generated by install.ps1. Do not commit.',
        'DJANGO_SETTINGS_MODULE=bgddr.settings_server',
        "DJANGO_SECRET_KEY=$(New-Secret 48)",
        'DJANGO_ALLOWED_HOSTS=192.168.7.55,dr-wasim,127.0.0.1,localhost',
        "GDES_CSRF_TRUSTED_ORIGINS=http://192.168.7.55:$Port,http://dr-wasim:$Port,http://127.0.0.1:$Port,http://localhost:$Port",
        'GDES_HTTPS=0',
        "BGDDR_DATA_DIR=$App",
        'POSTGRES_DB=gdes',
        'POSTGRES_USER=gdes',
        "POSTGRES_PASSWORD=$(New-Secret 24)",
        'POSTGRES_HOST=127.0.0.1',
        'POSTGRES_PORT=5432',
        'CELERY_BROKER_URL='
    )
    [IO.File]::WriteAllText($EnvFile, ($lines -join "`r`n") + "`r`n", (New-Object Text.UTF8Encoding $false))
    Write-Output "created $EnvFile (secrets generated, not shown)"
} else {
    Write-Output "kept existing $EnvFile"
}
& icacls $EnvFile /inheritance:r /grant:r 'SYSTEM:(F)' 'Administrators:(F)' "$($env:USERNAME):(F)" | Out-Null
foreach ($d in @((Join-Path $Data 'backups'), (Join-Path $App 'Media'))) {
    & icacls $d /inheritance:r /grant:r 'SYSTEM:(OI)(CI)(F)' 'Administrators:(OI)(CI)(F)' "$($env:USERNAME):(OI)(CI)(F)" | Out-Null
}
Write-Output "ok  .env, backups and Media restricted to SYSTEM, Administrators, $($env:USERNAME)"

# --- 2. database -------------------------------------------------------------------
Step 'PostgreSQL: gdes login and database'
$dbPass = Get-EnvValue 'POSTGRES_PASSWORD'
if ($dbPass -notmatch '^[0-9a-f]{32,}$') { throw "POSTGRES_PASSWORD in .env is not the generated hex value; fix .env first." }
$env:PGPASSWORD = (Get-Content -LiteralPath $SuperFile -Raw).Trim()
$env:PGHOST = '127.0.0.1'
$env:PGPORT = '5432'
try {
    $psql = Join-Path $PgBin 'psql.exe'
    $hasRole = (& $psql -U postgres -d postgres -tAc "SELECT 1 FROM pg_roles WHERE rolname='gdes'")
    # The password travels on stdin, never argv (argv is visible in the process list).
    if ($hasRole -match '1') {
        "ALTER ROLE gdes WITH LOGIN PASSWORD '$dbPass';" | & $psql -q -U postgres -d postgres -v ON_ERROR_STOP=1
        Write-Output "ok  role gdes exists (password synced with .env)"
    } else {
        "CREATE ROLE gdes WITH LOGIN PASSWORD '$dbPass';" | & $psql -q -U postgres -d postgres -v ON_ERROR_STOP=1
        Write-Output "ok  role gdes created"
    }
    if ($LASTEXITCODE -ne 0) { throw "could not create/update role gdes" }
    $hasDb = (& $psql -U postgres -d postgres -tAc "SELECT 1 FROM pg_database WHERE datname='gdes'")
    if ($hasDb -match '1') {
        Write-Output "ok  database gdes exists (kept)"
    } else {
        & $psql -q -U postgres -d postgres -v ON_ERROR_STOP=1 -c "CREATE DATABASE gdes OWNER gdes ENCODING 'UTF8' TEMPLATE template0;"
        if ($LASTEXITCODE -ne 0) { throw "could not create database gdes" }
        Write-Output "ok  database gdes created"
    }
} finally {
    $env:PGPASSWORD = $null
}

# --- 3. application ------------------------------------------------------------------
Step 'migrate + reference data (manage.py server_init)'
$env:DJANGO_SETTINGS_MODULE = 'bgddr.settings_server'
$env:CELERY_BROKER_URL = ''
Push-Location $Root
try {
    & $Py manage.py server_init
    if ($LASTEXITCODE -ne 0) { throw "server_init failed (exit $LASTEXITCODE)" }
    & $Py manage.py check --deploy
    if ($LASTEXITCODE -ne 0) { throw "check --deploy reported errors" }
} finally { Pop-Location }

# --- 4. proxy binary, tasks, firewall ----------------------------------------------
Step 'gdes-caddy.exe'
# A renamed copy so the DKD watchdog ("Get-Process caddy | Stop-Process")
# never matches it.
Copy-Item -LiteralPath $DkdCaddy -Destination (Join-Path $Data 'bin\gdes-caddy.exe') -Force
Write-Output "ok  $Data\bin\gdes-caddy.exe"

Step 'scheduled tasks (SYSTEM, at startup)'
$Principal = New-ScheduledTaskPrincipal -UserId 'SYSTEM' -LogonType ServiceAccount -RunLevel Highest
$Service = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries `
    -StartWhenAvailable -MultipleInstances IgnoreNew -ExecutionTimeLimit ([TimeSpan]::Zero) `
    -RestartCount 999 -RestartInterval (New-TimeSpan -Minutes 1)
$Job = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries `
    -StartWhenAvailable -MultipleInstances IgnoreNew -WakeToRun -ExecutionTimeLimit (New-TimeSpan -Hours 2)

function Register-Gdes($Name, $Exec, $Argument, $Trigger, $Description, $With) {
    $action = New-ScheduledTaskAction -Execute $Exec -Argument $Argument -WorkingDirectory $Root
    if (Get-ScheduledTask -TaskName $Name -ErrorAction SilentlyContinue) {
        Stop-ScheduledTask -TaskName $Name -ErrorAction SilentlyContinue
        Unregister-ScheduledTask -TaskName $Name -Confirm:$false
    }
    Register-ScheduledTask -TaskName $Name -Action $action -Trigger $Trigger -Principal $Principal `
        -Settings $With -Description $Description | Out-Null
    Write-Output "ok  $Name"
}

$AtBoot = New-ScheduledTaskTrigger -AtStartup
Register-Gdes 'GDES Server' 'cmd.exe' "/c `"$Root\deploy\windows\run_server.bat`"" $AtBoot `
    'GDES registry: waitress WSGI server on 127.0.0.1:8100.' $Service
Register-Gdes 'GDES Caddy' 'cmd.exe' "/c `"$Root\deploy\windows\run_caddy.bat`"" $AtBoot `
    "GDES reverse proxy: Caddy on port $Port (admin 127.0.0.1:2020)." $Service
Register-Gdes 'GDES Backup' 'powershell.exe' "-NoProfile -ExecutionPolicy Bypass -File `"$Root\deploy\windows\backup.ps1`"" `
    (New-ScheduledTaskTrigger -Daily -At '02:15') 'Nightly pg_dump of gdes + uploaded files to E:\gdes-data\backups.' $Job

$donor = New-ScheduledTaskTrigger -Once -At (Get-Date).AddMinutes(2) `
    -RepetitionInterval (New-TimeSpan -Minutes 5) -RepetitionDuration (New-TimeSpan -Days 3650)
$every5 = New-ScheduledTaskTrigger -Once -At (Get-Date).AddMinutes(2)
$every5.Repetition = $donor.Repetition
Register-Gdes 'GDES Watchdog' 'powershell.exe' "-NoProfile -ExecutionPolicy Bypass -File `"$Root\deploy\windows\watchdog.ps1`"" `
    @($every5, (New-ScheduledTaskTrigger -AtStartup)) `
    'Every 5 min: checks GDES on 127.0.0.1:8100 and the clinic address, restarts only GDES processes.' $Service

Step 'firewall'
$fw = "GDES registry (HTTP $Port, clinic LAN)"
Get-NetFirewallRule -DisplayName $fw -ErrorAction SilentlyContinue | Remove-NetFirewallRule
New-NetFirewallRule -DisplayName $fw -Direction Inbound -Protocol TCP -LocalPort $Port `
    -Action Allow -Profile Private -RemoteAddress $LanSubnet | Out-Null
Write-Output "ok  TCP $Port inbound, Private profile, $($LanSubnet -join ', ') only (8100 and 5432 stay closed)"

# --- 5. start and verify -------------------------------------------------------------
Step 'start'
Start-ScheduledTask -TaskName 'GDES Server'
Start-ScheduledTask -TaskName 'GDES Caddy'
. (Join-Path $Root 'deploy\windows\http_probe.ps1')
$app  = Wait-HttpOk -Url 'http://127.0.0.1:8100/login/' -HostHeader '192.168.7.55' -ForSeconds 120
$edge = Wait-HttpOk -Url "http://192.168.7.55:$Port/login/" -ForSeconds 60
Write-Output "app  (127.0.0.1:8100)        -> $($app.Code) $($app.Reason)"
Write-Output "edge (192.168.7.55:$Port)  -> $($edge.Code) $($edge.Reason)"
if ((Test-ProbeDown $app) -or (Test-ProbeDown $edge)) {
    Write-Output "NOT SERVING YET. Look at E:\gdes-data\app\Logs\server.err and caddy.err."
    exit 1
}
Write-Output @"

GDES is serving at http://192.168.7.55:$Port/  (DKD is unchanged at http://192.168.7.55/)

Next, yourself (the password must not pass through a script):
  & "E:\GDES server\deploy\windows\gdes-manage.bat" createsuperuser
"@
