# Generated by Django 6.0.6 on 2026-07-08 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuidelineSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('abbreviation', models.CharField(max_length=50)),
                ('version_year', models.PositiveSmallIntegerField()),
                ('url', models.URLField(blank=True, max_length=500)),
                ('effective_date', models.DateField()),
                ('retired_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['abbreviation', 'version_year'], name='knowledge_g_abbrevi_85d89b_idx')],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBaseEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_id', models.CharField(help_text='Stable KB entry ID (e.g. KB-IGA-001)', max_length=50, unique=True)),
                ('disease_id', models.CharField(db_index=True, help_text='Disease code from prototype (e.g. iga, membranous)', max_length=50)),
                ('rule_data', models.JSONField(help_text='Full rule definition (conditions, weights, explanations)')),
                ('evidence_grade', models.CharField(choices=[('1', 'Level 1 (Strong recommendation)'), ('2', 'Level 2 (Weak recommendation)'), ('NG', 'Not graded'), ('OP', 'Expert opinion')], default='NG', max_length=2)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('reviewed', 'Clinical review complete'), ('active', 'Active'), ('retired', 'Retired')], default='draft', max_length=10)),
                ('effective_date', models.DateField()),
                ('retired_date', models.DateField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='knowledge.guidelinesource')),
            ],
            options={
                'verbose_name_plural': 'knowledge base entries',
                'indexes': [models.Index(fields=['disease_id', 'status'], name='knowledge_k_disease_4df624_idx')],
            },
        ),
    ]
