# Generated by Django 6.0.6 on 2026-07-09 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebaseentry',
            name='evidence_url',
            field=models.URLField(blank=True, help_text='Link to supporting evidence or DOI', max_length=500),
        ),
        migrations.AddField(
            model_name='knowledgebaseentry',
            name='guideline_chapter',
            field=models.CharField(blank=True, help_text="e.g. 'KDIGO 2021 IgAN Chapter 3.1'", max_length=200),
        ),
        migrations.AddField(
            model_name='knowledgebaseentry',
            name='guideline_paragraph',
            field=models.CharField(blank=True, help_text="e.g. 'Section 3.1.2'", max_length=100),
        ),
        migrations.AddField(
            model_name='knowledgebaseentry',
            name='guideline_quote',
            field=models.TextField(blank=True, help_text='Direct quote from the guideline supporting this rule'),
        ),
        migrations.CreateModel(
            name='KnowledgeBaseVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveSmallIntegerField()),
                ('rule_data', models.JSONField()),
                ('evidence_grade', models.CharField(blank=True, max_length=2)),
                ('guideline_chapter', models.CharField(blank=True, max_length=200)),
                ('guideline_paragraph', models.CharField(blank=True, max_length=100)),
                ('guideline_quote', models.TextField(blank=True)),
                ('change_summary', models.TextField(blank=True, help_text='What changed in this version')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='knowledge.knowledgebaseentry')),
            ],
            options={
                'verbose_name_plural': 'knowledge base versions',
                'ordering': ['-version_number'],
                'unique_together': {('entry', 'version_number')},
            },
        ),
    ]
