# Generated by Django 6.0.6 on 2026-07-09 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_knowledgebaseentry_evidence_url_and_more'),
        ('patients', '0005_site_patient_site_usersiterole'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('authors', models.CharField(blank=True, max_length=500)),
                ('journal', models.CharField(blank=True, max_length=200)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('doi', models.CharField(blank=True, max_length=100)),
                ('pmid', models.CharField(blank=True, max_length=20)),
                ('evidence_level', models.CharField(choices=[('meta', 'Meta-analysis / Systematic review'), ('rct', 'Randomised controlled trial'), ('cohort', 'Cohort study'), ('case_control', 'Case-control study'), ('case_series', 'Case series'), ('expert', 'Expert opinion'), ('other', 'Other')], default='other', max_length=20)),
                ('summary', models.TextField(blank=True, help_text='How this evidence supports the rule')),
                ('url', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'evidence entries',
                'ordering': ['-year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='GuidelineDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('document_type', models.CharField(choices=[('markdown', 'Markdown'), ('html', 'HTML'), ('text', 'Plain text'), ('json', 'Structured JSON'), ('yaml', 'YAML')], default='markdown', max_length=20)),
                ('content', models.TextField(blank=True)),
                ('import_status', models.CharField(choices=[('pending', 'Pending'), ('parsing', 'Parsing'), ('complete', 'Complete'), ('error', 'Error')], default='pending', max_length=20)),
                ('parsed_rules', models.JSONField(blank=True, default=list, help_text='Rule candidates extracted from the document')),
                ('import_log', models.TextField(blank=True, help_text='Parsing log messages')),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='RuleReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('changes_requested', 'Changes requested'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RuleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('diagnostic', 'Diagnostic'), ('treatment', 'Treatment'), ('monitoring', 'Monitoring'), ('referral', 'Referral')], default='diagnostic', max_length=20)),
                ('condition_schema', models.JSONField(blank=True, default=dict, help_text='JSON Schema describing valid conditions for this template')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'template_id'],
            },
        ),
        migrations.CreateModel(
            name='RuleTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(blank=True, max_length=200)),
                ('expected_score', models.FloatField(blank=True, null=True)),
                ('actual_score', models.FloatField()),
                ('matched', models.BooleanField()),
                ('test_input', models.JSONField(help_text='Features used for the test')),
                ('test_output', models.JSONField(help_text='Full evaluation output')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='knowledgebaseentry',
            name='rule_type',
            field=models.CharField(choices=[('diagnostic', 'Diagnostic'), ('treatment', 'Treatment recommendation'), ('monitoring', 'Monitoring'), ('referral', 'Referral criterion'), ('prognostic', 'Prognostic'), ('exclusion', 'Exclusion criterion')], default='diagnostic', max_length=20),
        ),
        migrations.AddField(
            model_name='knowledgebaseentry',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Flexible tags for categorisation'),
        ),
        migrations.AddField(
            model_name='knowledgebaseversion',
            name='rule_data_diff',
            field=models.JSONField(blank=True, default=dict, help_text='Diff from previous version'),
        ),
        migrations.AddIndex(
            model_name='knowledgebaseentry',
            index=models.Index(fields=['rule_type'], name='knowledge_k_rule_ty_349c58_idx'),
        ),
        migrations.AddField(
            model_name='evidenceentry',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_entries', to='knowledge.knowledgebaseentry'),
        ),
        migrations.AddField(
            model_name='guidelinedocument',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='knowledge.guidelinesource'),
        ),
        migrations.AddField(
            model_name='rulereview',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='knowledge.knowledgebaseentry'),
        ),
        migrations.AddField(
            model_name='rulereview',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rulereview',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='knowledge.knowledgebaseversion'),
        ),
        migrations.AddField(
            model_name='ruletestresult',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='knowledge.knowledgebaseentry'),
        ),
        migrations.AddField(
            model_name='ruletestresult',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.patient'),
        ),
        migrations.AddIndex(
            model_name='ruletestresult',
            index=models.Index(fields=['entry', 'matched'], name='knowledge_r_entry_i_ab6148_idx'),
        ),
    ]
