# Generated by Django 6.0.6 on 2026-07-10 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_evidenceentry_guidelinedocument_rulereview_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgebaseentry',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('under_review', 'Under review'), ('approved', 'Approved'), ('active', 'Active'), ('superseded', 'Superseded'), ('archived', 'Archived'), ('retired', 'Retired')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.CharField(help_text='Disease code (e.g. iga, membranous)', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Full disease name', max_length=300)),
                ('category', models.CharField(choices=[('primary', 'Primary glomerular disease'), ('secondary', 'Secondary glomerular disease'), ('transplant', 'Transplant glomerular disease'), ('tubulointerstitial', 'Tubulointerstitial disease'), ('vascular', 'Renal vascular disease'), ('hereditary', 'Hereditary/congenital disease'), ('other', 'Other renal condition')], default='primary', max_length=30)),
                ('definition', models.TextField(blank=True, help_text='Concise definition of the disease')),
                ('epidemiology', models.TextField(blank=True, help_text='Incidence, prevalence, demographics')),
                ('etiology', models.TextField(blank=True, help_text='Causes and risk factors')),
                ('pathophysiology', models.TextField(blank=True, help_text='Disease mechanisms and pathways')),
                ('clinical_presentation', models.TextField(blank=True, help_text=' Signs, symptoms, typical presentation patterns')),
                ('diagnostic_criteria', models.JSONField(blank=True, default=list, help_text='List of diagnostic criteria with evidence levels')),
                ('differential_diagnosis', models.JSONField(blank=True, default=list, help_text='List of disease_id values to consider in differential')),
                ('lab_findings', models.JSONField(blank=True, default=list, help_text='Typical laboratory findings')),
                ('biopsy_findings', models.JSONField(blank=True, default=list, help_text='Typical histopathology findings')),
                ('classification_systems', models.JSONField(blank=True, default=list, help_text='Classification systems (e.g. Oxford MEST-C, ISN/RPS)')),
                ('risk_stratification', models.JSONField(blank=True, default=list, help_text='Risk factors and stratification schemes')),
                ('treatment_overview', models.TextField(blank=True, help_text='General treatment approach')),
                ('treatment_algorithms', models.JSONField(blank=True, default=list, help_text='Structured treatment decision nodes')),
                ('monitoring_protocol', models.TextField(blank=True, help_text='Standard monitoring schedule and parameters')),
                ('complications', models.JSONField(blank=True, default=list, help_text='Potential complications')),
                ('relapse_information', models.TextField(blank=True, help_text='Relapse rates, patterns, and management')),
                ('long_term_prognosis', models.TextField(blank=True, help_text='Long-term outcomes and kidney survival data')),
                ('evidence_summary', models.TextField(blank=True, help_text='Overall evidence base summary')),
                ('guideline_recommendations', models.JSONField(blank=True, default=list, help_text='Key guideline recommendations with sources')),
                ('key_references', models.JSONField(blank=True, default=list, help_text='Key literature references with DOIs')),
                ('notes', models.TextField(blank=True, help_text='Clinical knowledge engineering notes')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this disease is actively supported')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_disease', models.ForeignKey(blank=True, help_text='Parent disease for subtypes (e.g. FSGS subtypes under FSGS)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtypes', to='knowledge.disease')),
            ],
            options={
                'verbose_name_plural': 'diseases',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClinicalPathway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_id', models.CharField(help_text='Stage identifier (e.g. IGA-PATH-01)', max_length=50)),
                ('stage_name', models.CharField(help_text='Human-readable stage name', max_length=200)),
                ('stage_order', models.PositiveIntegerField(help_text='Order in the pathway sequence')),
                ('description', models.TextField(blank=True, help_text='What happens at this stage')),
                ('required_actions', models.JSONField(blank=True, default=list, help_text='Actions that must be completed at this stage')),
                ('expected_duration_days', models.PositiveIntegerField(blank=True, help_text='Typical duration in days', null=True)),
                ('next_stages', models.JSONField(blank=True, default=list, help_text='List of stage_ids that can follow')),
                ('criteria_to_proceed', models.TextField(blank=True, help_text='Criteria that must be met to move to next stage')),
                ('warnings', models.JSONField(blank=True, default=list, help_text='Red flags or cautionary notes')),
                ('is_active', models.BooleanField(default=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pathways', to='knowledge.disease')),
            ],
            options={
                'verbose_name_plural': 'clinical pathways',
                'ordering': ['disease', 'stage_order'],
            },
        ),
        migrations.CreateModel(
            name='ClinicalCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(help_text='Stable case identifier (e.g. CASE-IGA-001)', max_length=50, unique=True)),
                ('title', models.CharField(help_text='Case title', max_length=300)),
                ('presentation_type', models.CharField(choices=[('typical', 'Typical presentation'), ('atypical', 'Atypical presentation'), ('early', 'Early disease'), ('advanced', 'Advanced disease'), ('rapid', 'Rapid progression'), ('remission', 'Remission'), ('relapse', 'Relapse'), ('resistant', 'Treatment-resistant disease'), ('complications', 'Complications'), ('special', 'Special population')], default='typical', max_length=20)),
                ('history', models.TextField(blank=True, help_text='Patient history and background')),
                ('examination', models.TextField(blank=True, help_text='Physical examination findings')),
                ('lab_data', models.JSONField(blank=True, default=dict, help_text='Laboratory data key-value pairs')),
                ('biopsy_data', models.JSONField(blank=True, default=dict, help_text='Biopsy findings')),
                ('diagnosis', models.TextField(blank=True, help_text='Final clinical diagnosis')),
                ('expected_differential', models.JSONField(blank=True, default=list, help_text='Expected differential diagnosis with scores')),
                ('expected_reasoning', models.JSONField(blank=True, default=list, help_text='Expected reasoning chain steps')),
                ('expected_recommendations', models.JSONField(blank=True, default=list, help_text='Expected clinical recommendations')),
                ('expected_monitoring', models.JSONField(blank=True, default=list, help_text='Expected monitoring plan')),
                ('expected_followup', models.JSONField(blank=True, default=list, help_text='Expected follow-up schedule')),
                ('treatment', models.TextField(blank=True, help_text='Treatment administered and response')),
                ('outcome', models.TextField(blank=True, help_text='Clinical outcome')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('internal_review', 'Internal Review'), ('clinical_review', 'Clinical Review'), ('approved', 'Approved'), ('published', 'Published')], default='draft', max_length=20)),
                ('review_notes', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, help_text='Source of the case (clinic, literature, synthetic)', max_length=200)),
                ('is_gold_standard', models.BooleanField(default=False, help_text='Whether this case is a validated gold standard')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_cases', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_cases', to=settings.AUTH_USER_MODEL)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_cases', to='knowledge.disease')),
            ],
            options={
                'verbose_name_plural': 'clinical cases',
                'ordering': ['disease', 'presentation_type', 'title'],
            },
        ),
    ]
