# Generated by Django 6.0.6 on 2026-07-10 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0005_v42_reusable_knowledge_objects'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeGraphNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(help_text='Stable node identifier (e.g. sn:iga, e:mesangial_proliferation)', max_length=50, unique=True)),
                ('node_type', models.CharField(choices=[('syndrome', 'Clinical Syndrome'), ('disease', 'Disease'), ('pathology', 'Pathology Entity'), ('lab', 'Lab Entity'), ('drug', 'Drug Intelligence'), ('monitoring_protocol', 'Monitoring Protocol'), ('complication', 'Complication'), ('clinical_feature', 'Clinical Feature'), ('guideline', 'Guideline'), ('evidence', 'Evidence Entry')], db_index=True, max_length=30)),
                ('label', models.CharField(help_text='Human-readable node label', max_length=300)),
                ('description', models.TextField(blank=True, help_text='Node description')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional node metadata (provenance, references)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'knowledge graph nodes',
                'ordering': ['node_type', 'label'],
                'indexes': [models.Index(fields=['node_type', 'is_active'], name='knowledge_k_node_ty_311cdc_idx')],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeGraphEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge_type', models.CharField(choices=[('presents_with', 'Presents with'), ('causes', 'Causes'), ('diagnosed_by', 'Diagnosed by'), ('treated_by', 'Treated by'), ('indicated_for', 'Indicated for'), ('monitored_by', 'Monitored by'), ('complicated_by', 'Complicated by'), ('risk_factor_for', 'Risk factor for'), ('evidence_for', 'Evidence for'), ('guideline_for', 'Guideline for'), ('subtype_of', 'Subtype of'), ('found_in', 'Found in disease'), ('associated_with', 'Associated with')], db_index=True, max_length=30)),
                ('weight', models.FloatField(default=1.0, help_text='Edge weight for scoring/traversal (0.0 to 1.0)')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional edge metadata (evidence, references)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(help_text='Source node of the edge', on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='knowledge.knowledgegraphnode')),
                ('target', models.ForeignKey(help_text='Target node of the edge', on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='knowledge.knowledgegraphnode')),
            ],
            options={
                'verbose_name_plural': 'knowledge graph edges',
                'ordering': ['edge_type', 'source__label'],
                'indexes': [models.Index(fields=['source', 'edge_type'], name='knowledge_k_source__cdb1df_idx'), models.Index(fields=['target', 'edge_type'], name='knowledge_k_target__6f3244_idx'), models.Index(fields=['edge_type', 'is_active'], name='knowledge_k_edge_ty_31e6ba_idx')],
            },
        ),
    ]
