# Generated by Django 6.0.6 on 2026-07-11 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0006_v42_knowledge_graph'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebaseentry',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='Approval timestamp', null=True),
        ),
        migrations.AddField(
            model_name='knowledgebaseentry',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Clinical reviewer who approved', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_rules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='knowledgebaseentry',
            name='author',
            field=models.ForeignKey(blank=True, help_text='Original rule author', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_rules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='knowledgebaseentry',
            name='confidence_score',
            field=models.FloatField(default=0.0, help_text='AI confidence score (0-100)'),
        ),
        migrations.AddField(
            model_name='knowledgebaseentry',
            name='date_validated',
            field=models.DateField(blank=True, help_text='Last validation date', null=True),
        ),
        migrations.AddField(
            model_name='knowledgebaseentry',
            name='explanation',
            field=models.TextField(blank=True, help_text='Human-readable reasoning for this rule'),
        ),
        migrations.AddField(
            model_name='knowledgebaseentry',
            name='knowledge_version',
            field=models.CharField(blank=True, help_text='Knowledge base version when rule was created', max_length=50),
        ),
        migrations.AddField(
            model_name='knowledgebaseentry',
            name='next_review_date',
            field=models.DateField(blank=True, help_text='Scheduled re-review date', null=True),
        ),
        migrations.AddField(
            model_name='knowledgebaseentry',
            name='override_allowed',
            field=models.BooleanField(default=True, help_text='Whether clinicians can override this recommendation'),
        ),
        migrations.AddField(
            model_name='knowledgebaseentry',
            name='recommendation_id',
            field=models.CharField(blank=True, help_text='Guideline recommendation ID (e.g. KDIGO-2021-IGAN-4.1.3)', max_length=100),
        ),
    ]
