# Generated by Django 6.0.6 on 2026-07-11 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0007_knowledgebaseentry_approved_at_and_more'),
        ('patients', '0005_site_patient_site_usersiterole'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_id', models.CharField(help_text='Unique recommendation ID', max_length=100, unique=True)),
                ('recommendation_type', models.CharField(choices=[('investigation', 'Investigation recommendation'), ('drug_toxicity', 'Drug toxicity alert'), ('treatment_failure', 'Treatment failure alert'), ('management_plan', 'Management plan'), ('monitoring_plan', 'Monitoring plan'), ('followup', 'Follow-up scheduling'), ('disease_validation', 'Disease validation'), ('clinical_reasoning', 'Clinical reasoning output')], db_index=True, max_length=30)),
                ('disease_id', models.CharField(db_index=True, max_length=50)),
                ('recommendation_text', models.TextField(help_text='Human-readable recommendation')),
                ('clinical_rationale', models.TextField(help_text='Why this recommendation was made')),
                ('guideline', models.CharField(help_text="e.g. 'KDIGO 2021'", max_length=200)),
                ('guideline_version', models.CharField(help_text="e.g. '2021'", max_length=50)),
                ('guideline_section', models.CharField(blank=True, help_text="e.g. 'Section 4.1'", max_length=200)),
                ('guideline_recommendation_id', models.CharField(blank=True, help_text="e.g. 'KDIGO-2021-IGAN-4.1.3'", max_length=100)),
                ('evidence_grade', models.CharField(help_text="e.g. '1A', '2B', 'OP'", max_length=10)),
                ('evidence_source', models.URLField(blank=True, help_text='Evidence URL or DOI', max_length=500)),
                ('confidence_score', models.FloatField(default=0.0, help_text='AI confidence (0-100)')),
                ('kb_rule_id', models.CharField(blank=True, help_text='Knowledge base rule ID (e.g. KB-IGA-001)', max_length=50)),
                ('kb_version', models.CharField(blank=True, help_text='KB version when rule was applied', max_length=50)),
                ('validation_date', models.DateField(help_text='When this recommendation was validated')),
                ('next_review_date', models.DateField(blank=True, help_text='Scheduled re-review', null=True)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('overridden', 'Overridden')], default='pending', max_length=20)),
                ('override_allowed', models.BooleanField(default=True, help_text='Can clinician override?')),
                ('override_reason', models.TextField(blank=True, help_text='If overridden, why')),
                ('explanation', models.TextField(help_text='Full reasoning chain for this recommendation')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('clinician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_recommendations', to=settings.AUTH_USER_MODEL)),
                ('expert_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_recommendations', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_audits', to='patients.patient')),
            ],
            options={
                'ordering': ['-issued_at'],
                'indexes': [models.Index(fields=['patient', 'recommendation_type'], name='knowledge_r_patient_7a6f47_idx'), models.Index(fields=['disease_id', 'approval_status'], name='knowledge_r_disease_d61085_idx'), models.Index(fields=['kb_rule_id'], name='knowledge_r_kb_rule_9103c3_idx'), models.Index(fields=['issued_at'], name='knowledge_r_issued__e0b360_idx')],
            },
        ),
    ]
