# Generated by Django 6.0.6 on 2026-07-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0008_recommendationaudit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendationaudit',
            name='evidence_grade',
            field=models.CharField(choices=[('1', 'Level 1 (Strong recommendation)'), ('2', 'Level 2 (Weak recommendation)'), ('NG', 'Not graded'), ('OP', 'Expert opinion')], default='NG', help_text='Evidence grade: 1=Strong, 2=Weak, NG=Not Graded, OP=Expert Opinion', max_length=2),
        ),
    ]
