# Generated by Django 6.0.6 on 2026-06-19 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalEncounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encounter_date', models.DateField()),
                ('encounter_type', models.CharField(choices=[('baseline', 'Baseline / enrollment'), ('followup', 'Scheduled follow-up'), ('unscheduled', 'Unscheduled / sick visit')], default='followup', max_length=16)),
                ('clinic_location', models.CharField(blank=True, max_length=120)),
                ('systolic_bp', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('diastolic_bp', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('advice', models.TextField(blank=True)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encounters', to='patients.patient')),
                ('seen_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encounters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-encounter_date'],
                'indexes': [models.Index(fields=['patient', 'encounter_date'], name='encounters__patient_36ea25_idx')],
            },
        ),
    ]
