# Generated by Django 6.0.6 on 2026-06-19 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('eskd', 'ESKD / kidney failure'), ('dialysis_start', 'Dialysis started'), ('transplant', 'Kidney transplant'), ('death', 'Death'), ('complete_remission', 'Complete remission'), ('partial_remission', 'Partial remission'), ('relapse', 'Relapse / flare'), ('major_cv', 'Major cardiovascular event')], max_length=20)),
                ('event_date', models.DateField()),
                ('notes', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='encounters.clinicalencounter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='patients.patient')),
            ],
            options={
                'ordering': ['patient', 'event_date'],
                'indexes': [models.Index(fields=['patient', 'event_type', 'event_date'], name='encounters__patient_7bd9da_idx')],
            },
        ),
    ]
