# Generated by Django 6.0.6 on 2026-07-02 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0002_clinicalevent'),
        ('pathology', '0005_biopsy_indication_biopsy_result_category'),
        ('patients', '0004_patient_current_phase_patient_registration_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalencounter',
            name='clinician_response',
            field=models.CharField(blank=True, choices=[('not_assessed', 'Not assessed'), ('complete', 'Complete remission'), ('partial', 'Partial remission'), ('none', 'No response'), ('stable', 'Stable / maintenance')], max_length=16),
        ),
        migrations.AddField(
            model_name='clinicalencounter',
            name='disease_phase',
            field=models.CharField(blank=True, choices=[('active', 'Active disease (pre-remission)'), ('remission', 'In remission'), ('post_remission', 'Post-remission monitoring'), ('relapse', 'Relapse')], max_length=16),
        ),
        migrations.AddField(
            model_name='clinicalencounter',
            name='edema_grade',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Peripheral oedema 0 (none) – 4 (anasarca).', null=True),
        ),
        migrations.AddField(
            model_name='clinicalencounter',
            name='symptoms',
            field=models.CharField(blank=True, help_text='Frothy urine, haematuria, breathlessness, etc.', max_length=240),
        ),
        migrations.AddField(
            model_name='clinicalencounter',
            name='treatment_adjusted',
            field=models.BooleanField(default=False, help_text='Was therapy changed at this visit?'),
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admit_date', models.DateField()),
                ('discharge_date', models.DateField(blank=True, null=True)),
                ('ward', models.CharField(blank=True, max_length=80)),
                ('reason', models.CharField(blank=True, help_text='Reason for admission / work-up.', max_length=240)),
                ('baseline_captured', models.BooleanField(default=False, help_text='Pre-discharge baseline data form completed.')),
                ('discharge_advice', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('biopsy', models.ForeignKey(blank=True, help_text='Biopsy done during this admission.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='pathology.biopsy')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='patients.patient')),
            ],
            options={
                'ordering': ['patient', '-admit_date'],
                'indexes': [models.Index(fields=['patient', 'admit_date'], name='encounters__patient_4bb8bf_idx')],
            },
        ),
        migrations.CreateModel(
            name='RelapseEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relapse_date', models.DateField()),
                ('relapse_type', models.CharField(choices=[('proteinuric', 'Proteinuric relapse'), ('nephrotic', 'Nephrotic relapse'), ('nephritic', 'Nephritic flare'), ('functional', 'Functional (rising creatinine)'), ('serologic', 'Serologic (e.g. rising anti-PLA2R / dsDNA)')], max_length=16)),
                ('criteria', models.CharField(blank=True, help_text="Criteria met, e.g. 'UPCR 0.4→3.2 g/g; albumin 2.6'.", max_length=240)),
                ('action_taken', models.CharField(blank=True, help_text='Treatment change in response.', max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relapses', to='encounters.clinicalencounter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relapses', to='patients.patient')),
            ],
            options={
                'ordering': ['patient', '-relapse_date'],
                'indexes': [models.Index(fields=['patient', 'relapse_date'], name='encounters__patient_f718aa_idx')],
            },
        ),
    ]
