# Generated by Django 5.2.16 on 2026-09-27 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0002_alter_vitalsign_options_vitalsign_measured_at_and_more'),
        ('encounters', '0003_clinicalencounter_clinician_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalencounter',
            name='selected_vital',
            field=models.ForeignKey(blank=True, help_text='The reading displayed and printed for this visit.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='clinical.vitalsign'),
        ),
    ]
