# Generated by Django 6.0.6 on 2026-07-08 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(choices=[('patient', 'Patient'), ('encounter', 'Encounter'), ('clinical', 'Clinical Assessment'), ('lab', 'Laboratory'), ('biopsy', 'Biopsy'), ('decision', 'Decision Support')], max_length=20)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('event_date', models.DateTimeField(db_index=True)),
                ('summary', models.CharField(max_length=500)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('source_id', models.CharField(blank=True, help_text='ID of the source entity', max_length=100)),
                ('source_url', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='patients.patient')),
            ],
            options={
                'ordering': ['-event_date', '-created_at'],
                'indexes': [models.Index(fields=['patient', 'domain'], name='timeline_ti_patient_255f05_idx'), models.Index(fields=['patient', '-event_date'], name='timeline_ti_patient_8617b8_idx')],
            },
        ),
    ]
