# Generated by Django 6.0.6 on 2026-06-19 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_date', models.DateField(blank=True, null=True)),
                ('baseline_egfr', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('baseline_creatinine', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('baseline_upcr', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('last_contact_date', models.DateField(blank=True, null=True)),
                ('followup_days', models.IntegerField(blank=True, null=True)),
                ('n_egfr', models.IntegerField(default=0)),
                ('latest_egfr', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('egfr_slope', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('sustained_40_decline', models.BooleanField(default=False)),
                ('sustained_40_date', models.DateField(blank=True, null=True)),
                ('sustained_50_decline', models.BooleanField(default=False)),
                ('sustained_50_date', models.DateField(blank=True, null=True)),
                ('doubling_creatinine', models.BooleanField(default=False)),
                ('doubling_date', models.DateField(blank=True, null=True)),
                ('eskd', models.BooleanField(default=False)),
                ('eskd_date', models.DateField(blank=True, null=True)),
                ('death', models.BooleanField(default=False)),
                ('death_date', models.DateField(blank=True, null=True)),
                ('composite_kidney_event', models.BooleanField(default=False)),
                ('composite_date', models.DateField(blank=True, null=True)),
                ('composite_cause', models.CharField(blank=True, max_length=40)),
                ('remission_status', models.CharField(choices=[('none', 'No remission'), ('partial', 'Partial remission'), ('complete', 'Complete remission')], default='none', max_length=10)),
                ('any_relapse', models.BooleanField(default=False)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outcome', to='patients.patient')),
            ],
            options={
                'ordering': ['patient'],
            },
        ),
    ]
