# Generated by Django 6.0.6 on 2026-06-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientoutcome',
            name='any_remission_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientoutcome',
            name='best_proteinuria_reduction_pct',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='patientoutcome',
            name='complete_remission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientoutcome',
            name='complete_remission_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientoutcome',
            name='latest_upcr',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='patientoutcome',
            name='nadir_upcr',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='patientoutcome',
            name='partial_remission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientoutcome',
            name='partial_remission_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientoutcome',
            name='proteinuria_relapse',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientoutcome',
            name='proteinuria_relapse_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
