# Generated by Django 6.0.6 on 2026-06-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_patientoutcome_any_remission_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientoutcome',
            name='igan_proteinuria_response',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientoutcome',
            name='igan_proteinuria_response_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientoutcome',
            name='proteinuria_source',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='patientoutcome',
            name='remission_definition',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
