# Generated by Django 6.0.6 on 2026-07-15 18:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge', '0009_alter_recommendationaudit_evidence_grade'),
        ('patients', '0007_longitudinal_gn_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Feedback Configuration',
                'verbose_name_plural': 'Feedback Configurations',
            },
        ),
        migrations.CreateModel(
            name='AIFailureLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('failure_type', models.CharField(choices=[('diagnosis', 'Diagnosis'), ('treatment', 'Treatment'), ('monitoring', 'Monitoring'), ('investigation', 'Investigation')], db_index=True, max_length=20)),
                ('patient_id_hash', models.CharField(blank=True, max_length=64)),
                ('disease', models.CharField(blank=True, max_length=100)),
                ('missing_data', models.JSONField(blank=True, null=True)),
                ('reasoning_chain', models.JSONField(blank=True, null=True)),
                ('rules_evaluated', models.JSONField(blank=True, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('knowledge_version', models.CharField(blank=True, max_length=50)),
                ('evidence_retrieved', models.JSONField(blank=True, null=True)),
                ('ai_output', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'AI Failure Log',
                'verbose_name_plural': 'AI Failure Logs',
                'indexes': [models.Index(fields=['failure_type', 'confidence'], name='feedback_ai_failure_922489_idx'), models.Index(fields=['disease'], name='feedback_ai_disease_4b69ab_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClinicalConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('patient_id_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('disease', models.CharField(blank=True, db_index=True, max_length=100)),
                ('ai_recommendation', models.TextField(blank=True)),
                ('clinician_decision', models.TextField(blank=True)),
                ('difference', models.TextField(blank=True)),
                ('reason', models.TextField(blank=True)),
                ('ai_confidence', models.FloatField(blank=True, null=True)),
                ('guideline_ref', models.CharField(blank=True, max_length=200)),
                ('knowledge_rule_id', models.CharField(blank=True, max_length=50)),
                ('resolved', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Clinical Conflict',
                'verbose_name_plural': 'Clinical Conflicts',
                'indexes': [models.Index(fields=['disease', 'resolved'], name='feedback_cl_disease_01734a_idx'), models.Index(fields=['knowledge_rule_id'], name='feedback_cl_knowled_83829b_idx')],
            },
        ),
        migrations.CreateModel(
            name='CrashReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('exception_type', models.CharField(max_length=200)),
                ('exception_message', models.TextField(blank=True)),
                ('stack_trace', models.TextField(blank=True)),
                ('module', models.CharField(blank=True, max_length=100)),
                ('patient_id_hash', models.CharField(blank=True, max_length=64)),
                ('encounter_id_hash', models.CharField(blank=True, max_length=64)),
                ('url', models.CharField(blank=True, max_length=1000)),
                ('workflow', models.CharField(blank=True, max_length=200)),
                ('memory_usage_mb', models.FloatField(blank=True, null=True)),
                ('recent_actions', models.JSONField(blank=True, null=True)),
                ('app_version', models.CharField(blank=True, max_length=50)),
                ('knowledge_version', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Crash Report',
                'verbose_name_plural': 'Crash Reports',
                'indexes': [models.Index(fields=['exception_type', 'timestamp'], name='feedback_cr_excepti_715be0_idx'), models.Index(fields=['module'], name='feedback_cr_module_16e14e_idx')],
            },
        ),
        migrations.CreateModel(
            name='FeedbackExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('filename', models.CharField(max_length=500)),
                ('size_bytes', models.IntegerField(blank=True, null=True)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('included_sections', models.JSONField(default=list)),
                ('export_hash', models.CharField(blank=True, max_length=64)),
                ('exported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback Export',
                'verbose_name_plural': 'Feedback Exports',
                'ordering': ['-exported_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('conflict_type', models.CharField(choices=[('recommendation_vs_guideline', 'Recommendation vs Guideline'), ('treatment_vs_contraindication', 'Treatment vs Contraindication'), ('biopsy_vs_diagnosis', 'Biopsy vs Diagnosis'), ('diagnosis_vs_pathology', 'Diagnosis vs Pathology'), ('ckd_vs_egfr', 'CKD Stage vs eGFR'), ('drug_contraindication', 'Drug Contraindication'), ('duplicate_diagnosis', 'Duplicate Diagnosis'), ('missing_followup', 'Missing Follow-up'), ('missing_investigation', 'Missing Investigation')], db_index=True, max_length=50)),
                ('patient_id_hash', models.CharField(blank=True, max_length=64)),
                ('disease', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('rule_id_a', models.CharField(blank=True, max_length=50)),
                ('rule_id_b', models.CharField(blank=True, max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('resolved', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Knowledge Conflict',
                'verbose_name_plural': 'Knowledge Conflicts',
                'indexes': [models.Index(fields=['conflict_type', 'severity'], name='feedback_kn_conflic_2fd3df_idx'), models.Index(fields=['disease'], name='feedback_kn_disease_49f545_idx')],
            },
        ),
        migrations.CreateModel(
            name='RuleFailureLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('rule_id', models.CharField(db_index=True, max_length=50)),
                ('disease', models.CharField(blank=True, max_length=100)),
                ('condition', models.JSONField(blank=True, null=True)),
                ('missing_feature', models.CharField(blank=True, max_length=200)),
                ('exception_message', models.TextField(blank=True)),
                ('knowledge_version', models.CharField(blank=True, max_length=50)),
                ('patient_feature_summary', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Rule Failure Log',
                'verbose_name_plural': 'Rule Failure Logs',
                'indexes': [models.Index(fields=['rule_id', 'timestamp'], name='feedback_ru_rule_id_d89949_idx'), models.Index(fields=['disease'], name='feedback_ru_disease_ea2a6b_idx')],
            },
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('app_version', models.CharField(blank=True, max_length=50)),
                ('knowledge_version', models.CharField(blank=True, max_length=50)),
                ('os_version', models.CharField(blank=True, max_length=200)),
                ('db_version', models.CharField(blank=True, max_length=50)),
                ('module', models.CharField(blank=True, db_index=True, max_length=100)),
                ('page', models.CharField(blank=True, max_length=500)),
                ('action', models.CharField(blank=True, max_length=200)),
                ('stack_trace', models.TextField(blank=True)),
                ('error_type', models.CharField(blank=True, max_length=200)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='error', max_length=20)),
                ('recovered_automatically', models.BooleanField(default=False)),
                ('request_data', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Error Log',
                'verbose_name_plural': 'Error Logs',
                'indexes': [models.Index(fields=['severity', 'timestamp'], name='feedback_er_severit_75a666_idx'), models.Index(fields=['module', 'error_type'], name='feedback_er_module_2d3efc_idx')],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeImprovementSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('rule_id', models.CharField(db_index=True, max_length=50)),
                ('disease', models.CharField(blank=True, db_index=True, max_length=100)),
                ('override_count', models.PositiveIntegerField(default=0)),
                ('common_override_reason', models.TextField(blank=True)),
                ('current_recommendation', models.TextField(blank=True)),
                ('suggested_change', models.TextField(blank=True)),
                ('supporting_evidence', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Knowledge Improvement Suggestion',
                'verbose_name_plural': 'Knowledge Improvement Suggestions',
                'indexes': [models.Index(fields=['status', 'override_count'], name='feedback_kn_status_e444c9_idx'), models.Index(fields=['disease', 'rule_id'], name='feedback_kn_disease_6bf195_idx')],
            },
        ),
        migrations.CreateModel(
            name='PerformanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('metric_name', models.CharField(choices=[('startup_time', 'Application Startup Time'), ('knowledge_loading', 'Knowledge Loading Time'), ('reasoning_time', 'Clinical Reasoning Time'), ('patient_loading', 'Patient Loading Time'), ('db_query', 'Database Query Duration'), ('slow_page', 'Slow Page Load'), ('memory_usage', 'Memory Usage'), ('cpu_usage', 'CPU Usage')], db_index=True, max_length=30)),
                ('duration_ms', models.FloatField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, help_text='Numeric value for non-duration metrics (MB, %, etc.)', null=True)),
                ('module', models.CharField(blank=True, max_length=100)),
                ('page', models.CharField(blank=True, max_length=500)),
                ('url', models.CharField(blank=True, max_length=1000)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Performance Log',
                'verbose_name_plural': 'Performance Logs',
                'indexes': [models.Index(fields=['metric_name', 'timestamp'], name='feedback_pe_metric__7eb420_idx'), models.Index(fields=['module'], name='feedback_pe_module_8eccac_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('feedback_type', models.CharField(choices=[('software_bug', 'Software Bug'), ('incorrect_recommendation', 'Incorrect Recommendation'), ('missing_guideline', 'Missing Guideline'), ('workflow_issue', 'Workflow Issue'), ('ui_issue', 'UI Issue'), ('suggestion', 'Suggestion'), ('feature_request', 'Feature Request'), ('clinical_concern', 'Clinical Concern')], db_index=True, max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='feedback_screenshots/')),
                ('page_url', models.CharField(blank=True, max_length=1000)),
                ('resolved', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Feedback',
                'verbose_name_plural': 'User Feedback',
                'indexes': [models.Index(fields=['feedback_type', 'resolved'], name='feedback_us_feedbac_b1d243_idx'), models.Index(fields=['user'], name='feedback_us_user_id_819323_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkflowFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('feedback_type', models.CharField(choices=[('diagnosis', 'Diagnosis Suggestions'), ('treatment_plan', 'Treatment Plans'), ('followup_plan', 'Follow-up Plans'), ('investigation_plan', 'Investigation Plans'), ('clinical_reasoning', 'Clinical Reasoning')], db_index=True, max_length=30)),
                ('rating', models.PositiveSmallIntegerField()),
                ('comments', models.TextField(blank=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.patient')),
                ('recommendation_audit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='knowledge.recommendationaudit')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workflow Feedback',
                'verbose_name_plural': 'Workflow Feedback',
                'indexes': [models.Index(fields=['feedback_type', 'rating'], name='feedback_wo_feedbac_0f6a2c_idx'), models.Index(fields=['user'], name='feedback_wo_user_id_78490b_idx')],
            },
        ),
    ]
