# Generated by Django 6.0.6 on 2026-07-16 04:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetrySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Enable automatic error reporting')),
                ('sync_interval', models.CharField(choices=[('hourly', 'Hourly'), ('6h', 'Every 6 Hours'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('manual', 'Manual Only')], default='daily', max_length=10)),
                ('auto_crash_reporting', models.BooleanField(default=True)),
                ('auto_performance_reporting', models.BooleanField(default=False)),
                ('github_repo', models.CharField(default='arkoamit-bot/GDES', help_text='GitHub repo for issue reporting (owner/repo)', max_length=200)),
                ('github_token', models.CharField(blank=True, help_text='GitHub Personal Access Token (stored locally)', max_length=200)),
                ('last_upload', models.DateTimeField(blank=True, null=True)),
                ('pending_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Telemetry Settings',
                'verbose_name_plural': 'Telemetry Settings',
            },
        ),
        migrations.CreateModel(
            name='UploadBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='running', max_length=10)),
                ('errors_uploaded', models.PositiveIntegerField(default=0)),
                ('errors_failed', models.PositiveIntegerField(default=0)),
                ('errors_skipped', models.PositiveIntegerField(default=0)),
                ('trigger', models.CharField(default='scheduled', help_text='scheduled | manual | startup | critical', max_length=50)),
                ('log_output', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Upload Batch',
                'verbose_name_plural': 'Upload Batches',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ErrorOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(db_index=True, help_text='SHA-256 of (exception_type + module + line + stack_hash)', max_length=64, unique=True)),
                ('exception_type', models.CharField(db_index=True, max_length=200)),
                ('exception_message', models.TextField(blank=True)),
                ('module', models.CharField(blank=True, db_index=True, max_length=200)),
                ('function_name', models.CharField(blank=True, max_length=200)),
                ('line_number', models.PositiveIntegerField(blank=True, null=True)),
                ('stack_trace', models.TextField(blank=True)),
                ('stack_hash', models.CharField(blank=True, help_text='Hash of the de-parameterized stack trace', max_length=64)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='error', max_length=20)),
                ('occurrence_count', models.PositiveIntegerField(default=1)),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('queue_state', models.CharField(choices=[('pending', 'Pending'), ('uploaded', 'Uploaded'), ('failed', 'Failed'), ('ignored', 'Ignored')], db_index=True, default='pending', max_length=10)),
                ('github_issue_number', models.PositiveIntegerField(blank=True, null=True)),
                ('github_issue_url', models.CharField(blank=True, max_length=500)),
                ('last_upload_attempt', models.DateTimeField(blank=True, null=True)),
                ('upload_fail_count', models.PositiveIntegerField(default=0)),
                ('app_version', models.CharField(blank=True, max_length=50)),
                ('os_version', models.CharField(blank=True, max_length=200)),
                ('python_version', models.CharField(blank=True, max_length=50)),
                ('django_version', models.CharField(blank=True, max_length=50)),
                ('sample_context', models.JSONField(blank=True, help_text='Sanitized request context from the most recent occurrence', null=True)),
            ],
            options={
                'verbose_name': 'Error Occurrence',
                'verbose_name_plural': 'Error Occurrences',
                'ordering': ['-last_seen'],
                'indexes': [models.Index(fields=['queue_state', 'severity'], name='feedback_er_queue_s_b222bf_idx'), models.Index(fields=['exception_type', 'module'], name='feedback_er_excepti_07bce3_idx')],
            },
        ),
    ]
