# Generated by Django 6.0.6 on 2026-07-16 21:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_telemetrysettings_uploadbatch_erroroccurrence'),
        ('knowledge', '0009_alter_recommendationaudit_evidence_grade'),
        ('patients', '0007_longitudinal_gn_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowfeedback',
            name='action',
            field=models.CharField(blank=True, choices=[('accept', 'Accepted'), ('modify', 'Modified'), ('reject', 'Rejected')], db_index=True, max_length=10),
        ),
        migrations.AddField(
            model_name='workflowfeedback',
            name='recommendation_ref',
            field=models.CharField(blank=True, help_text='What the feedback is about (e.g. differential:iga, management_plan:membranous).', max_length=120),
        ),
        migrations.AlterField(
            model_name='workflowfeedback',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='workflowfeedback',
            index=models.Index(fields=['action', 'feedback_type'], name='feedback_wo_action_2b8abd_idx'),
        ),
    ]
