# Generated by Django 6.0.6 on 2026-07-17 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_workflowfeedback_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telemetrysettings',
            name='github_repo',
            field=models.CharField(default='arkoamit-bot/GDES-releases', help_text='GitHub repo for issue reporting (owner/repo)', max_length=200),
        ),
    ]
