# Generated by Django 6.0.6 on 2026-07-09 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0004_patient_current_phase_patient_registration_date_and_more'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientCommunicationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_channel', models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('app', 'In-app notification')], default='sms', max_length=10)),
                ('phone', models.CharField(blank=True, help_text='Override phone for SMS/WhatsApp', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Override email address', max_length=200)),
                ('reminder_follow_up', models.BooleanField(default=True)),
                ('reminder_lab', models.BooleanField(default=True)),
                ('reminder_medication', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comm_preferences', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='ReminderTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('follow_up', 'Follow-up visit reminder'), ('lab_test', 'Lab test reminder'), ('medication', 'Medication adherence reminder'), ('monitoring', 'Monitoring parameter reminder'), ('general', 'General notification')], max_length=20)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('app', 'In-app notification')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('template_body', models.TextField(help_text='Template with placeholders like {{patient_name}}, {{visit_date}}, {{clinic_address}}')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('reminder_type', 'channel', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ReminderSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('follow_up', 'Follow-up visit reminder'), ('lab_test', 'Lab test reminder'), ('medication', 'Medication adherence reminder'), ('monitoring', 'Monitoring parameter reminder'), ('general', 'General notification')], max_length=20)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('app', 'In-app notification')], default='sms', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('scheduled_at', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='patients.patient')),
                ('scheduled_visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders', to='scheduling.scheduledvisit')),
            ],
            options={
                'ordering': ['-scheduled_at'],
                'indexes': [models.Index(fields=['status', 'scheduled_at'], name='reminders_r_status_d49a76_idx'), models.Index(fields=['patient', 'status'], name='reminders_r_patient_240279_idx')],
            },
        ),
    ]
