# Generated by Django 6.0.6 on 2026-06-19 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_type', models.CharField(choices=[('serum', 'Serum'), ('plasma', 'Plasma'), ('urine', 'Urine'), ('dna', 'DNA'), ('tissue', 'Tissue')], max_length=8)),
                ('collection_date', models.DateField()),
                ('volume_ml', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('aliquots', models.PositiveSmallIntegerField(default=1)),
                ('storage_location', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('stored', 'Stored'), ('depleted', 'Depleted'), ('shipped', 'Shipped')], default='stored', max_length=8)),
                ('notes', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='patients.patient')),
            ],
            options={
                'ordering': ['patient', '-collection_date'],
            },
        ),
    ]
