# Generated by Django 6.0.6 on 2026-06-19 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('encounters', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_name', models.CharField(max_length=120, unique=True)),
                ('brand_names', models.JSONField(blank=True, default=list, help_text='List of common brand names.')),
                ('drug_class', models.CharField(choices=[('raasi', 'RAAS inhibitor (ACEi/ARB)'), ('sglt2i', 'SGLT2 inhibitor'), ('finerenone', 'Finerenone (ns-MRA)'), ('hcq', 'Hydroxychloroquine'), ('steroid', 'Corticosteroid'), ('mmf', 'Mycophenolate'), ('azathioprine', 'Azathioprine'), ('cyclophosphamide', 'Cyclophosphamide'), ('cni', 'Calcineurin inhibitor'), ('rituximab', 'Rituximab'), ('diuretic', 'Diuretic'), ('statin', 'Statin'), ('other', 'Other / not research-coded')], default='other', max_length=20)),
                ('available_strengths', models.JSONField(blank=True, default=list, help_text='e.g. ["5 mg", "10 mg", "20 mg"]')),
                ('default_frequency', models.CharField(blank=True, help_text='e.g. "1+0+1" or "once daily"', max_length=40)),
                ('default_route', models.CharField(blank=True, default='PO', max_length=20)),
                ('renal_dose_adjust', models.BooleanField(default=False)),
                ('egfr_caution_below', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['generic_name'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentExposure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=120)),
                ('dose', models.CharField(blank=True, max_length=40)),
                ('dose_unit', models.CharField(blank=True, max_length=20)),
                ('frequency', models.CharField(blank=True, max_length=40)),
                ('route', models.CharField(blank=True, default='PO', max_length=20)),
                ('start_date', models.DateField()),
                ('stop_date', models.DateField(blank=True, null=True)),
                ('ongoing', models.BooleanField(default=True)),
                ('stop_reason', models.CharField(blank=True, choices=[('remission', 'Remission / goal achieved'), ('non_response', 'Non-response'), ('intolerance', 'Intolerance / side-effect'), ('adverse_event', 'Adverse event'), ('cost', 'Cost / access'), ('dose_change', 'Dose/regimen changed (episode split)'), ('switch', 'Switched to another agent'), ('completed', 'Planned course completed'), ('other', 'Other / unspecified')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_by_encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_exposures', to='encounters.clinicalencounter')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exposures', to='treatments.drugmaster')),
                ('opened_by_encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_exposures', to='encounters.clinicalencounter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exposures', to='patients.patient')),
            ],
            options={
                'ordering': ['patient', 'drug__generic_name', 'start_date'],
                'indexes': [models.Index(fields=['patient', 'ongoing'], name='treatments__patient_a47d45_idx'), models.Index(fields=['drug', 'ongoing'], name='treatments__drug_id_eb9e64_idx')],
            },
        ),
    ]
