# Generated by Django 6.0.6 on 2026-07-02 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugmaster',
            name='available_routes',
            field=models.JSONField(blank=True, default=list, help_text='Routes of administration, e.g. ["PO", "IV"].'),
        ),
        migrations.AddField(
            model_name='drugmaster',
            name='strengths_by_route',
            field=models.JSONField(blank=True, default=dict, help_text='Strengths per route, e.g. {"IV": ["500 mg vial", "1 g vial"]}.'),
        ),
        migrations.AlterField(
            model_name='drugmaster',
            name='brand_names',
            field=models.JSONField(blank=True, default=list, help_text='Common Bangladeshi brand names, most-used first.'),
        ),
    ]
