# Generated by Django 6.0.6 on 2026-07-03 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0002_drugmaster_available_routes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugmaster',
            name='drug_class',
            field=models.CharField(choices=[('raasi', 'RAAS inhibitor (ACEi/ARB)'), ('sglt2i', 'SGLT2 inhibitor'), ('finerenone', 'Finerenone (ns-MRA)'), ('hcq', 'Hydroxychloroquine'), ('steroid', 'Corticosteroid'), ('mmf', 'Mycophenolate'), ('azathioprine', 'Azathioprine'), ('cyclophosphamide', 'Cyclophosphamide'), ('cni', 'Calcineurin inhibitor'), ('rituximab', 'Rituximab'), ('diuretic', 'Diuretic'), ('statin', 'Statin'), ('insulin', 'Insulin'), ('metformin', 'Metformin (biguanide)'), ('sulfonylurea', 'Sulfonylurea'), ('dpp4i', 'DPP-4 inhibitor'), ('glp1', 'GLP-1 receptor agonist'), ('other', 'Other / not research-coded')], default='other', max_length=20),
        ),
    ]
