# Generated by Django 6.0.6 on 2026-07-10 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0003_alter_drugmaster_drug_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugmaster',
            name='dialysis_dose_adjust',
            field=models.BooleanField(default=False, help_text='Requires dose adjustment/administration timing with dialysis'),
        ),
        migrations.AddField(
            model_name='drugmaster',
            name='hepatic_dose_adjust',
            field=models.BooleanField(default=False, help_text='Requires dose adjustment in hepatic impairment'),
        ),
        migrations.AddField(
            model_name='drugmaster',
            name='indications',
            field=models.JSONField(blank=True, default=list, help_text='Approved indications: list of disease/condition identifiers'),
        ),
        migrations.AddField(
            model_name='drugmaster',
            name='lactation_safety',
            field=models.CharField(blank=True, help_text='Lactation safety: safe, caution, contraindicated, unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='drugmaster',
            name='nephrotoxic',
            field=models.BooleanField(default=False, help_text='Known nephrotoxic agent'),
        ),
        migrations.AddField(
            model_name='drugmaster',
            name='pregnancy_category',
            field=models.CharField(blank=True, help_text='FDA pregnancy category (A, B, C, D, X, N)', max_length=3),
        ),
    ]
