# Generated by Django 6.0.6 on 2026-07-10 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0004_v35_drug_certification_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugmaster',
            name='common_side_effects',
            field=models.JSONField(blank=True, default=list, help_text='Common adverse effects (frequency >= 1%)'),
        ),
        migrations.AddField(
            model_name='drugmaster',
            name='evidence_level',
            field=models.CharField(blank=True, choices=[('1', 'Level 1 (Strong recommendation)'), ('2', 'Level 2 (Weak recommendation)'), ('NG', 'Not graded'), ('OP', 'Expert opinion')], help_text='GRADE evidence level for GN indications', max_length=2),
        ),
        migrations.AddField(
            model_name='drugmaster',
            name='guideline_recommendations',
            field=models.JSONField(blank=True, default=list, help_text='Guideline recommendations referencing this drug: [{source, chapter, recommendation}]'),
        ),
        migrations.AddField(
            model_name='drugmaster',
            name='maximum_dose',
            field=models.CharField(blank=True, help_text='Maximum recommended daily dose', max_length=100),
        ),
        migrations.AddField(
            model_name='drugmaster',
            name='mechanism_of_action',
            field=models.TextField(blank=True, help_text='Pharmacological mechanism of action'),
        ),
        migrations.AddField(
            model_name='drugmaster',
            name='monitoring_parameters',
            field=models.TextField(blank=True, help_text='Required monitoring: labs, vitals, levels'),
        ),
        migrations.AddField(
            model_name='drugmaster',
            name='serious_side_effects',
            field=models.JSONField(blank=True, default=list, help_text='Serious adverse effects requiring attention'),
        ),
        migrations.AddField(
            model_name='drugmaster',
            name='stopping_criteria',
            field=models.TextField(blank=True, help_text='Criteria for stopping or holding the drug'),
        ),
        migrations.AddField(
            model_name='drugmaster',
            name='transplant_considerations',
            field=models.TextField(blank=True, help_text='Special considerations in transplant patients'),
        ),
        migrations.AddField(
            model_name='drugmaster',
            name='typical_dosage',
            field=models.CharField(blank=True, help_text='Typical starting and maintenance dosage', max_length=200),
        ),
    ]
