# Generated by Django 6.0.6 on 2026-07-31 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0003_clinicalencounter_clinician_response_and_more'),
        ('patients', '0008_patient_cvd_history_patient_diabetic_foot_history_and_more'),
        ('treatments', '0005_drugmaster_common_side_effects_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='treatmentexposure',
            constraint=models.UniqueConstraint(condition=models.Q(('ongoing', True)), fields=('patient', 'drug'), name='one_ongoing_exposure_per_drug'),
        ),
    ]
