# Generated by Django 5.2.16 on 2026-09-26 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0006_treatmentexposure_one_ongoing_exposure_per_drug'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('running', 'Running'), ('success', 'Succeeded'), ('unchanged', 'Succeeded (catalogue unchanged)'), ('skipped', 'Skipped'), ('failed', 'Failed')], db_index=True, default='running', max_length=12)),
                ('trigger', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled')], default='scheduled', max_length=12)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('pages_fetched', models.PositiveIntegerField(default=0)),
                ('total_pages', models.PositiveIntegerField(default=0)),
                ('rows_scraped', models.PositiveIntegerField(default=0)),
                ('content_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('generics_created', models.PositiveIntegerField(default=0)),
                ('generics_updated', models.PositiveIntegerField(default=0)),
                ('brands_added', models.PositiveIntegerField(default=0)),
                ('strengths_added', models.PositiveIntegerField(default=0)),
                ('routes_added', models.PositiveIntegerField(default=0)),
                ('rows_merged', models.PositiveIntegerField(default=0)),
                ('rows_deleted', models.PositiveIntegerField(default=0)),
                ('fks_repointed', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('detail', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'drug sync run',
                'ordering': ['-started_at'],
            },
        ),
    ]
