# Generated by Django 5.2.16 on 2026-09-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0007_drugsyncrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentexposure',
            name='strength',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='treatmentexposure',
            name='dose',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
