# Generated by Django 6.0.6 on 2026-06-19 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaselineAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_date', models.DateField(blank=True, null=True)),
                ('division_residence', models.CharField(blank=True, max_length=60)),
                ('socioeconomic_status', models.CharField(blank=True, max_length=30)),
                ('monthly_income_bdt', models.PositiveIntegerField(blank=True, null=True)),
                ('education', models.CharField(blank=True, max_length=40)),
                ('occupation', models.CharField(blank=True, max_length=60)),
                ('smoking', models.CharField(blank=True, max_length=20)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('bmi', models.DecimalField(blank=True, decimal_places=1, editable=False, max_digits=4, null=True)),
                ('bmi_category', models.CharField(blank=True, editable=False, max_length=12)),
                ('systolic_bp', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('diastolic_bp', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('dm_duration_years', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('hba1c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('diabetic_retinopathy', models.BooleanField(default=False)),
                ('neuropathy', models.BooleanField(default=False)),
                ('diabetic_foot_history', models.BooleanField(default=False)),
                ('hypertension', models.BooleanField(default=False)),
                ('cvd_history', models.BooleanField(default=False)),
                ('presentation_syndrome', models.CharField(blank=True, choices=[('nephrotic', 'Nephrotic syndrome'), ('nephritic', 'Nephritic syndrome'), ('rpgn', 'Rapidly progressive GN'), ('asymptomatic', 'Asymptomatic urinary abnormality'), ('hematuria', 'Isolated hematuria'), ('proteinuria', 'Isolated proteinuria'), ('ckd', 'Chronic kidney disease'), ('aki', 'Acute kidney injury')], max_length=14)),
                ('oedema_grade', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('active_urinary_sediment', models.BooleanField(default=False)),
                ('rbc_casts', models.BooleanField(default=False)),
                ('family_history_kidney', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='baseline', to='patients.patient')),
            ],
            options={
                'ordering': ['patient'],
            },
        ),
    ]
