# Generated by Django 6.0.6 on 2026-06-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baselineassessment',
            name='education',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Primary', 'Primary'), ('Secondary', 'Secondary'), ('Higher secondary', 'Higher secondary'), ('Graduate', 'Graduate'), ('Postgraduate', 'Postgraduate')], max_length=40),
        ),
        migrations.AlterField(
            model_name='baselineassessment',
            name='smoking',
            field=models.CharField(blank=True, choices=[('Never', 'Never'), ('Current', 'Current'), ('Former', 'Former'), ('Unknown', 'Unknown')], max_length=20),
        ),
        migrations.AlterField(
            model_name='baselineassessment',
            name='socioeconomic_status',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Lower-middle', 'Lower-middle'), ('Middle', 'Middle'), ('Upper-middle', 'Upper-middle'), ('High', 'High')], max_length=30),
        ),
    ]
