# Generated by Django 6.0.6 on 2026-07-02 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseline', '0002_alter_baselineassessment_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baselineassessment',
            name='alcohol_use',
            field=models.CharField(blank=True, choices=[('never', 'Never'), ('former', 'Former'), ('current', 'Current')], max_length=10),
        ),
        migrations.AddField(
            model_name='baselineassessment',
            name='autoimmune_disease',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='baselineassessment',
            name='chronic_infection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='baselineassessment',
            name='drug_history',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='baselineassessment',
            name='fundoscopy',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='baselineassessment',
            name='joint_findings',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='baselineassessment',
            name='malignancy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='baselineassessment',
            name='presentation_syndromes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='baselineassessment',
            name='presenting_symptoms',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='baselineassessment',
            name='previous_kidney_disease',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='baselineassessment',
            name='prior_immunosuppression',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='baselineassessment',
            name='pulse_bpm',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='baselineassessment',
            name='respiratory_rate',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='baselineassessment',
            name='skin_findings',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='baselineassessment',
            name='temperature_c',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='baselineassessment',
            name='volume_status',
            field=models.CharField(blank=True, choices=[('euvolemic', 'Euvolemic'), ('hypervolemic', 'Hypervolemic / overloaded'), ('hypovolemic', 'Hypovolemic / depleted')], max_length=12),
        ),
    ]
