# Generated by Django 5.2.16 on 2026-09-27 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseline', '0003_baselineassessment_alcohol_use_and_more'),
        ('encounters', '0004_clinicalencounter_selected_vital'),
        ('labs', '0002_alter_labresult_options_alter_labresult_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baselineassessment',
            name='baseline_encounter',
            field=models.ForeignKey(blank=True, help_text='Link only when the baseline was captured at this visit.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='encounters.clinicalencounter'),
        ),
        migrations.AddField(
            model_name='baselineassessment',
            name='comorbidity_snapshot_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='baselineassessment',
            name='comorbidity_snapshot_source',
            field=models.CharField(blank=True, editable=False, help_text='enrollment | legacy_mirror | correction', max_length=16),
        ),
        migrations.AddField(
            model_name='baselineassessment',
            name='hba1c_result',
            field=models.ForeignKey(blank=True, editable=False, help_text='The HbA1c observation this baseline reports.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='labs.labresult'),
        ),
        migrations.AlterField(
            model_name='baselineassessment',
            name='hba1c',
            field=models.DecimalField(blank=True, decimal_places=1, editable=False, max_digits=4, null=True),
        ),
    ]
