# Generated by Django 6.0.6 on 2026-06-19 13:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biopsy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biopsy_date', models.DateField()),
                ('adequacy', models.CharField(blank=True, choices=[('adequate', 'Adequate'), ('borderline', 'Borderline'), ('inadequate', 'Inadequate')], max_length=12)),
                ('total_glomeruli', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('global_sclerosis_pct', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('ifta_pct', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('arteriosclerosis', models.CharField(blank=True, choices=[('none', 'None'), ('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], max_length=8)),
                ('arteriolar_hyalinosis', models.BooleanField(default=False)),
                ('dkd_lesion_present', models.BooleanField(default=False)),
                ('crescents_present', models.BooleanField(default=False)),
                ('crescent_pct', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('necrosis_present', models.BooleanField(default=False)),
                ('if_pattern', models.CharField(blank=True, max_length=120)),
                ('em_findings', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biopsies', to='patients.patient')),
            ],
            options={
                'verbose_name_plural': 'biopsies',
                'ordering': ['patient', '-biopsy_date'],
            },
        ),
        migrations.CreateModel(
            name='BiopsyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='biopsy_images/%Y/%m/')),
                ('stain', models.CharField(blank=True, choices=[('he', 'H&E'), ('pas', 'PAS'), ('silver', 'Silver'), ('trichrome', 'Masson trichrome'), ('if', 'Immunofluorescence'), ('em', 'Electron microscopy')], max_length=10)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('biopsy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pathology.biopsy')),
            ],
        ),
        migrations.CreateModel(
            name='FSGSPathology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_secondary', models.CharField(blank=True, choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('unknown', 'Unknown')], max_length=10)),
                ('variant', models.CharField(blank=True, choices=[('nos', 'NOS'), ('perihilar', 'Perihilar'), ('cellular', 'Cellular'), ('tip', 'Tip'), ('collapsing', 'Collapsing')], max_length=10)),
                ('biopsy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fsgs', to='pathology.biopsy')),
            ],
        ),
        migrations.CreateModel(
            name='GNDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.CharField(max_length=120)),
                ('broad_group', models.CharField(blank=True, max_length=80)),
                ('pathogenesis_group', models.CharField(blank=True, max_length=80)),
                ('primary_secondary', models.CharField(blank=True, choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('unknown', 'Unknown')], max_length=10)),
                ('secondary_cause', models.CharField(blank=True, max_length=120)),
                ('biopsy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis', to='pathology.biopsy')),
            ],
        ),
        migrations.CreateModel(
            name='IgANScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('M', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('E', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('S', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('T', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
                ('C', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
                ('biopsy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='igan_score', to='pathology.biopsy')),
            ],
        ),
        migrations.CreateModel(
            name='LupusPathology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isn_rps_class', models.CharField(blank=True, choices=[('I', 'Class I'), ('II', 'Class II'), ('III', 'Class III'), ('IV', 'Class IV'), ('V', 'Class V'), ('VI', 'Class VI')], max_length=4)),
                ('activity_index', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)])),
                ('chronicity_index', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)])),
                ('biopsy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lupus', to='pathology.biopsy')),
            ],
        ),
        migrations.CreateModel(
            name='MembranousPathology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pla2r_tissue', models.CharField(blank=True, choices=[('pos', 'Positive'), ('neg', 'Negative'), ('nd', 'Not done')], max_length=4)),
                ('thsd7a_tissue', models.CharField(blank=True, choices=[('pos', 'Positive'), ('neg', 'Negative'), ('nd', 'Not done')], max_length=4)),
                ('mn_stage', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('biopsy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membranous', to='pathology.biopsy')),
            ],
        ),
    ]
