# Generated by Django 6.0.6 on 2026-06-19 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathology', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='biopsy',
            name='review_status',
            field=models.CharField(choices=[('pending', 'Pending review'), ('awaiting_central', 'Local done, awaiting central'), ('concordant', 'Concordant (local = central)'), ('discordant', 'Discordant — needs adjudication'), ('adjudicated', 'Adjudicated (consensus)')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='PathologyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('local', 'Local pathologist'), ('central', 'Central expert review'), ('adjudication', 'Consensus adjudication')], max_length=12)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('diagnosis', models.CharField(max_length=120)),
                ('broad_group', models.CharField(blank=True, max_length=80)),
                ('mest_m', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('mest_e', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('mest_s', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('mest_t', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('mest_c', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('isn_rps_class', models.CharField(blank=True, max_length=4)),
                ('fsgs_variant', models.CharField(blank=True, max_length=10)),
                ('is_final', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('biopsy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='pathology.biopsy')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pathology_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['biopsy', 'role'],
                'constraints': [models.UniqueConstraint(fields=('biopsy', 'role'), name='uniq_biopsy_review_role')],
            },
        ),
    ]
