# Generated by Django 6.0.6 on 2026-06-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathology', '0003_alter_gndiagnosis_broad_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathologyreview',
            name='fsgs_variant',
            field=models.CharField(blank=True, choices=[('nos', 'NOS'), ('perihilar', 'Perihilar'), ('cellular', 'Cellular'), ('tip', 'Tip'), ('collapsing', 'Collapsing')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pathologyreview',
            name='isn_rps_class',
            field=models.CharField(blank=True, choices=[('I', 'Class I'), ('II', 'Class II'), ('III', 'Class III'), ('IV', 'Class IV'), ('V', 'Class V'), ('VI', 'Class VI')], max_length=4),
        ),
    ]
