# Generated by Django 6.0.6 on 2026-07-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathology', '0005_biopsy_indication_biopsy_result_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biopsy',
            name='if_pattern',
            field=models.CharField(blank=True, choices=[('', '—'), ('mesangial_iga', 'Mesangial IgA'), ('full_house', 'Full-house (IgG/IgA/IgM/C3/C1q)'), ('granular_capillary_subendothelial', 'Granular capillary wall — subendothelial'), ('granular_capillary_subepithelial', 'Granular capillary wall — subepithelial'), ('linear_igg', 'Linear IgG (anti-GBM pattern)'), ('pauci_immune', 'Pauci-immune / no immune deposits'), ('mesangial_c3', 'Mesangial C3'), ('mesangial_igg', 'Mesangial IgG'), ('c3_dominant', 'C3 dominant (starry sky)'), ('granular_mesangial_capillary', 'Granular mesangial + capillary wall'), ('other', 'Other (specify in notes)')], help_text='Immunofluorescence pattern on biopsy', max_length=120),
        ),
    ]
