# Generated by Django 6.0.6 on 2026-07-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathology', '0006_if_pattern_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biopsy',
            name='em_findings',
            field=models.TextField(blank=True, choices=[('', '—'), ('normal', 'Normal ultrastructure'), ('mesangial_expansion', 'Mesangial matrix expansion'), ('subendothelial_deposits', 'Subendothelial electron-dense deposits'), ('subepithelial_deposits', 'Subepithelial electron-dense deposits'), ('mesangial_deposits', 'Mesangial electron-dense deposits'), ('intramembranous_deposits', 'Intramembranous deposits'), ('foot_process_effacement', 'Foot process effacement'), ('basement_membrane_thinning', 'GBM thinning'), ('basement_membrane_irregularity', 'GBM irregularity/double contours'), ('electron_dense_cryoglobulin', 'Electron-dense cryoglobulin-like deposits'), ('fibrillary_deposits', 'Fibrillary/tubulointerstitial deposits'), ('other', 'Other (specify in notes)')], help_text='Electron microscopy findings'),
        ),
    ]
