# Generated by Django 6.0.6 on 2026-07-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathology', '0007_em_findings_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lupuspathology',
            name='isn_rps_class',
            field=models.CharField(blank=True, choices=[('I', 'Class I'), ('II', 'Class II'), ('III', 'Class III'), ('IV', 'Class IV'), ('V', 'Class V'), ('VI', 'Class VI'), ('III+V', 'Class III+V'), ('IV+V', 'Class IV+V')], max_length=6),
        ),
        migrations.AlterField(
            model_name='pathologyreview',
            name='isn_rps_class',
            field=models.CharField(blank=True, choices=[('I', 'Class I'), ('II', 'Class II'), ('III', 'Class III'), ('IV', 'Class IV'), ('V', 'Class V'), ('VI', 'Class VI'), ('III+V', 'Class III+V'), ('IV+V', 'Class IV+V')], max_length=6),
        ),
    ]
