# Generated by Django 5.2.16 on 2026-09-27 14:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathology', '0008_alter_lupuspathology_isn_rps_class_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='biopsy',
            name='arteriolar_hyalinosis',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='biopsy',
            name='crescent_pct',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='biopsy',
            name='crescents_present',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='biopsy',
            name='dkd_lesion_present',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='biopsy',
            name='global_sclerosis_pct',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='biopsy',
            name='ifta_pct',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='biopsy',
            name='necrosis_present',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='biopsy',
            name='total_glomeruli',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Glomeruli (light microscopy)'),
        ),
        migrations.CreateModel(
            name='PathologyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('local', 'Local pathologist'), ('central', 'Central expert review'), ('adjudication', 'Consensus adjudication')], default='local', max_length=12)),
                ('revision', models.PositiveSmallIntegerField(default=1)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('origin', models.CharField(choices=[('guided', 'Guided entry'), ('amendment', 'Amendment'), ('addendum', 'Addendum'), ('api', 'API'), ('admin', 'Admin'), ('legacy', 'Converted from legacy biopsy fields')], default='guided', max_length=10)),
                ('revision_reason', models.CharField(blank=True, help_text='Required for an amendment or addendum.', max_length=240)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending further studies'), ('preliminary', 'Preliminary'), ('final', 'Final'), ('inadequate', 'Inadequate / non-diagnostic')], default='final', max_length=12)),
                ('report_identifier', models.CharField(blank=True, max_length=60)),
                ('laboratory', models.CharField(blank=True, max_length=120)),
                ('pathologist', models.CharField(blank=True, max_length=120)),
                ('specimen_date', models.DateField(blank=True, null=True)),
                ('report_date', models.DateField(blank=True, null=True)),
                ('context', models.CharField(blank=True, choices=[('native', 'Native kidney'), ('transplant', 'Transplant kidney')], max_length=10)),
                ('signed_by', models.CharField(blank=True, max_length=120)),
                ('signed_at', models.DateField(blank=True, null=True)),
                ('cortex_present', models.BooleanField(blank=True, null=True)),
                ('medulla_present', models.BooleanField(blank=True, null=True)),
                ('cores', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('glomeruli_if', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Glomeruli (IF)')),
                ('glomeruli_em', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Glomeruli (EM)')),
                ('globally_sclerosed', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Globally sclerosed glomeruli (LM)')),
                ('segmentally_sclerosed', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Segmentally sclerosed glomeruli (LM)')),
                ('crescentic_glomeruli', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Glomeruli with crescents (LM)')),
                ('limitations', models.TextField(blank=True)),
                ('lm_status', models.CharField(blank=True, choices=[('performed', 'Performed'), ('pending', 'Pending'), ('not_done', 'Not done'), ('unavailable', 'Unavailable'), ('inadequate', 'Inadequate sample')], max_length=12, verbose_name='Light microscopy')),
                ('if_status', models.CharField(blank=True, choices=[('performed', 'Performed'), ('pending', 'Pending'), ('not_done', 'Not done'), ('unavailable', 'Unavailable'), ('inadequate', 'Inadequate sample')], max_length=12, verbose_name='Immunofluorescence')),
                ('ihc_status', models.CharField(blank=True, choices=[('performed', 'Performed'), ('pending', 'Pending'), ('not_done', 'Not done'), ('unavailable', 'Unavailable'), ('inadequate', 'Inadequate sample')], max_length=12, verbose_name='Special stains / IHC')),
                ('em_status', models.CharField(blank=True, choices=[('performed', 'Performed'), ('pending', 'Pending'), ('not_done', 'Not done'), ('unavailable', 'Unavailable'), ('inadequate', 'Inadequate sample')], max_length=12, verbose_name='Electron microscopy')),
                ('primary_diagnosis', models.CharField(blank=True, choices=[('IgA nephropathy', 'IgA nephropathy'), ('IgA vasculitis nephritis', 'IgA vasculitis nephritis'), ('Membranous nephropathy - PLA2R positive', 'Membranous nephropathy - PLA2R positive'), ('Membranous nephropathy - PLA2R negative', 'Membranous nephropathy - PLA2R negative'), ('Membranous nephropathy - secondary/associated', 'Membranous nephropathy - secondary/associated'), ('Minimal change disease', 'Minimal change disease'), ('FSGS - primary', 'FSGS - primary'), ('FSGS - secondary/adaptive', 'FSGS - secondary/adaptive'), ('FSGS - genetic/suspected genetic', 'FSGS - genetic/suspected genetic'), ('FSGS - collapsing variant', 'FSGS - collapsing variant'), ('FSGS - tip lesion variant', 'FSGS - tip lesion variant'), ('FSGS - cellular variant', 'FSGS - cellular variant'), ('FSGS - perihilar variant', 'FSGS - perihilar variant'), ('FSGS - NOS', 'FSGS - NOS'), ('Lupus nephritis class I', 'Lupus nephritis class I'), ('Lupus nephritis class II', 'Lupus nephritis class II'), ('Lupus nephritis class III', 'Lupus nephritis class III'), ('Lupus nephritis class IV', 'Lupus nephritis class IV'), ('Lupus nephritis class V', 'Lupus nephritis class V'), ('Lupus nephritis class III+V', 'Lupus nephritis class III+V'), ('Lupus nephritis class IV+V', 'Lupus nephritis class IV+V'), ('ANCA-associated pauci-immune crescentic GN - MPO', 'ANCA-associated pauci-immune crescentic GN - MPO'), ('ANCA-associated pauci-immune crescentic GN - PR3', 'ANCA-associated pauci-immune crescentic GN - PR3'), ('ANCA-associated pauci-immune crescentic GN - ANCA negative', 'ANCA-associated pauci-immune crescentic GN - ANCA negative'), ('Anti-GBM disease', 'Anti-GBM disease'), ('C3 glomerulopathy - C3 glomerulonephritis', 'C3 glomerulopathy - C3 glomerulonephritis'), ('C3 glomerulopathy - dense deposit disease', 'C3 glomerulopathy - dense deposit disease'), ('Immune-complex MPGN', 'Immune-complex MPGN'), ('Infection-related GN - post-streptococcal', 'Infection-related GN - post-streptococcal'), ('Infection-related GN - staphylococcal/IgA-dominant', 'Infection-related GN - staphylococcal/IgA-dominant'), ('Infection-related GN - endocarditis-associated', 'Infection-related GN - endocarditis-associated'), ('Infection-related GN - hepatitis B associated', 'Infection-related GN - hepatitis B associated'), ('Infection-related GN - hepatitis C associated', 'Infection-related GN - hepatitis C associated'), ('Cryoglobulinaemic GN', 'Cryoglobulinaemic GN'), ('Monoclonal immunoglobulin deposition disease', 'Monoclonal immunoglobulin deposition disease'), ('Proliferative GN with monoclonal Ig deposits - PGNMID', 'Proliferative GN with monoclonal Ig deposits - PGNMID'), ('Amyloidosis - renal', 'Amyloidosis - renal'), ('Fibrillary GN', 'Fibrillary GN'), ('Immunotactoid GN', 'Immunotactoid GN'), ('C1q nephropathy', 'C1q nephropathy'), ('Thin basement membrane nephropathy', 'Thin basement membrane nephropathy'), ('Alport syndrome / hereditary nephritis', 'Alport syndrome / hereditary nephritis'), ('Thrombotic microangiopathy with glomerular injury', 'Thrombotic microangiopathy with glomerular injury'), ('Diabetic kidney disease only - no GN', 'Diabetic kidney disease only - no GN'), ('Diabetic kidney disease + IgA nephropathy', 'Diabetic kidney disease + IgA nephropathy'), ('Diabetic kidney disease + membranous nephropathy', 'Diabetic kidney disease + membranous nephropathy'), ('Diabetic kidney disease + FSGS', 'Diabetic kidney disease + FSGS'), ('Diabetic kidney disease + lupus nephritis', 'Diabetic kidney disease + lupus nephritis'), ('Diabetic kidney disease + ANCA GN', 'Diabetic kidney disease + ANCA GN'), ('Diabetic kidney disease + infection-related GN', 'Diabetic kidney disease + infection-related GN'), ('Diabetic kidney disease + other GN', 'Diabetic kidney disease + other GN'), ('Hypertensive nephrosclerosis only - no GN', 'Hypertensive nephrosclerosis only - no GN'), ('Tubulointerstitial nephritis predominant', 'Tubulointerstitial nephritis predominant'), ('Other specified GN', 'Other specified GN'), ('Unclassified GN', 'Unclassified GN'), ('Inadequate biopsy / non-diagnostic', 'Inadequate biopsy / non-diagnostic')], max_length=120)),
                ('additional_diagnoses', models.JSONField(blank=True, default=list, help_text='Coexisting diagnoses (e.g. DKD + GN), as diagnosis labels.')),
                ('comment', models.TextField(blank=True)),
                ('original_report_text', models.TextField(blank=True)),
                ('scores', models.JSONField(blank=True, default=dict)),
                ('panel_override_reason', models.CharField(blank=True, help_text='Why a score panel outside the diagnosis family applies (mixed / coexisting lesion).', max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('biopsy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='pathology.biopsy')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pathology_reports', to=settings.AUTH_USER_MODEL)),
                ('supersedes', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='pathology.pathologyreport')),
            ],
            options={
                'ordering': ['biopsy', 'role', '-revision'],
            },
        ),
        migrations.CreateModel(
            name='PathologyFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('lm_glomerular', 'Light microscopy — glomeruli'), ('tubulointerstitial', 'Tubulointerstitium'), ('vascular', 'Vessels'), ('if_marker', 'Immunofluorescence / IHC — marker result'), ('if_interpretation', 'Immunofluorescence — interpreted pattern'), ('em', 'Electron microscopy'), ('special_stain', 'Special stains / IHC')], max_length=20)),
                ('code', models.CharField(choices=[('acute_tubular_injury', 'Acute tubular injury'), ('arteriolar_hyalinosis', 'Arteriolar hyalinosis'), ('arteriosclerosis', 'Arteriosclerosis (intimal fibrosis)'), ('c3_dominant', 'C3 dominant'), ('c4d', 'C4d'), ('capillary_wall_thickening', 'Capillary wall thickening'), ('congo_red', 'Congo red'), ('crescent_cellular', 'Crescents — cellular'), ('crescent_fibrocellular', 'Crescents — fibrocellular'), ('crescent_fibrous', 'Crescents — fibrous'), ('cryoglobulin_like', 'Cryoglobulin-like deposits'), ('deposits_intramembranous', 'Deposits — intramembranous'), ('deposits_mesangial', 'Deposits — mesangial'), ('deposits_subendothelial', 'Deposits — subendothelial'), ('deposits_subepithelial', 'Deposits — subepithelial'), ('dnajb9', 'DNAJB9'), ('double_contours', 'Double contours'), ('endocapillary_hypercellularity', 'Endocapillary hypercellularity'), ('foot_process_effacement', 'Foot-process effacement'), ('full_house', 'Full-house (IgG/IgA/IgM/C3/C1q)'), ('gbm_irregularity', 'GBM irregularity / lamellation / double contours'), ('gbm_spikes', 'GBM spikes'), ('gbm_thickening', 'GBM thickening'), ('gbm_thinning', 'GBM thinning'), ('global_sclerosis', 'Global sclerosis'), ('glomerular_thrombi', 'Glomerular thrombi'), ('granular_capillary_subendothelial', 'Granular capillary wall — subendothelial'), ('granular_capillary_subepithelial', 'Granular capillary wall — subepithelial'), ('granular_mesangial_capillary', 'Granular mesangial + capillary wall'), ('ifta', 'IFTA (reported together)'), ('interstitial_fibrosis', 'Interstitial fibrosis'), ('interstitial_inflammation', 'Interstitial inflammation'), ('linear_igg', 'Linear IgG (anti-GBM pattern)'), ('marker', 'Marker result'), ('mesangial_c3', 'Mesangial C3'), ('mesangial_hypercellularity', 'Mesangial hypercellularity'), ('mesangial_iga', 'Mesangial IgA-dominant'), ('mesangial_igg', 'Mesangial IgG'), ('mesangial_matrix_expansion', 'Mesangial matrix expansion'), ('necrosis', 'Fibrinoid necrosis'), ('nodular_sclerosis', 'Nodular (Kimmelstiel-Wilson) lesions'), ('normal_ultrastructure', 'Normal ultrastructure'), ('organized_fibrillary', 'Organized deposits — fibrillary'), ('organized_microtubular', 'Organized deposits — microtubular'), ('other', 'Other (describe)'), ('other', 'Other stain (describe)'), ('pauci_immune', 'Pauci-immune / no immune deposits'), ('pla2r_tissue', 'PLA2R (tissue)'), ('protein_casts', 'Proteinaceous / hyaline casts'), ('rbc_casts', 'Red-cell casts'), ('segmental_sclerosis', 'Segmental sclerosis'), ('sv40', 'SV40 (polyoma)'), ('thsd7a_tissue', 'THSD7A (tissue)'), ('tma_mucoid_intimal', 'TMA — mucoid intimal oedema'), ('tma_other', 'TMA — other feature'), ('tma_thrombi', 'TMA — arteriolar/glomerular thrombi'), ('tubular_atrophy', 'Tubular atrophy'), ('tubulitis', 'Tubulitis'), ('tubuloreticular_inclusions', 'Tubuloreticular inclusions'), ('vasculitis', 'Vascular inflammation / vasculitis')], max_length=40)),
                ('other_label', models.CharField(blank=True, help_text="What the finding is, when 'Other'.", max_length=120)),
                ('presence', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('indeterminate', 'Indeterminate')], default='present', max_length=14)),
                ('severity', models.CharField(blank=True, choices=[('minimal', 'Minimal'), ('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], max_length=10)),
                ('extent', models.CharField(blank=True, choices=[('focal', 'Focal'), ('diffuse', 'Diffuse'), ('segmental', 'Segmental'), ('global', 'Global')], max_length=10)),
                ('extent_pct', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Extent (%)')),
                ('count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('denominator', models.PositiveSmallIntegerField(blank=True, help_text='Out of how many (e.g. glomeruli examined).', null=True)),
                ('site', models.CharField(blank=True, choices=[('mesangial', 'Mesangial'), ('capillary_wall', 'Capillary wall'), ('subendothelial', 'Subendothelial'), ('subepithelial', 'Subepithelial'), ('intramembranous', 'Intramembranous'), ('tubular_bm', 'Tubular basement membrane'), ('interstitium', 'Interstitium'), ('vessels', 'Vessels'), ('bowman', 'Bowman capsule')], max_length=16)),
                ('marker', models.CharField(blank=True, choices=[('IgG', 'IgG'), ('IgA', 'IgA'), ('IgM', 'IgM'), ('C3', 'C3'), ('C1q', 'C1q'), ('kappa', 'Kappa'), ('lambda', 'Lambda'), ('fibrinogen', 'Fibrin/fibrinogen'), ('C4d', 'C4d'), ('IgG_subclass', 'IgG subclass'), ('other', 'Other marker')], max_length=16)),
                ('intensity', models.CharField(blank=True, choices=[('0', 'Negative'), ('trace', 'Trace'), ('1+', '1+'), ('2+', '2+'), ('3+', '3+')], max_length=6)),
                ('distribution', models.CharField(blank=True, choices=[('granular', 'Granular'), ('linear', 'Linear'), ('pseudolinear', 'Pseudolinear'), ('smudgy', 'Smudgy')], max_length=14)),
                ('detail', models.CharField(blank=True, max_length=240)),
                ('origin', models.CharField(choices=[('entered', 'Entered'), ('legacy', 'Converted from a legacy biopsy field')], default='entered', max_length=8)),
                ('legacy_value', models.CharField(blank=True, max_length=120)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='pathology.pathologyreport')),
            ],
            options={
                'ordering': ['report', 'section', 'sort_order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='pathologyreport',
            constraint=models.UniqueConstraint(fields=('biopsy', 'role', 'revision'), name='uniq_report_revision'),
        ),
    ]
