# Generated by Django 5.2.16 on 2026-09-28 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathology', '0009_alter_biopsy_arteriolar_hyalinosis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathologyfinding',
            name='code',
            field=models.CharField(choices=[('acute_tubular_injury', 'Acute tubular injury'), ('arteriolar_hyalinosis', 'Arteriolar hyalinosis'), ('arteriosclerosis', 'Arteriosclerosis (intimal fibrosis)'), ('c3_dominant', 'C3 dominant'), ('c4d', 'C4d'), ('capillary_wall_thickening', 'Capillary wall thickening'), ('congo_red', 'Congo red'), ('crescent_cellular', 'Crescents — cellular'), ('crescent_fibrocellular', 'Crescents — fibrocellular'), ('crescent_fibrous', 'Crescents — fibrous'), ('cryoglobulin_like', 'Cryoglobulin-like deposits'), ('deposits_intramembranous', 'Deposits — intramembranous'), ('deposits_mesangial', 'Deposits — mesangial'), ('deposits_subendothelial', 'Deposits — subendothelial'), ('deposits_subepithelial', 'Deposits — subepithelial'), ('dnajb9', 'DNAJB9'), ('double_contours', 'Double contours'), ('endocapillary_hypercellularity', 'Endocapillary hypercellularity'), ('foot_process_effacement', 'Foot-process effacement'), ('full_house', 'Full-house (IgG/IgA/IgM/C3/C1q)'), ('gbm_irregularity', 'GBM irregularity / lamellation / double contours'), ('gbm_spikes', 'GBM spikes'), ('gbm_thickening', 'GBM thickening'), ('gbm_thinning', 'GBM thinning'), ('global_sclerosis', 'Global sclerosis'), ('glomerular_thrombi', 'Glomerular thrombi'), ('granular_capillary_subendothelial', 'Granular capillary wall — subendothelial'), ('granular_capillary_subepithelial', 'Granular capillary wall — subepithelial'), ('granular_mesangial_capillary', 'Granular mesangial + capillary wall'), ('ifta', 'IFTA (reported together)'), ('interstitial_fibrosis', 'Interstitial fibrosis'), ('interstitial_inflammation', 'Interstitial inflammation'), ('linear_igg', 'Linear IgG (anti-GBM pattern)'), ('marker', 'Marker result'), ('mesangial_c3', 'Mesangial C3'), ('mesangial_hypercellularity', 'Mesangial hypercellularity'), ('mesangial_iga', 'Mesangial IgA-dominant'), ('mesangial_igg', 'Mesangial IgG'), ('mesangial_matrix_expansion', 'Mesangial matrix expansion'), ('necrosis', 'Fibrinoid necrosis'), ('nodular_sclerosis', 'Nodular (Kimmelstiel-Wilson) lesions'), ('normal_ultrastructure', 'Normal ultrastructure'), ('organized_fibrillary', 'Organized deposits — fibrillary'), ('organized_microtubular', 'Organized deposits — microtubular'), ('other', 'Other (describe)'), ('pauci_immune', 'Pauci-immune / no immune deposits'), ('pla2r_tissue', 'PLA2R (tissue)'), ('protein_casts', 'Proteinaceous / hyaline casts'), ('rbc_casts', 'Red-cell casts'), ('segmental_sclerosis', 'Segmental sclerosis'), ('sv40', 'SV40 (polyoma)'), ('thsd7a_tissue', 'THSD7A (tissue)'), ('tma_mucoid_intimal', 'TMA — mucoid intimal oedema'), ('tma_other', 'TMA — other feature'), ('tma_thrombi', 'TMA — arteriolar/glomerular thrombi'), ('tubular_atrophy', 'Tubular atrophy'), ('tubulitis', 'Tubulitis'), ('tubuloreticular_inclusions', 'Tubuloreticular inclusions'), ('vasculitis', 'Vascular inflammation / vasculitis')], max_length=40),
        ),
    ]
