# Generated by Django 6.0.6 on 2026-06-19 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('encounters', '0001_initial'),
        ('treatments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft (editable)'), ('final', 'Finalized (printed, immutable)')], default='draft', max_length=8)),
                ('diagnosis_text', models.CharField(blank=True, max_length=240)),
                ('investigations_advised', models.TextField(blank=True, help_text='Labs/tests ordered at this visit (free text).')),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
                ('pdf_file', models.FileField(blank=True, upload_to='prescriptions/%Y/%m/')),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='encounters.clinicalencounter')),
                ('printed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='printed_prescriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=120)),
                ('strength', models.CharField(blank=True, max_length=40)),
                ('dose', models.CharField(blank=True, help_text='e.g. "10 mg"', max_length=40)),
                ('dose_unit', models.CharField(blank=True, max_length=20)),
                ('frequency', models.CharField(blank=True, help_text='e.g. "1+0+1"', max_length=40)),
                ('timing', models.CharField(choices=[('before', 'Before meal'), ('after', 'After meal'), ('empty', 'Empty stomach'), ('any', 'Any time')], default='after', max_length=8)),
                ('duration', models.CharField(blank=True, help_text='e.g. "continue"', max_length=40)),
                ('instruction_bn', models.CharField(blank=True, max_length=240)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='treatments.drugmaster')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='prescriptions.prescription')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='prescription',
            constraint=models.UniqueConstraint(fields=('encounter', 'version'), name='uniq_encounter_version'),
        ),
    ]
