# Generated by Django 6.0.6 on 2026-06-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='advice',
            field=models.TextField(blank=True, help_text='General advice / OTC or temporary drug advice (e.g. paracetamol for fever) — prints on the slip.'),
        ),
    ]
