# Generated by Django 6.0.6 on 2026-07-02 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0002_prescription_advice'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionitem',
            name='route',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
