# Generated by Django 6.0.6 on 2026-07-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0003_prescriptionitem_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdviceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Heading shown in the dropdown.', max_length=100, unique=True)),
                ('body', models.TextField(help_text='The advice text pasted into the field.')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='prescription',
            name='stop_notes',
            field=models.TextField(blank=True, help_text='Justifications for drugs removed at this visit (drug — reason), captured when a medication is stopped.'),
        ),
    ]
