# Generated by Django 6.0.6 on 2026-07-03 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0004_advicetemplate_prescription_stop_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='comorbidities',
            field=models.CharField(blank=True, help_text='Relevant comorbidities (e.g. Hypertension, Diabetes) — prints on the slip; pre-filled from baseline.', max_length=240),
        ),
    ]
