# Generated by Django 5.2.16 on 2026-09-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0005_prescription_comorbidities'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionitem',
            name='taper_notes',
            field=models.TextField(blank=True, help_text="How to step this drug down before stopping — e.g. '40 mg 1 wk → 20 mg 1 wk → 10 mg 1 wk → stop'. Prints under the drug line. Required for a systemic steroid course."),
        ),
    ]
