# Generated by Django 5.2.16 on 2026-09-27 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0006_prescriptionitem_taper_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionitem',
            name='dose',
            field=models.CharField(blank=True, help_text='e.g. "10 mg"', max_length=120),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='strength',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
