# Generated by Django 5.2.16 on 2026-09-27 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0002_alter_labresult_options_alter_labresult_managers_and_more'),
        ('prescriptions', '0007_widen_prescription_item_strength_and_dose'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='content_hash_version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='prescription',
            name='issued_snapshot',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='prescription',
            name='snapshot_version',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='comorbidities',
            field=models.CharField(blank=True, help_text='Comorbidities printed on the slip — chosen from the patient record, plus prescription-only notes.', max_length=240),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='investigations_advised',
            field=models.TextField(blank=True, help_text='Investigations not in the lab catalogue (free text).'),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='dose',
            field=models.CharField(blank=True, help_text='e.g. "2" or "10 mg"', max_length=120),
        ),
        migrations.CreateModel(
            name='PrescriptionTestRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescription_requests', to='labs.laborderitem')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_requests', to='prescriptions.prescription')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='labs.labtest')),
            ],
            options={
                'ordering': ['prescription', 'test__name'],
                'constraints': [models.UniqueConstraint(fields=('prescription', 'test'), name='uniq_rx_test_request')],
            },
        ),
    ]
