# Generated by Django 5.2.16 on 2026-09-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0008_prescription_content_hash_version_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaperTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Heading shown in the taper dropdown.', max_length=100, unique=True)),
                ('body', models.TextField(help_text='The step-down text inserted into the taper plan.')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
    ]
