# Generated by Django 6.0.6 on 2026-06-19 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_label', models.CharField(max_length=100)),
                ('object_pk', models.CharField(max_length=64)),
                ('object_repr', models.CharField(blank=True, max_length=200)),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted')], max_length=8)),
                ('field_name', models.CharField(blank=True, max_length=80)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('change_reason', models.CharField(blank=True, max_length=240)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-changed_at', 'id'],
                'indexes': [models.Index(fields=['model_label', 'object_pk'], name='audit_audit_model_l_87196a_idx'), models.Index(fields=['changed_at'], name='audit_audit_changed_e23920_idx')],
            },
        ),
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_type', models.CharField(choices=[('registry', 'Registry participation'), ('biobank', 'Biobank / sample storage'), ('genetic', 'Genetic testing'), ('imaging', 'Digital pathology / imaging'), ('trial', 'Registry-embedded trial')], max_length=12)),
                ('form_version', models.CharField(help_text='ICF version, e.g. "BGDDR-ICF-v2.1"', max_length=40)),
                ('status', models.CharField(choices=[('granted', 'Granted'), ('withdrawn', 'Withdrawn'), ('refused', 'Refused')], default='granted', max_length=10)),
                ('consent_date', models.DateField()),
                ('withdrawn_date', models.DateField(blank=True, null=True)),
                ('scope', models.TextField(blank=True, help_text='What the patient agreed to.')),
                ('document', models.FileField(blank=True, upload_to='consents/%Y/%m/')),
                ('notes', models.CharField(blank=True, max_length=240)),
                ('is_current', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('obtained_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consents_obtained', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='patients.patient')),
                ('supersedes', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='audit.consent')),
            ],
            options={
                'ordering': ['patient', 'consent_type', '-consent_date'],
                'indexes': [models.Index(fields=['patient', 'consent_type', 'is_current'], name='audit_conse_patient_7c0388_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('patient', 'consent_type'), name='uniq_current_consent_per_type')],
            },
        ),
    ]
