# Generated by Django 6.0.6 on 2026-07-10 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('encounters', '0003_clinicalencounter_clinician_response_and_more'),
        ('patients', '0005_site_patient_site_usersiterole'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUpTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('visit_due', 'Visit Due'), ('lab_due', 'Laboratory Due'), ('drug_monitoring_due', 'Drug Monitoring Due'), ('vaccination_due', 'Vaccination Due'), ('biopsy_review_due', 'Biopsy Review Due'), ('safety_review_due', 'Safety Review Due'), ('research_visit_due', 'Research Visit Due')], max_length=25)),
                ('priority', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('emergent', 'Emergent')], default='routine', max_length=10)),
                ('reason', models.TextField(blank=True)),
                ('clinical_reason', models.TextField(blank=True, help_text='Why this task is needed')),
                ('due_date', models.DateField()),
                ('overdue_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('overdue', 'Overdue')], default='pending', max_length=10)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('escalation_level', models.IntegerField(choices=[(0, 'None'), (1, 'Warning generated'), (2, 'Responsible clinician notified'), (3, 'Coordinator notified'), (4, 'Department dashboard escalated')], default=0)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('protocol_label', models.CharField(blank=True, help_text='e.g. IgAN Month 3, MCD Week 1 safety', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followup_tasks', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_followup_tasks', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followup_tasks', to='patients.patient')),
                ('related_encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='encounters.clinicalencounter')),
            ],
            options={
                'ordering': ['due_date', 'priority'],
                'indexes': [models.Index(fields=['patient', 'status', 'due_date'], name='followup_fo_patient_666658_idx'), models.Index(fields=['status', 'due_date'], name='followup_fo_status_b7f31a_idx'), models.Index(fields=['assigned_to', 'status'], name='followup_fo_assigne_897188_idx')],
            },
        ),
    ]
