# Generated by Django 6.0.6 on 2026-06-19 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('title', models.CharField(max_length=240)),
                ('study_type', models.CharField(choices=[('observational', 'Observational cohort'), ('quasi_experimental', 'Quasi-experimental'), ('rct', 'Randomized controlled trial')], max_length=20)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('recruiting', 'Recruiting'), ('active', 'Active (closed to recruitment)'), ('closed', 'Closed')], default='planning', max_length=12)),
                ('target_enrollment', models.PositiveIntegerField(blank=True, null=True)),
                ('primary_endpoint', models.CharField(blank=True, max_length=60)),
                ('randomization_scheme', models.CharField(choices=[('none', 'No randomization'), ('simple', 'Simple'), ('block', 'Permuted block'), ('stratified_block', 'Stratified permuted block')], default='none', max_length=20)),
                ('block_multipliers', models.JSONField(blank=True, default=list, help_text='Block-size multipliers of the ratio unit, e.g. [1, 2].')),
                ('stratify_by', models.JSONField(blank=True, default=list, help_text='Stratification factors, e.g. ["diabetes", "egfr_stratum"].')),
                ('random_seed', models.BigIntegerField(default=20260101, help_text='Fixes the allocation sequence (auditable).')),
                ('requires_trial_consent', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'studies',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='StudyArm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40)),
                ('name', models.CharField(max_length=120)),
                ('ratio', models.PositiveSmallIntegerField(default=1, help_text='Allocation weight (1:1 -> all arms ratio 1).')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_control', models.BooleanField(default=False)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arms', to='studies.study')),
            ],
            options={
                'ordering': ['study', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StudyEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('screened', 'Screened'), ('ineligible', 'Ineligible'), ('enrolled', 'Enrolled'), ('withdrawn', 'Withdrawn'), ('completed', 'Completed')], default='screened', max_length=12)),
                ('screened_date', models.DateField(blank=True, null=True)),
                ('eligible', models.BooleanField(default=False)),
                ('ineligibility_reasons', models.JSONField(blank=True, default=list)),
                ('enrolled_date', models.DateField(blank=True, null=True)),
                ('stratum', models.CharField(blank=True, max_length=120)),
                ('sequence_position', models.IntegerField(blank=True, null=True)),
                ('randomized_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('arm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='studies.studyarm')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='patients.patient')),
                ('randomized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='randomizations', to=settings.AUTH_USER_MODEL)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='studies.study')),
            ],
            options={
                'ordering': ['study', 'patient'],
            },
        ),
        migrations.AddConstraint(
            model_name='studyarm',
            constraint=models.UniqueConstraint(fields=('study', 'code'), name='uniq_study_arm_code'),
        ),
        migrations.AddConstraint(
            model_name='studyenrollment',
            constraint=models.UniqueConstraint(fields=('study', 'patient'), name='uniq_study_patient'),
        ),
    ]
