# Generated by Django 6.0.6 on 2026-07-08 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('encounters', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_snapshot', models.JSONField(help_text='Patient data at time of request')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_requests', to='encounters.clinicalencounter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_requests', to='patients.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DecisionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phenotype', models.CharField(blank=True, max_length=200)),
                ('urgency_level', models.CharField(blank=True, max_length=100)),
                ('urgency_tone', models.CharField(blank=True, max_length=20)),
                ('urgency_reasons', models.JSONField(blank=True, default=list)),
                ('ranked_differential', models.JSONField(blank=True, default=list)),
                ('next_steps', models.JSONField(blank=True, default=dict)),
                ('traceability', models.JSONField(blank=True, default=list, help_text='KB entries and rules applied')),
                ('explanation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='decision.decisionrequest')),
            ],
        ),
    ]
