# Generated by Django 6.0.6 on 2026-07-09 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='decisionresult',
            name='alternative_diagnosis',
            field=models.CharField(blank=True, help_text="Clinician's alternative diagnosis", max_length=200),
        ),
        migrations.AddField(
            model_name='decisionresult',
            name='clinician_notes',
            field=models.TextField(blank=True, help_text='Free-text notes from the clinician'),
        ),
        migrations.AddField(
            model_name='decisionresult',
            name='overridden_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overridden_decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='decisionresult',
            name='override_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='decisionresult',
            name='override_reason',
            field=models.TextField(blank=True, help_text='Reason for overriding the AI recommendation'),
        ),
        migrations.AddIndex(
            model_name='decisionresult',
            index=models.Index(fields=['created_at'], name='decision_de_created_135160_idx'),
        ),
    ]
