# Generated by Django 6.0.6 on 2026-06-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=32, unique=True)),
                ('hospital_id', models.CharField(blank=True, max_length=64)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('dob', models.DateField(blank=True, null=True)),
                ('enrollment_date', models.DateField(blank=True, null=True)),
                ('cohort', models.CharField(blank=True, max_length=32)),
                ('diabetes_status', models.CharField(choices=[('none', 'No diabetes'), ('t1', 'Type 1'), ('t2', 'Type 2'), ('other', 'Other / secondary')], default='none', max_length=8)),
                ('primary_diagnosis', models.CharField(blank=True, max_length=120)),
                ('latest_egfr', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['patient_id'],
            },
        ),
    ]
