# Generated by Django 6.0.6 on 2026-06-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='cohort',
            field=models.CharField(blank=True, choices=[('GN only', 'GN only'), ('Diabetes + GN', 'Diabetes + GN'), ('Diabetes + DKD + GN', 'Diabetes + DKD + GN'), ('Diabetes + DKD only', 'Diabetes + DKD only'), ('Non-diagnostic', 'Non-diagnostic'), ('Suspected GN no biopsy', 'Suspected GN no biopsy')], max_length=32),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(blank=True, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='primary_diagnosis',
            field=models.CharField(blank=True, choices=[('IgA nephropathy', 'IgA nephropathy'), ('IgA vasculitis nephritis', 'IgA vasculitis nephritis'), ('Membranous nephropathy - PLA2R positive', 'Membranous nephropathy - PLA2R positive'), ('Membranous nephropathy - PLA2R negative', 'Membranous nephropathy - PLA2R negative'), ('Membranous nephropathy - secondary/associated', 'Membranous nephropathy - secondary/associated'), ('Minimal change disease', 'Minimal change disease'), ('FSGS - primary', 'FSGS - primary'), ('FSGS - secondary/adaptive', 'FSGS - secondary/adaptive'), ('FSGS - genetic/suspected genetic', 'FSGS - genetic/suspected genetic'), ('FSGS - collapsing variant', 'FSGS - collapsing variant'), ('FSGS - tip lesion variant', 'FSGS - tip lesion variant'), ('FSGS - cellular variant', 'FSGS - cellular variant'), ('FSGS - perihilar variant', 'FSGS - perihilar variant'), ('FSGS - NOS', 'FSGS - NOS'), ('Lupus nephritis class I', 'Lupus nephritis class I'), ('Lupus nephritis class II', 'Lupus nephritis class II'), ('Lupus nephritis class III', 'Lupus nephritis class III'), ('Lupus nephritis class IV', 'Lupus nephritis class IV'), ('Lupus nephritis class V', 'Lupus nephritis class V'), ('Lupus nephritis class III+V', 'Lupus nephritis class III+V'), ('Lupus nephritis class IV+V', 'Lupus nephritis class IV+V'), ('ANCA-associated pauci-immune crescentic GN - MPO', 'ANCA-associated pauci-immune crescentic GN - MPO'), ('ANCA-associated pauci-immune crescentic GN - PR3', 'ANCA-associated pauci-immune crescentic GN - PR3'), ('ANCA-associated pauci-immune crescentic GN - ANCA negative', 'ANCA-associated pauci-immune crescentic GN - ANCA negative'), ('Anti-GBM disease', 'Anti-GBM disease'), ('C3 glomerulopathy - C3 glomerulonephritis', 'C3 glomerulopathy - C3 glomerulonephritis'), ('C3 glomerulopathy - dense deposit disease', 'C3 glomerulopathy - dense deposit disease'), ('Immune-complex MPGN', 'Immune-complex MPGN'), ('Infection-related GN - post-streptococcal', 'Infection-related GN - post-streptococcal'), ('Infection-related GN - staphylococcal/IgA-dominant', 'Infection-related GN - staphylococcal/IgA-dominant'), ('Infection-related GN - endocarditis-associated', 'Infection-related GN - endocarditis-associated'), ('Infection-related GN - hepatitis B associated', 'Infection-related GN - hepatitis B associated'), ('Infection-related GN - hepatitis C associated', 'Infection-related GN - hepatitis C associated'), ('Cryoglobulinaemic GN', 'Cryoglobulinaemic GN'), ('Monoclonal immunoglobulin deposition disease', 'Monoclonal immunoglobulin deposition disease'), ('Proliferative GN with monoclonal Ig deposits - PGNMID', 'Proliferative GN with monoclonal Ig deposits - PGNMID'), ('Amyloidosis - renal', 'Amyloidosis - renal'), ('Fibrillary GN', 'Fibrillary GN'), ('Immunotactoid GN', 'Immunotactoid GN'), ('C1q nephropathy', 'C1q nephropathy'), ('Thin basement membrane nephropathy', 'Thin basement membrane nephropathy'), ('Alport syndrome / hereditary nephritis', 'Alport syndrome / hereditary nephritis'), ('Thrombotic microangiopathy with glomerular injury', 'Thrombotic microangiopathy with glomerular injury'), ('Diabetic kidney disease only - no GN', 'Diabetic kidney disease only - no GN'), ('Diabetic kidney disease + IgA nephropathy', 'Diabetic kidney disease + IgA nephropathy'), ('Diabetic kidney disease + membranous nephropathy', 'Diabetic kidney disease + membranous nephropathy'), ('Diabetic kidney disease + FSGS', 'Diabetic kidney disease + FSGS'), ('Diabetic kidney disease + lupus nephritis', 'Diabetic kidney disease + lupus nephritis'), ('Diabetic kidney disease + ANCA GN', 'Diabetic kidney disease + ANCA GN'), ('Diabetic kidney disease + infection-related GN', 'Diabetic kidney disease + infection-related GN'), ('Diabetic kidney disease + other GN', 'Diabetic kidney disease + other GN'), ('Hypertensive nephrosclerosis only - no GN', 'Hypertensive nephrosclerosis only - no GN'), ('Tubulointerstitial nephritis predominant', 'Tubulointerstitial nephritis predominant'), ('Other specified GN', 'Other specified GN'), ('Unclassified GN', 'Unclassified GN'), ('Inadequate biopsy / non-diagnostic', 'Inadequate biopsy / non-diagnostic')], max_length=120),
        ),
    ]
