# Generated by Django 6.0.6 on 2026-07-02 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_patient_hospital_id_alter_patient_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='current_phase',
            field=models.CharField(blank=True, choices=[('active', 'Active disease (pre-remission)'), ('remission', 'In remission'), ('post_remission', 'Post-remission monitoring'), ('relapse', 'Relapse')], db_index=True, max_length=16),
        ),
        migrations.AddField(
            model_name='patient',
            name='registration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='registration_status',
            field=models.CharField(choices=[('suspected', 'Suspected — under evaluation'), ('registered', 'Registered in GN clinic'), ('not_registered', 'Not registered (managed elsewhere)'), ('excluded', 'Excluded / not GN')], db_index=True, default='suspected', max_length=16),
        ),
    ]
