# Generated by Django 6.0.6 on 2026-07-09 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patient_current_phase_patient_registration_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Short site code, e.g. BIRDEM, DMCH, SQUARE', max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Site-specific configuration (lab panels, local drugs, etc.)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Site (multi-center)',
                'verbose_name_plural': 'Sites (multi-center)',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='site',
            field=models.ForeignKey(blank=True, help_text='Enrolling/primary site for this patient', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='patients.site'),
        ),
        migrations.CreateModel(
            name='UserSiteRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('site_coordinator', 'Site Coordinator'), ('site_investigator', 'Site Investigator'), ('site_data_manager', 'Site Data Manager'), ('site_readonly', 'Site Read-Only')], default='site_readonly', max_length=20)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary site assignment for this user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='patients.site')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User-Site Role',
                'verbose_name_plural': 'User-Site Roles',
                'unique_together': {('user', 'site')},
            },
        ),
    ]
