# Generated by Django 6.0.6 on 2026-07-14 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_site_patient_site_usersiterole'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='autoimmune_disease',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='biopsy_diagnosis',
            field=models.CharField(blank=True, help_text='GN diagnosis from biopsy (auto-synced from GNDiagnosis)', max_length=120),
        ),
        migrations.AddField(
            model_name='patient',
            name='chronic_infection',
            field=models.BooleanField(default=False, help_text='HBV / HCV / HIV / TB'),
        ),
        migrations.AddField(
            model_name='patient',
            name='ckd_etiology',
            field=models.CharField(blank=True, help_text='CKD aetiology (auto-derived or clinician-entered)', max_length=120),
        ),
        migrations.AddField(
            model_name='patient',
            name='hepatitis_status',
            field=models.CharField(blank=True, choices=[('', '—'), ('negative', 'Negative'), ('hbv', 'HBV'), ('hcv', 'HCV'), ('both', 'HBV + HCV')], max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='hiv_status',
            field=models.CharField(blank=True, choices=[('', '—'), ('negative', 'Negative'), ('positive', 'Positive')], max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='hypertension',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='isn_rps_class',
            field=models.CharField(blank=True, help_text='ISN/RPS class for lupus nephritis (auto-synced)', max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='oxford_mestc',
            field=models.CharField(blank=True, help_text='Oxford MEST-C summary (auto-synced from IgANScore)', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='smoking_status',
            field=models.CharField(blank=True, choices=[('Never', 'Never'), ('Current', 'Current'), ('Former', 'Former'), ('Unknown', 'Unknown')], max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='transplant_status',
            field=models.CharField(blank=True, choices=[('', '—'), ('none', 'No transplant'), ('preemptive', 'Pre-emptive transplant'), ('living', 'Living donor transplant'), ('deceased', 'Deceased donor transplant')], max_length=20),
        ),
    ]
