# Generated by Django 6.0.6 on 2026-07-15 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_longitudinal_level2_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='gn_broad_group',
            field=models.CharField(blank=True, choices=[('Primary GN', 'Primary GN'), ('Secondary GN', 'Secondary GN'), ('DKD only', 'DKD only'), ('DKD + GN', 'DKD + GN'), ('Hereditary GBM disease', 'Hereditary GBM disease'), ('Monoclonal gammopathy-related', 'Monoclonal gammopathy-related'), ('TMA/glomerular vascular injury', 'TMA/glomerular vascular injury'), ('Other/non-diagnostic', 'Other/non-diagnostic')], help_text='Broad disease category (auto-synced from GNDiagnosis)', max_length=80),
        ),
        migrations.AddField(
            model_name='patient',
            name='gn_primary_secondary',
            field=models.CharField(blank=True, choices=[('', '—'), ('primary', 'Primary'), ('secondary', 'Secondary'), ('unknown', 'Unknown')], help_text='Primary vs secondary GN (auto-synced from GNDiagnosis)', max_length=10),
        ),
    ]
