# Generated by Django 6.0.6 on 2026-07-27 16:59

from django.db import migrations, models

# The fields being added here already exist on BaselineAssessment, where they
# were the only place these comorbidities could be recorded. Adding them to
# Patient without copying the existing values would silently reset every
# already-registered patient's history to "no", so backfill first.
BACKFILLED = [
    "cvd_history", "malignancy", "previous_kidney_disease",
    "prior_immunosuppression", "family_history_kidney",
    "diabetic_retinopathy", "neuropathy", "diabetic_foot_history",
]


def backfill_from_baseline(apps, schema_editor):
    Patient = apps.get_model("patients", "Patient")
    BaselineAssessment = apps.get_model("baseline", "BaselineAssessment")

    updates = []
    for baseline in BaselineAssessment.objects.select_related("patient").iterator():
        patient = baseline.patient
        if patient is None:
            continue
        touched = False
        for name in BACKFILLED:
            if getattr(baseline, name, False) and not getattr(patient, name, False):
                setattr(patient, name, True)
                touched = True
        if touched:
            updates.append(patient)

    if updates:
        Patient.objects.bulk_update(updates, BACKFILLED, batch_size=200)


def noop(apps, schema_editor):
    """Reversing drops the columns anyway; nothing to undo."""


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_longitudinal_gn_category'),
        ('baseline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='cvd_history',
            field=models.BooleanField(default=False, verbose_name='Cardiovascular disease'),
        ),
        migrations.AddField(
            model_name='patient',
            name='diabetic_foot_history',
            field=models.BooleanField(default=False, verbose_name='Diabetic foot disease'),
        ),
        migrations.AddField(
            model_name='patient',
            name='diabetic_retinopathy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='family_history_kidney',
            field=models.BooleanField(default=False, verbose_name='Family history of kidney disease'),
        ),
        migrations.AddField(
            model_name='patient',
            name='malignancy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='neuropathy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='previous_kidney_disease',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='prior_immunosuppression',
            field=models.BooleanField(default=False, verbose_name='Previous immunosuppressive therapy'),
        ),
        migrations.RunPython(backfill_from_baseline, noop),
    ]
