# Generated by Django 5.2.16 on 2026-09-27 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathology', '0009_alter_biopsy_arteriolar_hyalinosis_and_more'),
        ('patients', '0008_patient_cvd_history_patient_diabetic_foot_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='condition_provenance',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='pathology_projected_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='pathology_projection_state',
            field=models.CharField(blank=True, choices=[('', '—'), ('final', 'Final (reviewed)'), ('provisional', 'Provisional (local read, review pending)')], editable=False, max_length=12),
        ),
        migrations.AddField(
            model_name='patient',
            name='pathology_source_biopsy',
            field=models.ForeignKey(blank=True, editable=False, help_text='Biopsy the pathology summary below is projected from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pathology.biopsy'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='autoimmune_disease',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='biopsy_diagnosis',
            field=models.CharField(blank=True, help_text='GN diagnosis from biopsy (projected from the selected biopsy)', max_length=120),
        ),
        migrations.AlterField(
            model_name='patient',
            name='chronic_infection',
            field=models.BooleanField(blank=True, default=None, help_text='HBV / HCV / HIV / TB', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='cvd_history',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Cardiovascular disease'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='diabetes_status',
            field=models.CharField(choices=[('none', 'No diabetes'), ('t1', 'Type 1'), ('t2', 'Type 2'), ('other', 'Other / secondary'), ('unknown', 'Diabetes, type not recorded')], default='none', max_length=8),
        ),
        migrations.AlterField(
            model_name='patient',
            name='diabetic_foot_history',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Diabetic foot disease'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='diabetic_retinopathy',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='family_history_kidney',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Family history of kidney disease'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='hypertension',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='malignancy',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='neuropathy',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='previous_kidney_disease',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='prior_immunosuppression',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Previous immunosuppressive therapy'),
        ),
    ]
