"""Seed the DrugIntelligence knowledge base for glomerular-disease drugs.

Idempotent (update_or_create by drug id). Populates the disease-independent
clinical drug knowledge that powers the Drug Intelligence page. Content is
standard, guideline-aligned nephrology knowledge and should be reviewed by a
nephrologist before clinical reliance (see clinical governance).

    python manage.py seed_drug_intelligence
"""
from django.core.management.base import BaseCommand


# Each entry maps to the DrugIntelligence model fields. `indications` is a list
# of Disease ids to link (only those present in the DB are linked).
DRUGS = [
    {
        "id": "prednisolone", "name": "Prednisolone", "drug_class": "Corticosteroid",
        "mechanism_of_action": "Broad genomic and non-genomic immunosuppression: inhibits NF-κB, reduces cytokine transcription, lymphocyte and eosinophil activity.",
        "indications": ["mcd", "fsgs", "lupus", "anca", "iga", "membranous", "irgn"],
        "contraindications": "Systemic fungal infection; live vaccines during high-dose therapy; hypersensitivity. Relative: uncontrolled diabetes, active peptic ulcer, severe osteoporosis, poorly controlled hypertension/psychosis.",
        "renal_dosing": "No renal dose adjustment; use lowest effective dose. Watch fluid retention and hypertension in CKD.",
        "dialysis_dosing": "Not significantly dialysed; dose as per clinical need.",
        "transplant_considerations": "Backbone of maintenance immunosuppression; taper per protocol.",
        "pregnancy": "Generally acceptable when needed (minimal placental transfer of prednis(ol)one). Prefer lowest effective dose; monitor for gestational diabetes/hypertension.",
        "lactation": "Compatible; for high doses, consider a 4-hour delay before nursing.",
        "drug_interactions": ["CYP3A4 inducers (rifampicin) reduce levels", "NSAIDs increase GI bleeding risk", "Live vaccines contraindicated at immunosuppressive doses", "Additive hypokalaemia with loop/thiazide diuretics"],
        "laboratory_monitoring": "Fasting glucose/HbA1c, blood pressure, weight, bone density (prolonged use), electrolytes.",
        "vaccination_advice": "Complete inactivated vaccines before therapy if possible; avoid live vaccines at ≥20 mg/day prednisolone equivalent for ≥2 weeks.",
        "common_side_effects": ["Weight gain", "Hyperglycaemia", "Mood/sleep disturbance", "Increased appetite", "Cushingoid features"],
        "serious_side_effects": ["Osteoporosis/fracture", "Avascular necrosis", "Serious infection", "Adrenal suppression", "Steroid psychosis"],
        "stopping_criteria": "Taper gradually to avoid adrenal insufficiency; never stop high-dose therapy abruptly.",
        "evidence_level": "1",
        "guideline_references": ["KDIGO 2021 Glomerular Diseases"],
    },
    {
        "id": "mycophenolate", "name": "Mycophenolate mofetil", "drug_class": "IMPDH inhibitor (antimetabolite)",
        "mechanism_of_action": "Inhibits inosine-5'-monophosphate dehydrogenase, depleting guanosine nucleotides and selectively suppressing T- and B-lymphocyte proliferation.",
        "indications": ["lupus", "anca", "membranous", "fsgs", "iga"],
        "contraindications": "Pregnancy (teratogen — REMS/pregnancy-prevention required); hypersensitivity. Caution in active serious infection and severe GI disease.",
        "renal_dosing": "No fixed adjustment; higher MPA exposure in severe CKD — monitor tolerance/CBC. Reduce dose for cytopenias.",
        "dialysis_dosing": "Not removed by dialysis; dose per tolerance.",
        "transplant_considerations": "Standard maintenance agent; target by tolerance/CBC (routine MPA levels not required).",
        "pregnancy": "Contraindicated — first-trimester loss and characteristic malformations. Two reliable contraceptive methods; stop ≥6 weeks before conception.",
        "lactation": "Avoid — insufficient safety data.",
        "drug_interactions": ["Antacids/iron reduce absorption", "Cholestyramine reduces enterohepatic recirculation", "Aciclovir/valaciclovir competition raises levels in renal impairment", "Reduced efficacy of oral contraceptives (use additional method)"],
        "laboratory_monitoring": "CBC weekly x1 month, then every 2 weeks x2 months, then monthly; LFTs periodically.",
        "vaccination_advice": "Avoid live vaccines; inactivated vaccines may have reduced response.",
        "common_side_effects": ["Diarrhoea/GI upset", "Nausea", "Leukopenia", "Increased infections"],
        "serious_side_effects": ["Severe neutropenia", "Serious/opportunistic infection", "PML (rare)", "PRCA (rare)"],
        "stopping_criteria": "Hold for ANC < 1.3 ×10⁹/L or severe infection; reduce/hold for intolerable GI effects.",
        "evidence_level": "1",
        "guideline_references": ["KDIGO 2021 Glomerular Diseases", "KDIGO 2024 Lupus Nephritis"],
    },
    {
        "id": "cyclophosphamide", "name": "Cyclophosphamide", "drug_class": "Alkylating agent",
        "mechanism_of_action": "Alkylates DNA (cross-linking), depleting proliferating B and T lymphocytes; potent immunosuppression.",
        "indications": ["anca", "lupus", "antiGbm", "membranous"],
        "contraindications": "Pregnancy; severe active infection; severe myelosuppression; haemorrhagic cystitis; hypersensitivity.",
        "renal_dosing": "Reduce dose in significant renal impairment (active metabolite accumulation); IV pulse regimens reduce cumulative dose vs oral.",
        "dialysis_dosing": "Dialysable — give after dialysis; reduce dose.",
        "transplant_considerations": "Rarely used post-transplant; consider marrow toxicity with other agents.",
        "pregnancy": "Contraindicated — teratogenic. Effective contraception essential; counsel on fertility (gonadotoxicity).",
        "lactation": "Contraindicated.",
        "drug_interactions": ["Allopurinol increases myelosuppression", "Concurrent nephrotoxins worsen toxicity", "Reduces effect of some vaccines"],
        "laboratory_monitoring": "CBC weekly during treatment (nadir 10–14 days), urinalysis for haematuria, at each pulse before dosing.",
        "vaccination_advice": "Avoid live vaccines; vaccinate before therapy where possible.",
        "common_side_effects": ["Nausea/vomiting", "Alopecia", "Leukopenia", "Infection risk"],
        "serious_side_effects": ["Haemorrhagic cystitis (use MESNA/hydration)", "Bladder cancer (cumulative)", "Infertility", "Secondary malignancy", "Severe cytopenia"],
        "stopping_criteria": "Hold for ANC < 1.5–2.0 ×10⁹/L, active infection, or haemorrhagic cystitis; cap cumulative lifetime dose.",
        "evidence_level": "1",
        "guideline_references": ["KDIGO 2021 Glomerular Diseases"],
    },
    {
        "id": "rituximab", "name": "Rituximab", "drug_class": "Anti-CD20 monoclonal antibody",
        "mechanism_of_action": "Depletes CD20+ B lymphocytes via ADCC/CDC and apoptosis, reducing pathogenic antibody production.",
        "indications": ["membranous", "anca", "lupus", "fsgs", "mcd"],
        "contraindications": "Active severe infection; active hepatitis B (reactivation risk); severe hypersensitivity to murine proteins.",
        "renal_dosing": "No renal dose adjustment.",
        "dialysis_dosing": "Not dialysed (large protein); dose as usual.",
        "transplant_considerations": "Used for antibody-mediated rejection and desensitisation.",
        "pregnancy": "Avoid; if used, neonatal B-cell depletion possible — plan last dose well before conception.",
        "lactation": "Limited data; likely minimal transfer but avoid where alternatives exist.",
        "drug_interactions": ["Live vaccines contraindicated (avoid for ~6 months after)", "Additive immunosuppression/infection with other agents"],
        "laboratory_monitoring": "HBV serology (HBsAg, anti-HBc) and screening before therapy; CD19/20 counts, immunoglobulins; CBC.",
        "vaccination_advice": "Complete vaccines ≥4 weeks before; avoid live vaccines; poor response for ~6 months after B-cell depletion.",
        "common_side_effects": ["Infusion reactions", "Increased infections", "Fatigue"],
        "serious_side_effects": ["HBV reactivation", "PML (rare)", "Severe infusion reaction", "Late-onset neutropenia", "Hypogammaglobulinaemia"],
        "stopping_criteria": "Hold for serious infection; treat/prophylax HBV before use; monitor IgG for recurrent infections.",
        "evidence_level": "1",
        "guideline_references": ["KDIGO 2021 Glomerular Diseases (MENTOR/RITUXVAS)"],
    },
    {
        "id": "tacrolimus", "name": "Tacrolimus", "drug_class": "Calcineurin inhibitor (CNI)",
        "mechanism_of_action": "Binds FKBP-12, inhibiting calcineurin and IL-2–driven T-cell activation; also stabilises the podocyte actin cytoskeleton.",
        "indications": ["membranous", "fsgs", "mcd", "lupus"],
        "contraindications": "Hypersensitivity; caution with QT prolongation, significant hyperkalaemia, and pre-existing severe CKD.",
        "renal_dosing": "Nephrotoxic — titrate to trough; reduce for rising creatinine; avoid volume depletion.",
        "dialysis_dosing": "Not significantly dialysed; dose by trough level.",
        "transplant_considerations": "Core maintenance immunosuppressant; target trough varies by time post-transplant.",
        "pregnancy": "Generally continued in transplant pregnancy; monitor levels (often need dose increase); watch BP, glucose, K⁺.",
        "lactation": "Low relative infant dose; considered compatible with monitoring.",
        "drug_interactions": ["Strong CYP3A4 inhibitors (azoles, diltiazem, clarithromycin, grapefruit) raise levels", "CYP3A4 inducers (rifampicin) lower levels", "Additive nephrotoxicity with NSAIDs/aminoglycosides", "Hyperkalaemia with RAAS inhibitors"],
        "laboratory_monitoring": "Trough levels, serum creatinine/eGFR, potassium, glucose, blood pressure, magnesium.",
        "vaccination_advice": "Avoid live vaccines; inactivated vaccines acceptable.",
        "common_side_effects": ["Tremor", "Hyperglycaemia", "Hypertension", "Hyperkalaemia", "Hypomagnesaemia"],
        "serious_side_effects": ["Nephrotoxicity (acute & chronic)", "New-onset diabetes", "TMA", "Neurotoxicity", "Serious infection"],
        "stopping_criteria": "Reduce/hold for rising creatinine (>25–30% above baseline), TMA, or severe hyperkalaemia.",
        "evidence_level": "1",
        "guideline_references": ["KDIGO 2021 Glomerular Diseases"],
    },
    {
        "id": "cyclosporine", "name": "Cyclosporine", "drug_class": "Calcineurin inhibitor (CNI)",
        "mechanism_of_action": "Binds cyclophilin to inhibit calcineurin and IL-2 transcription; podocyte-stabilising antiproteinuric effect.",
        "indications": ["fsgs", "mcd", "membranous", "lupus"],
        "contraindications": "Uncontrolled hypertension; significant renal impairment; malignancy; hypersensitivity.",
        "renal_dosing": "Nephrotoxic — titrate to trough; avoid in significant CKD; reduce for rising creatinine.",
        "dialysis_dosing": "Not significantly dialysed; dose by level.",
        "transplant_considerations": "Alternative CNI; more cosmetic side effects than tacrolimus.",
        "pregnancy": "Used in transplant pregnancy with monitoring; watch BP and renal function.",
        "lactation": "Compatible with monitoring in most guidance.",
        "drug_interactions": ["CYP3A4 inhibitors raise levels", "Statins — increased myopathy/rhabdomyolysis risk", "Additive nephrotoxicity/hyperkalaemia with RAAS/NSAIDs"],
        "laboratory_monitoring": "Trough levels, creatinine/eGFR, blood pressure, lipids, potassium, uric acid.",
        "vaccination_advice": "Avoid live vaccines.",
        "common_side_effects": ["Hypertension", "Gingival hyperplasia", "Hirsutism", "Tremor", "Hyperlipidaemia"],
        "serious_side_effects": ["Nephrotoxicity", "TMA", "Malignancy risk", "Serious infection"],
        "stopping_criteria": "Reduce/hold for rising creatinine, uncontrolled hypertension, or TMA.",
        "evidence_level": "1",
        "guideline_references": ["KDIGO 2021 Glomerular Diseases"],
    },
    {
        "id": "azathioprine", "name": "Azathioprine", "drug_class": "Purine antimetabolite",
        "mechanism_of_action": "Converted to 6-mercaptopurine; inhibits purine synthesis and lymphocyte proliferation.",
        "indications": ["anca", "lupus", "iga"],
        "contraindications": "Hypersensitivity; concurrent allopurinol at standard dose; very low TPMT activity. Pregnancy category — generally continued when needed.",
        "renal_dosing": "Consider dose reduction in significant renal impairment.",
        "dialysis_dosing": "Partially dialysed; dose after dialysis.",
        "transplant_considerations": "Alternative maintenance agent (esp. in pregnancy where MMF is contraindicated).",
        "pregnancy": "Considered compatible (preferred over MMF) — continue where needed with monitoring.",
        "lactation": "Compatible; monitor infant if high dose.",
        "drug_interactions": ["Allopurinol/febuxostat markedly increase toxicity (reduce azathioprine to 25% or avoid)", "ACEi may increase anaemia/leukopenia", "Warfarin effect altered"],
        "laboratory_monitoring": "TPMT before starting; CBC weekly initially then periodically; LFTs.",
        "vaccination_advice": "Avoid live vaccines.",
        "common_side_effects": ["Nausea", "Leukopenia", "Raised transaminases"],
        "serious_side_effects": ["Severe myelosuppression (TPMT-deficient)", "Hepatotoxicity", "Pancreatitis", "Long-term malignancy risk"],
        "stopping_criteria": "Hold for significant cytopenia or hepatotoxicity; avoid full-dose with allopurinol.",
        "evidence_level": "2",
        "guideline_references": ["KDIGO 2021 Glomerular Diseases"],
    },
    {
        "id": "hydroxychloroquine", "name": "Hydroxychloroquine", "drug_class": "Antimalarial / immunomodulator",
        "mechanism_of_action": "Raises endosomal pH, impairs antigen presentation and TLR signalling; immunomodulatory and antithrombotic.",
        "indications": ["lupus"],
        "contraindications": "Known retinopathy; hypersensitivity. Caution with QT-prolonging drugs and G6PD deficiency.",
        "renal_dosing": "Consider dose reduction in severe CKD; renal clearance contributes to elimination.",
        "dialysis_dosing": "Not significantly dialysed.",
        "transplant_considerations": "Generally safe adjunct.",
        "pregnancy": "Recommended to continue in lupus pregnancy — reduces flares and congenital heart block risk.",
        "lactation": "Compatible.",
        "drug_interactions": ["QT-prolonging agents (additive)", "Increases digoxin and ciclosporin levels", "Antacids reduce absorption"],
        "laboratory_monitoring": "Baseline and annual ophthalmology (retinopathy screening); ECG if QT risk.",
        "vaccination_advice": "No specific restriction (not significantly immunosuppressive).",
        "common_side_effects": ["GI upset", "Headache", "Skin pigmentation"],
        "serious_side_effects": ["Irreversible retinopathy (dose/duration related)", "QT prolongation", "Cardiomyopathy (rare)"],
        "stopping_criteria": "Stop for confirmed retinopathy; keep ≤5 mg/kg actual body weight/day to minimise risk.",
        "evidence_level": "1",
        "guideline_references": ["KDIGO 2024 Lupus Nephritis"],
    },
    {
        "id": "dapagliflozin", "name": "Dapagliflozin", "drug_class": "SGLT2 inhibitor",
        "mechanism_of_action": "Inhibits renal SGLT2, reducing glucose/sodium reabsorption; lowers intraglomerular pressure via tubuloglomerular feedback — nephroprotective and antiproteinuric.",
        "indications": ["iga", "fsgs", "diabeticNephropathy", "membranous"],
        "contraindications": "Type 1 diabetes for glycaemic use; prior serious DKA; hypersensitivity. Caution with recurrent genital infection.",
        "renal_dosing": "Initiate down to eGFR ≥20 for kidney protection (per DAPA-CKD); expected initial eGFR 'dip' is benign. Limited glucose-lowering at low eGFR.",
        "dialysis_dosing": "Not for use on dialysis.",
        "transplant_considerations": "Emerging use; watch for urinary/genital infection.",
        "pregnancy": "Not recommended — discontinue.",
        "lactation": "Not recommended.",
        "drug_interactions": ["Additive volume depletion with diuretics", "Hypoglycaemia risk with insulin/sulfonylureas (reduce those)", "Hold during acute illness (sick-day rule)"],
        "laboratory_monitoring": "eGFR at ~2–4 weeks after start (expect small dip), volume status, foot/genital review.",
        "vaccination_advice": "No restriction.",
        "common_side_effects": ["Genital mycotic infection", "Polyuria", "Volume depletion", "Small reversible eGFR dip"],
        "serious_side_effects": ["Euglycaemic DKA (rare)", "Fournier gangrene (very rare)", "Volume depletion/AKI if over-diuresed"],
        "stopping_criteria": "Withhold during acute serious illness/surgery (DKA risk); stop in pregnancy.",
        "evidence_level": "1",
        "guideline_references": ["KDIGO 2024 CKD (DAPA-CKD, EMPA-KIDNEY)"],
    },
    {
        "id": "finerenone", "name": "Finerenone", "drug_class": "Nonsteroidal mineralocorticoid receptor antagonist",
        "mechanism_of_action": "Selective nonsteroidal MRA reducing inflammation and fibrosis; antiproteinuric and cardiorenal-protective.",
        "indications": ["diabeticNephropathy"],
        "contraindications": "Hyperkalaemia (K⁺ > 5.0 at initiation); Addison disease; strong CYP3A4 inhibitors; hypersensitivity.",
        "renal_dosing": "Start based on eGFR and potassium; avoid initiation if K⁺ > 5.0 mmol/L; not for eGFR < 25 initiation.",
        "dialysis_dosing": "Not recommended.",
        "transplant_considerations": "Limited data.",
        "pregnancy": "Not recommended.",
        "lactation": "Not recommended.",
        "drug_interactions": ["Strong CYP3A4 inhibitors (contraindicated)", "Additive hyperkalaemia with RAASi/K⁺-sparing diuretics/K⁺ supplements", "CYP3A4 inducers reduce effect"],
        "laboratory_monitoring": "Potassium and eGFR at baseline, 4 weeks, and periodically; adjust/withhold for hyperkalaemia.",
        "vaccination_advice": "No restriction.",
        "common_side_effects": ["Hyperkalaemia", "Hypotension", "Small eGFR reduction"],
        "serious_side_effects": ["Severe hyperkalaemia"],
        "stopping_criteria": "Withhold for K⁺ > 5.5 mmol/L; recheck and restart when ≤5.0.",
        "evidence_level": "1",
        "guideline_references": ["KDIGO 2024 CKD (FIDELIO/FIGARO-DKD)"],
    },
    {
        "id": "raas_inhibitor", "name": "ACE inhibitor / ARB (RAAS blockade)", "drug_class": "RAAS inhibitor",
        "mechanism_of_action": "Reduces angiotensin II activity, lowering intraglomerular pressure and proteinuria; foundational nephroprotection.",
        "indications": ["iga", "fsgs", "membranous", "diabeticNephropathy", "alport"],
        "contraindications": "Pregnancy; bilateral renal artery stenosis; angio-oedema history; hyperkalaemia; do NOT combine ACEi with ARB.",
        "renal_dosing": "Titrate to maximum tolerated dose; an early creatinine rise up to ~30% is acceptable; recheck K⁺/creatinine after changes.",
        "dialysis_dosing": "Use per BP/indication; some agents dialysable.",
        "transplant_considerations": "Useful for proteinuria/BP; monitor K⁺ and creatinine, especially with CNIs.",
        "pregnancy": "Contraindicated — fetal renal toxicity; switch before/at conception.",
        "lactation": "Some agents (e.g., enalapril, captopril) considered compatible.",
        "drug_interactions": ["Hyperkalaemia with K⁺-sparing diuretics/finerenone/trimethoprim", "NSAIDs reduce efficacy and worsen renal function", "Additive hypotension with diuretics", "Lithium levels increased"],
        "laboratory_monitoring": "Serum creatinine and potassium 1–2 weeks after initiation/uptitration, then periodically; blood pressure.",
        "vaccination_advice": "No restriction.",
        "common_side_effects": ["Cough (ACEi)", "Hyperkalaemia", "Hypotension", "Reversible creatinine rise"],
        "serious_side_effects": ["Angio-oedema", "AKI (volume depletion/RAS)", "Severe hyperkalaemia"],
        "stopping_criteria": "Hold for creatinine rise > 30%, K⁺ > 5.5 mmol/L, angio-oedema, or pregnancy.",
        "evidence_level": "1",
        "guideline_references": ["KDIGO 2021 Glomerular Diseases", "KDIGO 2024 CKD"],
    },
    {
        "id": "sparsentan", "name": "Sparsentan", "drug_class": "Dual endothelin-A / angiotensin-II receptor antagonist",
        "mechanism_of_action": "Simultaneous ETA and AT1 receptor antagonism; potent antiproteinuric effect in IgA nephropathy.",
        "indications": ["iga", "fsgs"],
        "contraindications": "Pregnancy (REMS — hepatotoxicity and embryo-fetal toxicity); concomitant ARB or ERA; hypersensitivity.",
        "renal_dosing": "Per label; monitor for fluid retention; expected initial eGFR dip.",
        "dialysis_dosing": "Not established.",
        "transplant_considerations": "Not established.",
        "pregnancy": "Contraindicated — REMS program; effective contraception and pregnancy testing required.",
        "lactation": "Avoid.",
        "drug_interactions": ["Do not combine with ARB or other endothelin antagonist", "Additive hyperkalaemia with RAASi/K⁺-sparing agents", "Strong CYP3A inducers reduce levels"],
        "laboratory_monitoring": "LFTs at baseline and monthly (per REMS), potassium, eGFR, fluid status/BP, pregnancy testing.",
        "vaccination_advice": "No restriction.",
        "common_side_effects": ["Peripheral oedema", "Hypotension", "Hyperkalaemia", "eGFR dip"],
        "serious_side_effects": ["Hepatotoxicity", "Fluid retention/heart failure", "Embryo-fetal toxicity"],
        "stopping_criteria": "Stop for significant transaminase rise, fluid overload, or pregnancy.",
        "evidence_level": "1",
        "guideline_references": ["KDIGO 2025 IgAN/IgAV (PROTECT)"],
    },
]


class Command(BaseCommand):
    help = "Seed/refresh the DrugIntelligence knowledge base for GN drugs (idempotent)."

    def handle(self, *args, **options):
        from knowledge.models import DrugIntelligence, Disease

        created = updated = 0
        for d in DRUGS:
            indications = d.pop("indications", [])
            obj, was_created = DrugIntelligence.objects.update_or_create(
                id=d["id"], defaults={k: v for k, v in d.items() if k != "id"},
            )
            # Link indications that exist as Disease rows.
            diseases = list(Disease.objects.filter(pk__in=indications))
            obj.indications.set(diseases)
            d["indications"] = indications  # restore for idempotent re-runs
            created += int(was_created)
            updated += int(not was_created)

        self.stdout.write(self.style.SUCCESS(
            f"DrugIntelligence seeded: {created} created, {updated} updated "
            f"({DrugIntelligence.objects.count()} total)."
        ))
