from datetime import date
from django.contrib.auth.models import User
from django.core.management.base import BaseCommand
from django.utils import timezone

from knowledge.models import GuidelineSource, KnowledgeBaseEntry

DISEASE_CHAPTERS = {
    "iga": "Chapter 3: IgA Nephropathy / KDIGO 2025 IgAN and IgAV Guideline",
    "membranous": "Chapter 4: Membranous Nephropathy / KDIGO 2021 Glomerular Diseases Guideline",
    "mcd": "Chapter 5: Minimal Change Disease / KDIGO 2025 Nephrotic Syndrome Guideline",
    "fsgs": "Chapter 6: Focal Segmental Glomerulosclerosis / KDIGO 2021 Glomerular Diseases Guideline",
    "mpgn": "Chapter 7: Membranoproliferative GN / KDIGO 2021 Glomerular Diseases Guideline",
    "lupus": "Chapter 8: Lupus Nephritis / KDIGO 2021 Glomerular Diseases Guideline",
    "anca": "Chapter 9: Pauci-immune GN / KDIGO 2021 Glomerular Diseases Guideline",
    "antiGbm": "Chapter 10: Anti-GBM Crescentic GN / KDIGO 2021 Glomerular Diseases Guideline",
    "infectionRelated": "Chapter 11: Infection-Related GN / KDIGO 2021 Glomerular Diseases Guideline",
    "castNephropathy": "Chapter 12: Light Chain Cast Nephropathy / KDIGO 2021 Glomerular Diseases Guideline",
    "fibrillaryGlomerulonephritis": "Chapter 13: Fibrillary GN / KDIGO 2021 Glomerular Diseases Guideline",
    "amyloidosis": "Chapter 14: Renal Amyloidosis / KDIGO 2021 Glomerular Diseases Guideline",
    "diabeticNephropathyWithGN": "Chapter 4: Diabetes Management in CKD / KDIGO 2024 Guideline",
    "diabeticNephropathy": "Chapter 4: Diabetes Management in CKD / KDIGO 2024 Guideline",
    "acuteInterstitialNephritis": "Chapter 13: Acute Interstitial Nephritis / KDIGO 2021 Glomerular Diseases Guideline",
    "acuteTubularNecrosis": "Chapter 12: Acute Tubular Necrosis / KDIGO 2021 AKI Guideline",
    "c3": "Chapter 7: C3 Glomerulopathy / KDIGO 2021 Glomerular Diseases Guideline",
    "hypertensiveNephrosclerosis": "Chapter 3: Hypertensive Nephrosclerosis / KDIGO 2021 BP Guideline",
    "lightChainCastNephropathy": "Chapter 12: Light Chain Cast Nephropathy / KDIGO 2021 Glomerular Diseases Guideline",
    "thromboticMicroangiopathy": "Chapter 11: Thrombotic Microangiopathy / KDIGO 2021 Glomerular Diseases Guideline",
    "denseDepositDisease": "Chapter 7: Dense Deposit Disease / KDIGO 2021 Glomerular Diseases Guideline",
    "mgrs": "Chapter 12: Monoclonal Gammopathy of Renal Significance / KDIGO 2021 Glomerular Diseases Guideline",
    "cryoglobulinemic": "Chapter 11: Cryoglobulinemic GN / KDIGO 2021 Glomerular Diseases Guideline",
    "immunotactoid": "Chapter 13: Immunotactoid Glomerulopathy / KDIGO 2021 Glomerular Diseases Guideline",
    "alport": "Chapter 15: Alport Syndrome / KDIGO 2021 Glomerular Diseases Guideline",
    "thinBasementMembrane": "Chapter 15: Thin Basement Membrane Nephropathy / KDIGO 2021 Guideline",
    "cfhr": "Chapter 7: Complement-Mediated Diseases / KDIGO 2021 Glomerular Diseases Guideline",
    "fabry": "Chapter 15: Fabry Disease / KDIGO 2021 Glomerular Diseases Guideline",
    "hbvAssociatedGN": "Chapter 11: Infection-Related GN / KDIGO 2021 Glomerular Diseases Guideline",
    "hcvAssociatedGN": "Chapter 11: Infection-Related GN / KDIGO 2021 Glomerular Diseases Guideline",
    "igg4Related": "Chapter 16: IgG4-Related Kidney Disease / KDIGO 2021 Glomerular Diseases Guideline",
    "paraneoplastic": "Chapter 16: Paraneoplastic GN / KDIGO 2021 Glomerular Diseases Guideline",
    "sarcoidosisAssociatedGN": "Chapter 16: Sarcoidosis-Associated GN / KDIGO 2021 Glomerular Diseases Guideline",
    "hivan": "Chapter 11: HIV-Associated Nephropathy / KDIGO 2021 Glomerular Diseases Guideline",
    "drugInducedGn": "Chapter 16: Drug-Induced GN / KDIGO 2021 Glomerular Diseases Guideline",
    "recurrentIgaNephropathy": "Chapter 17: Recurrent Glomerular Disease in Transplant / KDIGO 2021 Guideline",
    "recurrentFSGS": "Chapter 17: Recurrent Glomerular Disease in Transplant / KDIGO 2021 Guideline",
    "recurrentMembranous": "Chapter 17: Recurrent Glomerular Disease in Transplant / KDIGO 2021 Guideline",
    "transplantGlomerulopathy": "Chapter 17: Transplant Glomerulopathy / KDIGO 2021 Guideline",
    "antibodyMediatedRejection": "Chapter 18: Antibody-Mediated Rejection / KDIGO 2021 Guideline",
    "tCellMediatedRejection": "Chapter 18: T Cell-Mediated Rejection / KDIGO 2021 Guideline",
    "cniToxicity": "Chapter 18: CNI Toxicity / KDIGO 2021 Guideline",
    "bkVirusNephropathy": "Chapter 18: BK Virus Nephropathy / KDIGO 2021 Guideline",
}

DISEASE_URLS = {
    "iga": "https://kdigo.org/guidelines/iga-nephropathy/",
    "membranous": "https://kdigo.org/guidelines/glomerulonephritis/",
    "mcd": "https://kdigo.org/guidelines/nephrotic-syndrome-children/",
    "fsgs": "https://kdigo.org/guidelines/glomerulonephritis/",
    "mpgn": "https://kdigo.org/guidelines/glomerulonephritis/",
    "lupus": "https://kdigo.org/guidelines/glomerulonephritis/",
    "anca": "https://kdigo.org/guidelines/glomerulonephritis/",
    "antiGbm": "https://kdigo.org/guidelines/glomerulonephritis/",
    "infectionRelated": "https://kdigo.org/guidelines/glomerulonephritis/",
    "castNephropathy": "https://kdigo.org/guidelines/glomerulonephritis/",
    "fibrillaryGlomerulonephritis": "https://kdigo.org/guidelines/glomerulonephritis/",
    "amyloidosis": "https://kdigo.org/guidelines/glomerulonephritis/",
    "diabeticNephropathyWithGN": "https://kdigo.org/guidelines/diabetes-ckd/",
    "diabeticNephropathy": "https://kdigo.org/guidelines/diabetes-ckd/",
    "acuteInterstitialNephritis": "https://kdigo.org/guidelines/glomerulonephritis/",
    "acuteTubularNecrosis": "https://kdigo.org/guidelines/aki/",
    "c3": "https://kdigo.org/guidelines/glomerulonephritis/",
    "hypertensiveNephrosclerosis": "https://kdigo.org/guidelines/blood-pressure/",
    "lightChainCastNephropathy": "https://kdigo.org/guidelines/glomerulonephritis/",
    "thromboticMicroangiopathy": "https://kdigo.org/guidelines/glomerulonephritis/",
    "denseDepositDisease": "https://kdigo.org/guidelines/glomerulonephritis/",
    "mgrs": "https://kdigo.org/guidelines/glomerulonephritis/",
    "cryoglobulinemic": "https://kdigo.org/guidelines/glomerulonephritis/",
    "immunotactoid": "https://kdigo.org/guidelines/glomerulonephritis/",
    "alport": "https://kdigo.org/guidelines/glomerulonephritis/",
    "thinBasementMembrane": "https://kdigo.org/guidelines/glomerulonephritis/",
    "cfhr": "https://kdigo.org/guidelines/glomerulonephritis/",
    "fabry": "https://kdigo.org/guidelines/glomerulonephritis/",
    "hbvAssociatedGN": "https://kdigo.org/guidelines/glomerulonephritis/",
    "hcvAssociatedGN": "https://kdigo.org/guidelines/glomerulonephritis/",
    "igg4Related": "https://kdigo.org/guidelines/glomerulonephritis/",
    "paraneoplastic": "https://kdigo.org/guidelines/glomerulonephritis/",
    "sarcoidosisAssociatedGN": "https://kdigo.org/guidelines/glomerulonephritis/",
    "hivan": "https://kdigo.org/guidelines/glomerulonephritis/",
    "drugInducedGn": "https://kdigo.org/guidelines/glomerulonephritis/",
    "recurrentIgaNephropathy": "https://kdigo.org/guidelines/glomerulonephritis/",
    "recurrentFSGS": "https://kdigo.org/guidelines/glomerulonephritis/",
    "recurrentMembranous": "https://kdigo.org/guidelines/glomerulonephritis/",
    "transplantGlomerulopathy": "https://kdigo.org/guidelines/glomerulonephritis/",
    "antibodyMediatedRejection": "https://kdigo.org/guidelines/glomerulonephritis/",
    "tCellMediatedRejection": "https://kdigo.org/guidelines/glomerulonephritis/",
    "cniToxicity": "https://kdigo.org/guidelines/glomerulonephritis/",
    "bkVirusNephropathy": "https://kdigo.org/guidelines/glomerulonephritis/",
}
DISEASE_RULES = {
    "iga": {
        "name": "IgA nephropathy or IgA vasculitis nephritis",
        "base": 2,
        "rules": [
            (["sediment", "hematuria"], 2, "Dysmorphic hematuria supports glomerular inflammation."),
            (["sediment", "casts"], 3, "RBC casts point to active glomerulonephritis."),
            (["feature", "grossHematuria"], 3, "Gross hematuria can occur with IgA nephropathy, often around mucosal infection."),
            (["feature", "postInfectious"], 1, "Infection-timed hematuria keeps IgA nephropathy and infection-related GN in view."),
            (["feature", "purpura"], 3, "Purpura plus kidney findings raises IgA vasculitis nephritis."),
            (["feature", "arthritis"], 1, "Arthralgia is compatible with IgA vasculitis."),
            (["biopsy", "mesangialIga"], 6, "Dominant mesangial IgA is a defining biopsy clue."),
            (["proteinuria", "subnephrotic"], 1, "Proteinuria is common and should be quantified."),
            (["proteinuria", "nephrotic"], 1, "Nephrotic-range proteinuria can mark higher-risk IgA disease."),
            (["lab", "lowC3"], -1, "Low C3 is not typical of isolated IgA nephropathy."),
            (["feature", "chronicTonsillitis"], 2, "Tonsillitis-synchronous hematuria is classic for IgA nephropathy."),
            (["feature", "loinPain"], 1, "Loin pain can accompany macroscopic hematuria episodes in IgA nephropathy."),
            (["biopsy", "crescents"], 2, "Crescents on biopsy indicate active proliferative IgA nephropathy."),
            (["biopsy", "segmentalSclerosis"], 1, "Segmental sclerosis can be seen in advanced IgA lesions."),
            (["ageGroup", "adult"], 1, "IgA nephropathy commonly presents in young adults (20-40 years)."),
            (["feature", "hypertension"], 1, "Hypertension at presentation is a risk factor for progression in IgAN."),
        ],
        "source_abbr": "KDIGO",
        "source_year": 2025,
        "source_title": "KDIGO 2025 IgAN and IgAV Guideline",
    },
    "membranous": {
        "name": "Membranous nephropathy",
        "base": 1,
        "rules": [
            (["proteinuria", "nephrotic"], 4, "Nephrotic-range proteinuria is a classic presentation."),
            (["albumin", "low"], 2, "Hypoalbuminemia supports nephrotic syndrome physiology."),
            (["sediment", "bland"], 2, "A bland sediment fits a podocytopathy or membranous pattern."),
            (["lab", "pla2r"], 5, "PLA2R positivity strongly supports primary membranous nephropathy."),
            (["biopsy", "subepithelial"], 5, "Subepithelial deposits or spikes are characteristic."),
            (["lab", "hepatitis"], 1, "Infection screening matters when membranous nephropathy is suspected."),
            (["lab", "anaDsDna"], -1, "Positive lupus serology shifts the differential."),
            (["feature", "thrombosis"], 2, "Venous thromboembolism risk is increased in membranous nephropathy."),
            (["feature", "edema"], 1, "Peripheral edema is common with nephrotic-range proteinuria."),
            (["ageGroup", "adult"], 2, "Primary membranous is predominantly an adult disease (peak 40-60 years)."),
            (["lab", "antiGbm"], -1, "Anti-GBM positivity suggests dual anti-GBM/membranous or different diagnosis."),
            (["feature", "malignancy"], 1, "Secondary membranous can be associated with solid malignancies."),
            (["feature", "autoimmune"], 1, "Autoimmune conditions like SLE, RA, thyroiditis can cause secondary membranous."),
        ],
        "source_abbr": "KDIGO",
        "source_year": 2021,
        "source_title": "KDIGO 2021 Glomerular Diseases Guideline",
    },
    "mcd": {
        "name": "Minimal change disease",
        "base": 1,
        "rules": [
            (["ageGroup", "child"], 3, "Childhood nephrotic syndrome is often steroid-sensitive minimal change disease."),
            (["proteinuria", "nephrotic"], 4, "Abrupt nephrotic syndrome is a typical pattern."),
            (["albumin", "low"], 2, "Low serum albumin supports nephrotic syndrome."),
            (["sediment", "bland"], 2, "Bland sediment supports a podocytopathy."),
            (["biopsy", "podocyteEffacement"], 5, "Diffuse foot-process effacement is the key biopsy clue."),
            (["sediment", "casts"], -2, "RBC casts make isolated minimal change disease less likely."),
            (["feature", "suddenOnset"], 2, "Rapid onset of nephrotic syndrome favors MCD over FSGS."),
            (["feature", "steroidResponsive"], 3, "Steroid responsiveness is a hallmark of MCD."),
            (["feature", "allergy"], 1, "MCD can be triggered by allergies, NSAIDs, or immunizations."),
            (["feature", "infection"], 1, "MCD can relapse after infections or allergic reactions."),
        ],
        "source_abbr": "KDIGO",
        "source_year": 2025,
        "source_title": "KDIGO 2025 Nephrotic Syndrome in Children Guideline",
    },
    "fsgs": {
        "name": "Focal segmental glomerulosclerosis",
        "base": 1,
        "rules": [
            (["proteinuria", "nephrotic"], 3, "FSGS can present with nephrotic-range proteinuria."),
            (["proteinuria", "subnephrotic"], 1, "Secondary FSGS may have subnephrotic proteinuria."),
            (["albumin", "low"], 1, "Hypoalbuminemia supports primary podocyte injury if severe."),
            (["sediment", "hematuria"], 1, "Microscopic hematuria can coexist."),
            (["biopsy", "segmentalSclerosis"], 6, "Segmental sclerosis is the defining pathologic clue."),
            (["biopsy", "podocyteEffacement"], 2, "Diffuse effacement supports a primary podocytopathy pattern."),
            (["feature", "diabetes"], 1, "Metabolic or adaptive stress can contribute to secondary sclerosis."),
            (["feature", "obesity"], 1, "Obesity-related glomerulopathy can present as secondary FSGS."),
            (["feature", "hiv"], 2, "HIV-associated nephropathy (HIVAN) is typically collapsing FSGS."),
            (["feature", "steroidResistant"], 2, "Steroid resistance is more common in FSGS than MCD."),
            (["feature", "slowProgression"], 1, "Primary FSGS typically has slower onset than MCD."),
            (["feature", "hypertension"], 1, "Hypertension is frequent in FSGS, especially secondary forms."),
        ],
        "source_abbr": "KDIGO",
        "source_year": 2021,
        "source_title": "KDIGO 2021 Glomerular Diseases Guideline",
    },
    "lupus": {
        "name": "Lupus nephritis",
        "base": 1,
        "rules": [
            (["feature", "sle"], 5, "Known or suspected SLE is a major context clue."),
            (["lab", "anaDsDna"], 4, "ANA or anti-dsDNA positivity supports lupus activity."),
            (["lab", "lowC3"], 2, "Complement consumption supports immune-complex disease."),
            (["lab", "lowC4"], 2, "Low C4 strengthens suspicion for lupus nephritis."),
            (["sediment", "casts"], 3, "RBC casts can indicate active proliferative lupus nephritis."),
            (["proteinuria", "nephrotic"], 2, "Heavy proteinuria can occur, including membranous lupus nephritis."),
            (["biopsy", "fullHouse"], 6, "Full-house immune deposits are a classic biopsy clue."),
            (["feature", "malarRash"], 2, "Malar rash or photosensitivity supports SLE diagnosis."),
            (["feature", "oralUlcers"], 1, "Oral ulcers are a common SLE manifestation."),
            (["feature", "arthritis"], 2, "Arthritis/arthralgia is present in >80% of SLE patients."),
            (["feature", "serositis"], 1, "Pleuritis or pericarditis can accompany lupus nephritis."),
            (["feature", "alopecia"], 1, "Alopecia is a common non-renal manifestation of SLE."),
            (["feature", "female"], 2, "SLE has a strong female predominance (F:M 9:1)."),
            (["feature", "antiphospholipid"], 1, "Antiphospholipid antibodies can coexist with lupus nephritis."),
        ],
        "source_abbr": "KDIGO",
        "source_year": 2024,
        "source_title": "KDIGO 2024 Lupus Nephritis Guideline",
    },
    "anca": {
        "name": "ANCA-associated pauci-immune GN",
        "base": 1,
        "rules": [
            (["egfrTrend", "rapidDecline"], 4, "Rapid eGFR decline raises concern for rapidly progressive GN."),
            (["sediment", "casts"], 4, "RBC casts support active necrotizing GN."),
            (["lab", "anca"], 5, "ANCA positivity strongly supports ANCA-associated vasculitis."),
            (["feature", "sinopulmonary"], 3, "ENT or pulmonary features fit systemic small-vessel vasculitis."),
            (["feature", "hemoptysis"], 4, "Hemoptysis may indicate pulmonary capillaritis."),
            (["biopsy", "crescents"], 5, "Crescents or necrosis support rapidly progressive GN."),
            (["feature", "skinPurpura"], 1, "Palpable purpura can accompany small-vessel vasculitis."),
            (["feature", "arthralgia"], 1, "Joint pain is a common constitutional symptom."),
            (["feature", "mononeuritis"], 2, "Mononeuritis multiplex is specific for vasculitis."),
            (["lab", "lowC3"], -1, "Complement is typically normal or elevated in AAV."),
            (["lab", "antiGbm"], -1, "Anti-GBM positivity suggests dual disease or alternative diagnosis."),
            (["feature", "mpaPattern"], 2, "Microscopic polyangiitis: renal-limited or renal+lung without ENT."),
            (["feature", "gpaPattern"], 2, "Granulomatosis with polyangiitis: ENT+lung+kidney triad."),
            (["egfrTrend", "rapidDecline"], 3, "Sustained rapid eGFR loss over weeks is typical of RPGN."),
        ],
        "source_abbr": "KDIGO",
        "source_year": 2024,
        "source_title": "KDIGO 2024 ANCA Vasculitis Guideline",
    },
    "antiGbm": {
        "name": "Anti-GBM disease",
        "base": 0,
        "rules": [
            (["lab", "antiGbm"], 7, "Anti-GBM antibodies strongly support anti-GBM disease."),
            (["feature", "hemoptysis"], 4, "Hemoptysis with GN suggests pulmonary-renal syndrome."),
            (["egfrTrend", "rapidDecline"], 4, "Rapid loss of kidney function is typical and urgent."),
            (["sediment", "casts"], 3, "RBC casts support active crescentic GN."),
            (["biopsy", "linearIgg"], 7, "Linear IgG staining is a defining biopsy clue."),
            (["biopsy", "crescents"], 4, "Crescents support severe rapidly progressive GN."),
            (["lab", "anca"], 2, "ANCA positivity (dual anti-GBM/ANCA) occurs in 10-30% of cases."),
            (["feature", "smoking"], 1, "Smoking increases risk of pulmonary hemorrhage in anti-GBM."),
            (["feature", "oliguria"], 2, "Oliguric renal failure at presentation carries poor prognosis."),
            (["egfrTrend", "rapidDecline"], 3, "Dialysis requirement at presentation is common in severe anti-GBM."),
        ],
        "source_abbr": "KDIGO",
        "source_year": 2021,
        "source_title": "KDIGO 2021 Glomerular Diseases Guideline",
    },
    "infectionRelated": {
        "name": "Infection-related glomerulonephritis",
        "base": 1,
        "rules": [
            (["feature", "postInfectious"], 4, "A recent or ongoing infection is a key clinical clue."),
            (["lab", "lowC3"], 4, "Low C3 supports infection-related or complement-mediated GN."),
            (["lab", "lowC4"], 1, "Complement consumption can occur in immune-complex GN."),
            (["sediment", "casts"], 3, "RBC casts indicate active glomerulonephritis."),
            (["proteinuria", "subnephrotic"], 1, "Proteinuria is often present."),
            (["egfrTrend", "reduced"], 1, "Reduced eGFR can accompany active disease."),
            (["feature", "skinInfection"], 2, "Impetigo or skin infections can precede post-streptococcal GN."),
            (["feature", "pharyngitis"], 2, "Streptococcal pharyngitis 1-3 weeks before is classic."),
            (["feature", "scarletFever"], 2, "Scarlet fever history supports post-streptococcal GN."),
            (["ageGroup", "child"], 2, "Post-streptococcal GN is more common in children."),
            (["lab", "antiDnaseB"], 2, "Anti-DNase B positive more specific than ASOT for recent Strep."),
            (["lab", "asot"], 1, "ASOT elevation supports recent streptococcal infection."),
            (["feature", "staphylococcus"], 2, "Staphylococcal infection can cause IgA-dominant infection-related GN."),
        ],
        "source_abbr": "KDIGO",
        "source_year": 2021,
        "source_title": "KDIGO 2021 Glomerular Diseases Guideline",
    },
    "c3": {
        "name": "C3 glomerulopathy or complement-mediated GN",
        "base": 0,
        "rules": [
            (["lab", "lowC3"], 4, "Persistent low C3 raises complement-mediated disease."),
            (["lab", "lowC4"], -1, "Normal C4 with low C3 is more typical of alternative-pathway activation."),
            (["biopsy", "c3Dominant"], 7, "C3-dominant deposits are the central biopsy clue."),
            (["sediment", "casts"], 2, "Active urinary sediment supports GN."),
            (["egfrTrend", "reduced"], 2, "Reduced kidney function can occur in complement-mediated GN."),
            (["lab", "c3nephriticFactor"], 4, "C3 nephritic factor positivity supports C3 glomerulonephritis."),
            (["lab", "cfhMutation"], 3, "CFH mutation or autoantibody points to complement dysregulation."),
            (["feature", "drusen"], 2, "Ocular drusen can accompany complement dysregulation (CFH mutation)."),
            (["feature", "lipodystrophy"], 2, "Partial lipodystrophy is associated with C3 glomerulonephritis."),
            (["biopsy", "denseDeposits"], 6, "Intramembranous dense deposits define DDD."),
            (["feature", "persistentProteinuria"], 1, "Persistent proteinuria despite treatment is common."),
        ],
        "source_abbr": "KDIGO",
        "source_year": 2021,
        "source_title": "KDIGO 2021 Glomerular Diseases Guideline",
    },
    "diabeticNephropathy": {
        "name": "Diabetic kidney disease / nephropathy",
        "base": 1,
        "rules": [
            (["feature", "diabetes"], 5, "Presence of diabetes (type 1 or 2) is the primary risk factor."),
            (["feature", "diabetesDuration"], 2, "Long-standing diabetes (≥10 years) with proteinuria suggests DKD."),
            (["feature", "retinopathy"], 3, "Diabetic retinopathy strongly correlates with DKD."),
            (["proteinuria", "subnephrotic"], 1, "Moderate albuminuria is the earliest sign of DKD."),
            (["proteinuria", "nephrotic"], 1, "Nephrotic-range proteinuria can occur in advanced DKD."),
            (["egfrTrend", "reduced"], 1, "Gradual eGFR decline over years is typical."),
            (["feature", "hypertension"], 1, "Hypertension commonly accompanies DKD."),
            (["feature", "neuropathy"], 1, "Peripheral neuropathy supports long-standing diabetes complications."),
            (["sediment", "bland"], 1, "Bland sediment is typical of DKD (no active cellular casts)."),
        ],
        "source_abbr": "KDIGO",
        "source_year": 2024,
        "source_title": "KDIGO 2024 Diabetes Management in CKD Guideline",
    },
    "hypertensiveNephrosclerosis": {
        "name": "Hypertensive nephrosclerosis",
        "base": 1,
        "rules": [
            (["feature", "hypertension"], 4, "Long-standing hypertension is the primary risk factor."),
            (["feature", "hypertensionDuration"], 2, "Duration of hypertension correlates with renal injury."),
            (["proteinuria", "subnephrotic"], 1, "Modest proteinuria (<1.5g/day) is typical."),
            (["proteinuria", "nephrotic"], -2, "Nephrotic-range proteinuria is NOT typical."),
            (["sediment", "bland"], 2, "Bland sediment without active cells or casts."),
            (["egfrTrend", "reduced"], 1, "Slow gradual eGFR decline parallels vascular disease."),
            (["feature", "leftVentricularHypertrophy"], 1, "LVH supports chronic hypertensive end-organ damage."),
            (["feature", "retinopathy"], 1, "Hypertensive retinopathy supports chronic hypertension."),
            (["ageGroup", "adult"], 1, "More common in older adults (>50 years)."),
            (["feature", "africanAncestry"], 1, "More common and aggressive in African ancestry."),
        ],
        "source_abbr": "KDIGO",
        "source_year": 2021,
        "source_title": "KDIGO 2021 Blood Pressure in CKD Guideline",
    },
    "acuteInterstitialNephritis": {
        "name": "Acute interstitial nephritis",
        "base": 0,
        "rules": [
            (["feature", "drugExposure"], 4, "Drug-induced AIN is the most common cause (NSAIDs, antibiotics, PPIs)."),
            (["feature", "rash"], 2, "Classic triad: fever, rash, eosinophilia (present in <30% of cases)."),
            (["feature", "fever"], 2, "Fever within days-weeks of drug exposure is suspicious."),
            (["feature", "arthralgia"], 1, "Arthralgia can accompany drug-induced AIN."),
            (["egfrTrend", "rapidDecline"], 2, "Acute kidney injury develops over days to weeks."),
            (["sediment", "hematuria"], 1, "Microscopic hematuria is common."),
            (["lab", "eosinophilia"], 2, "Eosinophilia or eosinophiluria supports AIN."),
            (["feature", "nsaidExposure"], 3, "NSAID-induced AIN can occur after months to years of use."),
            (["feature", "antibioticExposure"], 3, "Beta-lactams, rifampin, TMP/SMX, fluoroquinolones are common causes."),
            (["feature", "ppiExposure"], 2, "PPI-associated AIN often has insidious onset; increasing recognition."),
            (["sediment", "bland"], 1, "White cell casts can be seen but often absent."),
            (["feature", "flankPain"], 1, "Bilateral flank pain can occur due to renal capsule distension."),
        ],
        "source_abbr": "KDIGO",
        "source_year": 2021,
        "source_title": "KDIGO 2021 AKI Guideline",
    },
    "acuteTubularNecrosis": {
        "name": "Acute tubular necrosis (ischemic/nephrotoxic)",
        "base": 0,
        "rules": [
            (["feature", "ischemia"], 4, "Prolonged hypotension, sepsis, or major surgery suggests ischemic ATN."),
            (["feature", "nephrotoxin"], 3, "Aminoglycosides, contrast, cisplatin, pigmented urine suggest nephrotoxic ATN."),
            (["egfrTrend", "rapidDecline"], 3, "Acute rise in creatinine over hours-days."),
            (["sediment", "muddyBrown"], 3, "Muddy brown granular casts are characteristic."),
            (["feature", "oliguria"], 2, "Oliguric or anuric phase is common in severe ATN."),
            (["feature", "fluidOverload"], 1, "Volume overload can complicate oliguric ATN."),
            (["feature", "hyperkalemia"], 1, "Hyperkalemia is common due to reduced renal excretion."),
            (["proteinuria", "subnephrotic"], 1, "Mild proteinuria may be present."),
            (["feature", "contrastExposure"], 2, "Contrast-induced nephropathy typically 24-48h post exposure."),
            (["feature", "rhabdomyolysis"], 3, "Pigment-induced ATN from myoglobin: dark urine, elevated CK."),
        ],
        "source_abbr": "KDIGO",
        "source_year": 2021,
        "source_title": "KDIGO 2021 AKI Guideline",
    },
    "thromboticMicroangiopathy": {
        "name": "Thrombotic microangiopathy (TMA)",
        "base": 0,
        "rules": [
            (["feature", "microangiopathicHemolyticAnemia"], 5, "MAHA (schistocytes, low haptoglobin, elevated LDH) is a hallmark."),
            (["feature", "thrombocytopenia"], 4, "Thrombocytopenia is part of the TMA diagnostic triad."),
            (["feature", "neurologicSymptoms"], 3, "Neurologic involvement (confusion, seizures, focal deficits) suggests TTP."),
            (["feature", "fever"], 2, "Fever is classically part of the TTP pentad."),
            (["feature", "renalFailure"], 3, "Acute kidney injury is prominent in aHUS and STEC-HUS."),
            (["egfrTrend", "rapidDecline"], 2, "Renal function often deteriorates rapidly."),
            (["lab", "adams13"], 4, "Severely decreased ADAMTS13 activity (<10%) confirms TTP."),
            (["feature", "diarrhea"], 2, "Bloody diarrhea precedes STEC-HUS (especially in children)."),
            (["feature", "complementMutation"], 3, "Complement gene mutation or autoantibody supports aHUS."),
            (["biopsy", "tmLesions"], 4, "Arteriolar and glomerular microthrombi are diagnostic."),
            (["feature", "drugInduced"], 2, "CNIs, VEGF inhibitors, quinine, chemotherapy can cause secondary TMA."),
            (["feature", "malignantHypertension"], 2, "Severe hypertension can cause or complicate TMA."),
        ],
        "source_abbr": "KDIGO",
        "source_year": 2021,
        "source_title": "KDIGO 2021 Glomerular Diseases Guideline",
    },
    "lightChainCastNephropathy": {
        "name": "Light chain cast nephropathy (myeloma kidney)",
        "base": 0,
        "rules": [
            (["feature", "multipleMyeloma"], 5, "Known or suspected multiple myeloma is the primary context."),
            (["feature", "hypercalcemia"], 2, "Hypercalcemia is common in myeloma and contributes to AKI."),
            (["feature", "anemia"], 2, "Anemia out of proportion to CKD is typical."),
            (["egfrTrend", "rapidDecline"], 2, "Acute or subacute renal failure is common."),
            (["proteinuria", "subnephrotic"], 1, "Proteinuria is often minimal (<1g/day), mostly Bence Jones."),
            (["sediment", "bland"], 1, "Urine sediment is typically bland."),
            (["lab", "freeLightChains"], 4, "Elevated serum free light chains with abnormal ratio are diagnostic."),
            (["lab", "serumProteinElectrophoresis"], 3, "Monoclonal spike on SPEP supports myeloma."),
            (["ageGroup", "adult"], 2, "Multiple myeloma is a disease of older adults (>60 years)."),
            (["feature", "bonePain"], 2, "Bone pain or lytic lesions support myeloma diagnosis."),
        ],
        "source_abbr": "KDIGO",
        "source_year": 2021,
        "source_title": "KDIGO 2021 Glomerular Diseases Guideline",
    },
    "fibrillaryGlomerulonephritis": {
        "name": "Fibrillary glomerulonephritis / immunotactoid glomerulopathy",
        "base": 0,
        "rules": [
            (["proteinuria", "nephrotic"], 2, "Nephrotic-range proteinuria is present in ~50% of cases."),
            (["proteinuria", "subnephrotic"], 1, "Subnephrotic proteinuria can occur."),
            (["sediment", "hematuria"], 2, "Microscopic hematuria is common."),
            (["sediment", "casts"], 1, "RBC casts can be present."),
            (["egfrTrend", "reduced"], 1, "Renal function is often impaired at diagnosis."),
            (["feature", "malignancy"], 2, "Associated with malignancies (especially lymphoproliferative) in ~30%."),
            (["feature", "autoimmune"], 1, "Associated with autoimmune conditions (SLE, RA, Crohn's)."),
            (["feature", "hepatitisC"], 1, "HCV infection can be associated with cryoglobulinemic GN."),
            (["biopsy", "fibrillaryDeposits"], 5, "Randomly oriented fibrils ~20nm distinguish fibrillary GN."),
            (["biopsy", "immunotactoid"], 4, "Microtubular deposits >30nm suggest immunotactoid glomerulopathy."),
        ],
        "source_abbr": "KDIGO",
        "source_year": 2021,
        "source_title": "KDIGO 2021 Glomerular Diseases Guideline",
    },
    "amyloidosis": {
        "name": "Renal amyloidosis",
        "base": 0,
        "rules": [
            (["proteinuria", "nephrotic"], 3, "Nephrotic-range proteinuria is common."),
            (["albumin", "low"], 2, "Severe hypoalbuminemia is typical."),
            (["sediment", "bland"], 1, "Bland sediment without active cells."),
            (["feature", "cardiacInvolvement"], 2, "Cardiac amyloid (HFpEF, arrhythmia, low voltage ECG) supports AL."),
            (["feature", "hepatomegaly"], 1, "Hepatomegaly can occur in systemic amyloidosis."),
            (["feature", "neuropathy"], 1, "Peripheral or autonomic neuropathy supports amyloid."),
            (["feature", "macroglossia"], 3, "Macroglossia is specific (though rare) for AL amyloid."),
            (["lab", "freeLightChains"], 3, "Abnormal FLC ratio supports AL amyloidosis."),
            (["lab", "serumProteinElectrophoresis"], 2, "Monoclonal protein in serum/urine supports AL."),
            (["feature", "chronicInflammation"], 2, "Chronic inflammatory conditions predispose to AA amyloidosis."),
            (["ageGroup", "adult"], 2, "Amyloidosis is more common in older adults."),
            (["biopsy", "congoRedPositive"], 5, "Congo red positive deposits with apple-green birefringence."),
            (["feature", "ecchymoses"], 1, "Periorbital ecchymoses (raccoon eyes) can occur in AL amyloid."),
        ],
        "source_abbr": "KDIGO",
        "source_year": 2021,
        "source_title": "KDIGO 2021 Glomerular Diseases Guideline",
    },
    "diabeticNephropathyWithGN": {
        "name": "Diabetic kidney disease with superimposed GN",
        "base": 1,
        "rules": [
            (["feature", "diabetes"], 3, "Diabetes is present."),
            (["feature", "retinopathy"], 1, "Background retinopathy supports diabetic kidney disease."),
            (["sediment", "casts"], 3, "Active sediment (RBC casts) suggests superimposed GN."),
            (["sediment", "hematuria"], 2, "New or worsening hematuria suggests GN rather than pure DKD."),
            (["egfrTrend", "rapidDecline"], 3, "Rapid decline is NOT typical of DKD alone - suggests GN."),
            (["proteinuria", "nephrotic"], 2, "Worsening proteinuria beyond DKD baseline suggests GN."),
            (["feature", "systemicSymptoms"], 2, "Constitutional symptoms suggest GN or vasculitis."),
            (["lab", "anca"], 2, "ANCA positivity suggests pauci-immune GN superimposed on DKD."),
            (["lab", "antiGbm"], 2, "Anti-GBM positivity suggests dual disease."),
            (["feature", "hemoptysis"], 2, "Pulmonary-renal syndrome can occur with DKD as comorbid condition."),
        ],
        "source_abbr": "KDIGO",
        "source_year": 2024,
        "source_title": "KDIGO 2024 Diabetes Management in CKD Guideline",
    },
    "mpgn": {
        "name": "Membranoproliferative glomerulonephritis",
        "base": 1,
        "rules": [
            (["proteinuria", "nephrotic"], 2, "Nephrotic-range proteinuria can occur in MPGN."),
            (["proteinuria", "subnephrotic"], 1, "Subnephrotic proteinuria is common in MPGN."),
            (["sediment", "hematuria"], 2, "Microscopic hematuria is a common finding."),
            (["sediment", "casts"], 2, "RBC casts indicate active glomerular inflammation."),
            (["lab", "lowC3"], 4, "Low C3 is a hallmark of complement-mediated MPGN."),
            (["lab", "lowC4"], 2, "Low C4 supports immune-complex-mediated MPGN."),
            (["biopsy", "mesangialProliferation"], 5, "Mesangial proliferation is a key histologic feature."),
            (["biopsy", "subendothelialDeposits"], 6, "Subendothelial deposits on electron microscopy define MPGN."),
            (["biopsy", "tramTrack"], 5, "Double-contour (tram-track) capillary wall thickening is characteristic."),
            (["feature", "hepatitisC"], 2, "HCV infection is a major cause of immune-complex MPGN."),
            (["feature", "autoimmune"], 2, "Autoimmune diseases (SLE, Sjogren's) can cause MPGN."),
            (["feature", "edema"], 1, "Edema is common with nephrotic-range proteinuria."),
            (["feature", "hypertension"], 1, "Hypertension is common in MPGN."),
            (["ageGroup", "adult"], 1, "MPGN can occur at any age but peak incidence is in adults."),
        ],
        "source_abbr": "KDIGO",
        "source_year": 2021,
        "source_title": "KDIGO 2021 Glomerular Diseases Guideline",
    },
    "denseDepositDisease": {
        "name": "Dense deposit disease (membranoproliferative GN type II)",
        "base": 0,
        "rules": [
            (["lab", "lowC3"], 5, "Persistent low C3 is the hallmark of dense deposit disease."),
            (["lab", "normalC4"], 3, "Normal C4 with low C3 indicates alternative complement pathway activation."),
            (["lab", "c3nephriticFactor"], 4, "C3 nephritic factor stabilizes C3 convertase, causing persistent low C3."),
            (["biopsy", "denseDeposits"], 7, "Dense ribbon-like intramembranous deposits on electron microscopy are diagnostic."),
            (["biopsy", "mpgnPattern"], 3, "MPGN pattern on light microscopy is typical."),
            (["proteinuria", "nephrotic"], 2, "Nephrotic-range proteinuria can occur."),
            (["proteinuria", "subnephrotic"], 1, "Subnephrotic proteinuria is common."),
            (["sediment", "hematuria"], 1, "Microscopic hematuria may be present."),
            (["ageGroup", "child"], 2, "DDD typically presents in children or young adults."),
            (["feature", "lipodystrophy"], 2, "Partial lipodystrophy is associated with alternative pathway complement dysregulation."),
            (["egfrTrend", "reduced"], 1, "Progressive renal impairment is common."),
        ],
        "source_abbr": "KDIGO",
        "source_year": 2021,
        "source_title": "KDIGO 2021 Glomerular Diseases Guideline",
    },
    "mgrs": {
        "name": "Monoclonal gammopathy of renal significance",
        "base": 0,
        "rules": [
            (["lab", "monoclonalGammopathy"], 5, "A monoclonal protein (M-spike or FLC abnormality) is the defining feature."),
            (["lab", "freeLightChains"], 4, "Abnormal serum free light chain ratio supports MGRS."),
            (["ageGroup", "adult"], 2, "MGRS typically affects older adults (>50 years)."),
            (["proteinuria", "subnephrotic"], 2, "Subnephrotic proteinuria is the most common presentation."),
            (["proteinuria", "nephrotic"], 1, "Nephrotic-range proteinuria can occur in amyloid or cast nephropathy."),
            (["biopsy", "monoclonalDeposits"], 6, "Monoclonal immunoglobulin deposits on kidney biopsy confirm MGRS."),
            (["feature", "hematologicEvaluation"], 3, "Hematologic evaluation is required to characterize the clone."),
            (["egfrTrend", "reduced"], 1, "CKD at presentation is common in MGRS."),
            (["sediment", "hematuria"], 1, "Microscopic hematuria may be present depending on lesion type."),
            (["biopsy", "lightChainRestriction"], 5, "Kappa or lambda light chain restriction on biopsy confirms monoclonality."),
            (["feature", "bonePain"], -2, "Bone pain or lytic lesions suggest multiple myeloma rather than MGRS."),
            (["lab", "hypercalcemia"], -2, "Hypercalcemia suggests myeloma rather than MGRS."),
        ],
        "source_abbr": "KDIGO",
        "source_year": 2021,
        "source_title": "KDIGO 2021 Glomerular Diseases Guideline",
    },
    "cryoglobulinemic": {
        "name": "Cryoglobulinemic glomerulonephritis",
        "base": 0,
        "rules": [
            (["feature", "palpablePurpura"], 4, "Palpable purpura (leukocytoclastic vasculitis) is a classic finding."),
            (["feature", "arthralgia"], 2, "Arthralgia is a common systemic manifestation."),
            (["lab", "hepatitisC"], 5, "HCV infection is the most common cause of cryoglobulinemic GN."),
            (["lab", "lowC4"], 5, "Very low C4 (often undetectable) is a hallmark of cryoglobulinemia."),
            (["lab", "rheumatoidFactor"], 3, "Positive rheumatoid factor (IgM anti-IgG) supports cryoglobulinemia."),
            (["proteinuria", "nephrotic"], 1, "Nephrotic-range proteinuria can occur."),
            (["sediment", "hematuria"], 2, "Microscopic hematuria is common."),
            (["sediment", "casts"], 2, "RBC casts indicate active glomerulonephritis."),
            (["biopsy", "intraluminalThrombi"], 5, "Intraluminal cryoglobulin thrombi are a characteristic biopsy finding."),
            (["feature", "peripheralNeuropathy"], 2, "Peripheral neuropathy is a common extrarenal manifestation."),
            (["feature", "raynaud"], 1, "Raynaud phenomenon can occur with cryoglobulinemia."),
            (["feature", "skinUlcers"], 1, "Cutaneous ulcers can occur in severe cryoglobulinemic vasculitis."),
        ],
        "source_abbr": "KDIGO",
        "source_year": 2021,
        "source_title": "KDIGO 2021 Glomerular Diseases Guideline",
    },
    "immunotactoid": {
        "name": "Immunotactoid glomerulopathy",
        "base": 0,
        "rules": [
            (["proteinuria", "nephrotic"], 2, "Nephrotic-range proteinuria is common at presentation."),
            (["proteinuria", "subnephrotic"], 1, "Subnephrotic proteinuria can occur."),
            (["sediment", "hematuria"], 2, "Microscopic hematuria is frequent."),
            (["biopsy", "microtubularDeposits"], 7, "Organized microtubular deposits >30nm diameter define immunotactoid glomerulopathy."),
            (["lab", "monoclonalGammopathy"], 3, "Monoclonal gammopathy is associated in ~50-70% of cases."),
            (["feature", "autoimmune"], 2, "Autoimmune conditions (Sjogren's, SLE) can be associated."),
            (["feature", "malignancy"], 2, "Hematologic malignancy (CLL, lymphoma) may be associated."),
            (["egfrTrend", "reduced"], 1, "CKD at presentation is common."),
            (["sediment", "casts"], 1, "RBC casts can be present with active inflammation."),
            (["ageGroup", "adult"], 1, "Immunotactoid glomerulopathy typically affects adults."),
        ],
        "source_abbr": "KDIGO",
        "source_year": 2021,
        "source_title": "KDIGO 2021 Glomerular Diseases Guideline",
    },
    "alport": {
        "name": "Alport syndrome",
        "base": 0,
        "rules": [
            (["sediment", "hematuria"], 5, "Persistent microscopic hematuria is the hallmark feature, often from birth."),
            (["feature", "familyHistoryHematuria"], 4, "Family history of hematuria or ESRD suggests hereditary nephritis."),
            (["feature", "hearingLoss"], 4, "Sensorineural hearing loss is a classic extrarenal manifestation."),
            (["feature", "ocularAbnormalities"], 3, "Anterior lenticonus and retinal flecks are characteristic ocular findings."),
            (["biopsy", "thinGbm"], 5, "Thinning of glomerular basement membrane on electron microscopy."),
            (["feature", "xlInheritance"], 3, "X-linked inheritance pattern (COL4A5) is most common form."),
            (["feature", "arInheritance"], 2, "Autosomal recessive inheritance (COL4A3/COL4A4) causes severe early disease."),
            (["proteinuria", "subnephrotic"], 2, "Proteinuria often increases with age as disease progresses."),
            (["egfrTrend", "reduced"], 3, "Progressive eGFR decline to ESRD is the natural history."),
            (["genetic", "col4aMutation"], 6, "COL4A5, COL4A3, or COL4A4 mutation on genetic testing is diagnostic."),
            (["ageGroup", "child"], 2, "Presentation in childhood with hematuria is typical for X-linked form."),
        ],
        "source_abbr": "KDIGO",
        "source_year": 2021,
        "source_title": "KDIGO 2021 Glomerular Diseases Guideline",
    },
    "thinBasementMembrane": {
        "name": "Thin basement membrane nephropathy",
        "base": 0,
        "rules": [
            (["sediment", "hematuria"], 4, "Persistent microscopic hematuria is the primary finding."),
            (["feature", "familyHistoryHematuria"], 3, "Family history of benign hematuria is common (autosomal dominant)."),
            (["egfrTrend", "reduced"], -2, "Renal function is typically normal; CKD is unusual."),
            (["proteinuria", "subnephrotic"], 1, "Minimal proteinuria (<500 mg/day) is typical."),
            (["biopsy", "thinGbm"], 5, "Diffuse thinning of GBM (<250 nm) on electron microscopy."),
            (["feature", "noHearingLoss"], 3, "Absence of hearing loss differentiates from Alport syndrome."),
            (["feature", "noOcularAbnormalities"], 2, "No ocular abnormalities helps distinguish from Alport syndrome."),
            (["feature", "adInheritance"], 2, "Autosomal dominant inheritance pattern (COL4A3/A4 heterozygous)."),
            (["genetic", "col4aCarrier"], 2, "Carrier of COL4A3/A4 heterozygous mutation."),
        ],
        "source_abbr": "KDIGO",
        "source_year": 2021,
        "source_title": "KDIGO 2021 Glomerular Diseases Guideline",
    },
    "cfhr": {
        "name": "CFHR-related disease",
        "base": 0,
        "rules": [
            (["lab", "lowC3"], 4, "Low C3 level is characteristic of complement-mediated disease."),
            (["lab", "normalC4"], 2, "Normal C4 with low C3 suggests alternative pathway activation."),
            (["biopsy", "mpgnPattern"], 3, "MPGN pattern on light microscopy is a common histologic finding."),
            (["biopsy", "c3Dominant"], 4, "C3-dominant deposits on immunofluorescence."),
            (["genetic", "cfhrMutation"], 6, "CFHR gene mutation or rearrangement is diagnostic."),
            (["feature", "familyHistoryComplement"], 2, "Family history of complement-mediated kidney disease."),
            (["proteinuria", "nephrotic"], 2, "Nephrotic-range proteinuria can occur."),
            (["sediment", "hematuria"], 1, "Microscopic hematuria may be present."),
            (["ageGroup", "child"], 1, "Age of onset is variable, can present in childhood."),
            (["egfrTrend", "reduced"], 1, "Progressive renal impairment is common."),
        ],
        "source_abbr": "KDIGO",
        "source_year": 2021,
        "source_title": "KDIGO 2021 Glomerular Diseases Guideline",
    },
    "fabry": {
        "name": "Fabry disease",
        "base": 0,
        "rules": [
            (["proteinuria", "subnephrotic"], 2, "Subnephrotic proteinuria is typical early; nephrotic-range develops later."),
            (["sediment", "hematuria"], 1, "Microscopic hematuria may be present."),
            (["feature", "acroparesthesias"], 4, "Neuropathic pain (burning hands/feet) is a classic early symptom."),
            (["feature", "angiokeratomas"], 3, "Angiokeratomas (dark red-purple skin lesions) are characteristic."),
            (["feature", "corneaVerticillata"], 3, "Cornea verticillata (whorl-like corneal deposits) on slit-lamp exam."),
            (["feature", "familyHistoryXlinked"], 2, "X-linked family pattern with variable female expression."),
            (["lab", "alphaGalA"], 6, "Low alpha-galactosidase A activity is diagnostic in males."),
            (["biopsy", "gb3Deposits"], 5, "Gb3 (globotriaosylceramide) accumulation with zebra bodies on EM."),
            (["feature", "leftVentricularHypertrophy"], 2, "Left ventricular hypertrophy from glycolipid cardiac deposition."),
            (["genetic", "glAaMutation"], 5, "GLA gene mutation confirms Fabry disease."),
        ],
        "source_abbr": "KDIGO",
        "source_year": 2021,
        "source_title": "KDIGO 2021 Glomerular Diseases Guideline",
    },
    "hbvAssociatedGN": {
        "name": "HBV-associated glomerulonephritis",
        "base": 0,
        "rules": [
            (["lab", "hbsAgPositive"], 6, "HBsAg positivity is required for diagnosis."),
            (["proteinuria", "nephrotic"], 3, "Nephrotic-range proteinuria is the most common presentation."),
            (["biopsy", "membranous"], 4, "Membranous pattern is the most common histologic lesion."),
            (["ageGroup", "child"], 2, "Children in endemic areas are disproportionately affected."),
            (["lab", "elevatedLiverEnzymes"], 2, "Elevated liver enzymes suggest active hepatitis."),
            (["lab", "hbeAgPositive"], 2, "HBeAg positivity and high viral load support active disease."),
            (["biopsy", "subepithelialDeposits"], 3, "Subepithelial deposits with spikes on EM."),
            (["feature", "arthralgia"], 1, "Arthralgia or rash can accompany HBV-associated GN."),
            (["feature", "asianOrAfrican"], 1, "Higher prevalence in Asia and sub-Saharan Africa."),
            (["feature", "hepatitis"], 2, "Clinical hepatitis may precede or accompany renal disease."),
        ],
        "source_abbr": "KDIGO",
        "source_year": 2021,
        "source_title": "KDIGO 2021 Glomerular Diseases Guideline",
    },
    "hcvAssociatedGN": {
        "name": "HCV-associated glomerulonephritis",
        "base": 0,
        "rules": [
            (["lab", "hcvRnaPositive"], 6, "HCV RNA positivity is required for diagnosis."),
            (["feature", "cryoglobulinemia"], 5, "Mixed cryoglobulinemia is the classic systemic manifestation."),
            (["proteinuria", "nephrotic"], 2, "Proteinuria is common."),
            (["sediment", "hematuria"], 2, "Hematuria is common with active glomerulonephritis."),
            (["lab", "lowC4"], 5, "Very low C4 (often undetectable) is characteristic of cryoglobulinemia."),
            (["biopsy", "mpgnPattern"], 4, "Membranoproliferative pattern is the most common histology."),
            (["biopsy", "intraluminalThrombi"], 3, "Intraluminal cryoglobulin thrombi on biopsy."),
            (["lab", "rheumatoidFactor"], 3, "Rheumatoid factor positive (IgM anti-IgG)."),
            (["feature", "palpablePurpura"], 3, "Palpable purpura from leukocytoclastic vasculitis."),
            (["feature", "peripheralNeuropathy"], 2, "Peripheral neuropathy is common in cryoglobulinemia."),
        ],
        "source_abbr": "KDIGO",
        "source_year": 2021,
        "source_title": "KDIGO 2021 Glomerular Diseases Guideline",
    },
    "igg4Related": {
        "name": "IgG4-related kidney disease",
        "base": 0,
        "rules": [
            (["biopsy", "tubulointerstitialNephritis"], 4, "Tubulointerstitial nephritis is the most common renal pattern."),
            (["lab", "elevatedIgG4"], 5, "Elevated serum IgG4 levels (>135 mg/dL) support diagnosis."),
            (["biopsy", "igg4PlasmaCells"], 6, "IgG4-positive plasma cell infiltrate (>10/HPF or IgG4/IgG ratio >40%)."),
            (["biopsy", "storiformFibrosis"], 5, "Storiform (cartwheel) fibrosis is characteristic."),
            (["feature", "otherOrganInvolvement"], 3, "Pancreatitis, sialadenitis, retroperitoneal fibrosis support diagnosis."),
            (["lab", "hypocomplementemia"], 2, "Low C3/C4 can occur in IgG4-related disease."),
            (["proteinuria", "subnephrotic"], 2, "Subnephrotic proteinuria is typical."),
            (["egfrTrend", "reduced"], 2, "CKD at presentation is common."),
            (["feature", "male"], 1, "Male predominance (M:F 3:1)."),
            (["ageGroup", "adult"], 1, "Typically affects adults >50 years."),
        ],
        "source_abbr": "KDIGO",
        "source_year": 2021,
        "source_title": "KDIGO 2021 Glomerular Diseases Guideline",
    },
    "paraneoplastic": {
        "name": "Paraneoplastic glomerulonephritis",
        "base": 0,
        "rules": [
            (["feature", "knownMalignancy"], 5, "Known or newly discovered malignancy is the primary context."),
            (["biopsy", "membranous"], 4, "Membranous pattern is the most common histologic lesion."),
            (["ageGroup", "adult"], 2, "Typically affects older adults (>60 years)."),
            (["proteinuria", "nephrotic"], 3, "Nephrotic-range proteinuria is typical."),
            (["sediment", "hematuria"], 1, "Hematuria may be present."),
            (["feature", "malignancyTiming"], 3, "Malignancy within 2 years of renal presentation supports association."),
            (["biopsy", "tumorAntigens"], 4, "Tumor antigens identified in immune deposits on biopsy."),
            (["feature", "resolutionWithTreatment"], 3, "Renal improvement with successful cancer treatment."),
            (["feature", "solidTumor"], 2, "Solid tumors (lung, colon, breast, kidney) are most commonly associated."),
            (["feature", "lymphoproliferative"], 2, "Lymphoproliferative disorders can also cause paraneoplastic GN."),
        ],
        "source_abbr": "KDIGO",
        "source_year": 2021,
        "source_title": "KDIGO 2021 Glomerular Diseases Guideline",
    },
    "sarcoidosisAssociatedGN": {
        "name": "Sarcoidosis-associated glomerulonephritis",
        "base": 0,
        "rules": [
            (["feature", "knownSarcoidosis"], 5, "Known or suspected sarcoidosis is the primary context."),
            (["biopsy", "granulomatousTIN"], 4, "Granulomatous tubulointerstitial nephritis is a classic pattern."),
            (["lab", "elevatedACE"], 3, "Elevated serum ACE level supports active sarcoidosis."),
            (["lab", "elevatedLysozyme"], 2, "Elevated lysozyme can support sarcoidosis diagnosis."),
            (["proteinuria", "subnephrotic"], 2, "Subnephrotic proteinuria is typical."),
            (["sediment", "hematuria"], 1, "Hematuria may be present."),
            (["feature", "hypercalcemia"], 2, "Hypercalcemia or hypercalciuria from 1,25(OH)2D production."),
            (["egfrTrend", "reduced"], 2, "CKD stage varies at presentation."),
            (["feature", "pulmonaryInvolvement"], 3, "Bilateral hilar lymphadenopathy or pulmonary infiltrates."),
            (["feature", "skinLesions"], 2, "Erythema nodosum or cutaneous sarcoidosis."),
            (["feature", "uveitis"], 2, "Uveitis or other ocular involvement."),
        ],
        "source_abbr": "KDIGO",
        "source_year": 2021,
        "source_title": "KDIGO 2021 Glomerular Diseases Guideline",
    },
    "recurrentIgaNephropathy": {
        "name": "Recurrent IgA nephropathy in transplant",
        "base": 0,
        "rules": [
            (["feature", "originalDiseaseIgaNephropathy"], 5, "Original native kidney disease was IgA nephropathy."),
            (["sediment", "hematuria"], 3, "Hematuria post-transplant raises concern for recurrence."),
            (["proteinuria", "subnephrotic"], 2, "Proteinuria post-transplant may indicate recurrence."),
            (["biopsy", "mesangialIga"], 6, "Mesangial IgA deposits on allograft biopsy confirm recurrence."),
            (["feature", "recurrenceTiming"], 2, "Recurrence typically occurs months to years post-transplant."),
            (["feature", "livingDonor"], 1, "Living donor transplantation may carry slightly higher recurrence risk."),
            (["biopsy", "crescents"], 2, "Crescents on allograft biopsy indicate aggressive recurrent disease."),
            (["egfrTrend", "reduced"], 2, "eGFR decline may indicate recurrent IgA nephropathy."),
        ],
        "source_abbr": "KDIGO",
        "source_year": 2021,
        "source_title": "KDIGO 2021 Glomerular Diseases Guideline",
    },
    "recurrentFSGS": {
        "name": "Recurrent FSGS in transplant",
        "base": 0,
        "rules": [
            (["feature", "originalDiseaseFsgs"], 5, "Original native kidney disease was FSGS."),
            (["proteinuria", "nephrotic"], 6, "Sudden nephrotic-range proteinuria post-transplant is the hallmark."),
            (["egfrTrend", "rapidDecline"], 3, "Rapid eGFR decline can occur with aggressive recurrence."),
            (["proteinuria", "subnephrotic"], 1, "Subnephrotic proteinuria may be early recurrence."),
            (["biopsy", "podocyteEffacement"], 4, "Diffuse podocyte effacement on EM supports recurrence."),
            (["feature", "circulatingFactor"], 3, "Circulating permeability factor suspected in pathogenesis."),
            (["feature", "plasmapheresisResponse"], 4, "Response to plasmapheresis supports diagnosis of recurrent FSGS."),
            (["feature", "rapidProgression"], 2, "Native kidney FSGS with rapid progression increases recurrence risk."),
        ],
        "source_abbr": "KDIGO",
        "source_year": 2021,
        "source_title": "KDIGO 2021 Glomerular Diseases Guideline",
    },
    "recurrentMembranous": {
        "name": "Recurrent membranous nephropathy in transplant",
        "base": 0,
        "rules": [
            (["feature", "originalDiseaseMembranous"], 5, "Original native kidney disease was membranous nephropathy."),
            (["proteinuria", "nephrotic"], 3, "Proteinuria post-transplant may indicate recurrence."),
            (["lab", "pla2r"], 4, "PLA2R antibodies detectable post-transplant."),
            (["biopsy", "subepithelialDeposits"], 5, "Subepithelial deposits on allograft biopsy confirm recurrence."),
            (["feature", "slowerOnset"], 1, "Onset is typically slower than recurrent FSGS."),
            (["egfrTrend", "reduced"], 2, "eGFR decline is variable depending on severity."),
            (["feature", "dsaControversial"], 1, "Association with donor-specific antibodies is controversial."),
        ],
        "source_abbr": "KDIGO",
        "source_year": 2021,
        "source_title": "KDIGO 2021 Glomerular Diseases Guideline",
    },
    "transplantGlomerulopathy": {
        "name": "Transplant glomerulopathy",
        "base": 0,
        "rules": [
            (["proteinuria", "nephrotic"], 3, "Proteinuria is a common presenting finding."),
            (["egfrTrend", "reduced"], 3, "Slowly progressive eGFR decline is typical."),
            (["biopsy", "doubleContour"], 5, "Double contours (tram-tracking) of GBM on EM."),
            (["biopsy", "c4dStaining"], 4, "C4d staining on biopsy indicates chronic AMR."),
            (["lab", "dsaPositive"], 5, "Donor-specific antibodies (DSA) are often positive."),
            (["feature", "priorAcuteRejection"], 2, "History of prior acute rejection episodes."),
            (["biopsy", "gbmLamellation"], 3, "Lamellation of GBM on electron microscopy."),
            (["feature", "transplantAge"], 2, "Typically occurs >1 year post-transplant."),
        ],
        "source_abbr": "KDIGO",
        "source_year": 2021,
        "source_title": "KDIGO 2021 Glomerular Diseases Guideline",
    },
    "antibodyMediatedRejection": {
        "name": "Antibody-mediated rejection",
        "base": 0,
        "rules": [
            (["lab", "dsaPositive"], 6, "Donor-specific antibodies (DSA) positive is a key finding."),
            (["biopsy", "c4dStaining"], 5, "C4d positive on biopsy is a hallmark of AMR."),
            (["biopsy", "microvascularInflammation"], 4, "Peritubular capillaritis and glomerulitis."),
            (["egfrTrend", "rapidDecline"], 3, "Acute or subacute eGFR decline."),
            (["proteinuria", "subnephrotic"], 2, "Proteinuria may be present."),
            (["feature", "transplantTiming"], 2, "Typically occurs >1 month post-transplant."),
            (["feature", "priorSensitization"], 2, "Prior transfusion, pregnancy, or transplant increases risk."),
            (["feature", "antiHumoralResponse"], 3, "Response to anti-humoral therapy (IVIG, plasmapheresis, rituximab)."),
            (["feature", "graftDysfunction"], 2, "Graft dysfunction with tenderness possible."),
            (["biopsy", "endothelialitis"], 2, "Endothelial inflammation on biopsy."),
        ],
        "source_abbr": "KDIGO",
        "source_year": 2021,
        "source_title": "KDIGO 2021 Glomerular Diseases Guideline",
    },
    "tCellMediatedRejection": {
        "name": "T cell-mediated rejection",
        "base": 0,
        "rules": [
            (["egfrTrend", "rapidDecline"], 4, "Acute eGFR decline is the most common presentation."),
            (["feature", "transplantTiming"], 3, "Higher risk within first year post-transplant."),
            (["biopsy", "tubulitis"], 5, "Tubulitis (lymphocytes in tubular epithelium) is the key finding."),
            (["biopsy", "interstitialInfiltrate"], 4, "Interstitial mononuclear cell infiltrate."),
            (["feature", "graftTenderness"], 2, "Graft tenderness and fever (rare with current immunosuppression)."),
            (["lab", "dsaNegative"], 2, "DSA negative (distinguishes from AMR)."),
            (["feature", "steroidResponse"], 3, "Response to pulse steroids supports diagnosis."),
            (["proteinuria", "subnephrotic"], 1, "Mild proteinuria may be present."),
            (["feature", "fever"], 1, "Low-grade fever possible with acute rejection."),
        ],
        "source_abbr": "KDIGO",
        "source_year": 2021,
        "source_title": "KDIGO 2021 Glomerular Diseases Guideline",
    },
    "cniToxicity": {
        "name": "Calcineurin inhibitor toxicity",
        "base": 0,
        "rules": [
            (["feature", "cniTherapy"], 5, "Tacrolimus or cyclosporine therapy is required context."),
            (["biopsy", "arteriolarHyalinosis"], 4, "Arteriolar hyalinosis on biopsy."),
            (["biopsy", "stripedFibrosis"], 4, "Striped interstitial fibrosis on biopsy."),
            (["egfrTrend", "reduced"], 3, "Slow, progressive eGFR decline."),
            (["proteinuria", "subnephrotic"], 1, "Minimal proteinuria (typically <1 g/day)."),
            (["lab", "highCniTrough"], 4, "High tacrolimus or cyclosporine trough levels."),
            (["feature", "cniDuration"], 2, "Duration of CNI therapy correlates with nephrotoxicity."),
            (["feature", "doseReductionResponse"], 3, "Improvement with CNI dose reduction."),
            (["feature", "tremor"], 1, "Tremor or neurotoxicity may coexist with CNI toxicity."),
        ],
        "source_abbr": "KDIGO",
        "source_year": 2021,
        "source_title": "KDIGO 2021 Glomerular Diseases Guideline",
    },
    "bkVirusNephropathy": {
        "name": "BK virus nephropathy",
        "base": 0,
        "rules": [
            (["lab", "bkViremia"], 6, "BK viremia (viral load >10,000 copies/mL) is a key finding."),
            (["lab", "bkViruria"], 3, "BK viruria with decoy cells on cytology."),
            (["feature", "transplantRecipient"], 5, "BK virus nephropathy occurs almost exclusively in transplant recipients."),
            (["egfrTrend", "reduced"], 3, "eGFR decline is typical."),
            (["biopsy", "viralInclusions"], 5, "Tubulitis with viral intranuclear inclusions on biopsy."),
            (["biopsy", "sv40Positive"], 4, "SV40 staining positive confirms BK virus infection."),
            (["feature", "intenseImmunosuppression"], 3, "High immunosuppression intensity (tacrolimus + MMF) increases risk."),
            (["feature", "uretericStenosis"], 2, "Ureteric stenosis is a possible complication."),
            (["feature", "hemorrhagicCystitis"], 2, "Hemorrhagic cystitis can occur with BK virus reactivation."),
        ],
        "source_abbr": "KDIGO",
        "source_year": 2021,
        "source_title": "KDIGO 2021 Glomerular Diseases Guideline",
    },
    "hivan": {
        "name": "HIV-associated nephropathy (HIVAN)",
        "base": 1,
        "rules": [
            (["ageGroup", "adult"], 2, "HIVAN predominantly affects young to middle-aged adults (20-40 years)."),
            (["feature", "hivPositive"], 6, "HIV seropositivity is essential for the diagnosis of HIVAN."),
            (["proteinuria", "nephrotic"], 3, "Nephrotic-range proteinuria is a common presenting feature."),
            (["egfrTrend", "rapidDecline"], 3, "Rapidly progressive decline in eGFR is characteristic."),
            (["albumin", "low"], 2, "Hypoalbuminemia accompanies nephrotic-range proteinuria."),
            (["sediment", "bland"], 2, "Bland urinary sediment is typical despite heavy proteinuria."),
            (["feature", "cd4Low"], 3, "Advanced immunosuppression with low CD4 count increases risk."),
            (["biopsy", "collapsingFsgs"], 5, "Collapsing FSGS pattern on biopsy is pathognomonic for HIVAN."),
            (["biopsy", "microcysticTubularDilatation"], 3, "Microcystic tubular dilatation is a supportive biopsy finding."),
            (["feature", "ethnicityAfrican"], 2, "Strong ethnic predisposition in individuals of African ancestry."),
            (["feature", "hypertension"], 1, "Hypertension may develop as CKD progresses."),
            (["lab", "normalC3"], 2, "Normal complement levels help distinguish HIVAN from lupus nephritis."),
            (["lab", "normalAntiDsDna"], 2, "Negative anti-dsDNA helps exclude lupus nephritis in HIV+ patients."),
        ],
        "source_abbr": "KDIGO",
        "source_year": 2021,
        "source_title": "KDIGO 2021 Glomerular Diseases Guideline",
    },
    "drugInducedGn": {
        "name": "Drug-induced glomerular disease",
        "base": 1,
        "rules": [
            (["feature", "offendingDrug"], 5, "Temporal association with a known nephrotoxic medication is the key clue."),
            (["feature", "nsaidUse"], 4, "NSAID use can cause minimal change disease, membranous, or AIN."),
            (["feature", "lithiumUse"], 3, "Lithium is associated with FSGS and distal renal tubular acidosis."),
            (["feature", "interferonUse"], 3, "Interferon therapy can induce FSGS or thrombotic microangiopathy."),
            (["feature", "bisphosphonateUse"], 2, "Bisphosphonates (especially pamidronate) can cause collapsing FSGS."),
            (["feature", "immuneCheckpointInhibitor"], 3, "Checkpoint inhibitors can trigger acute tubulointerstitial nephritis."),
            (["feature", "aminoglycosideUse"], 2, "Aminoglycosides cause acute tubular necrosis."),
            (["feature", "protonPumpInhibitorUse"], 2, "PPIs are a common cause of drug-induced AIN."),
            (["proteinuria", "nephrotic"], 3, "Nephrotic-range proteinuria can occur with NSAID-induced MCD."),
            (["proteinuria", "subnephrotic"], 2, "Subnephrotic proteinuria may be seen in drug-induced AIN."),
            (["egfrTrend", "reduced"], 3, "eGFR decline temporally related to drug initiation."),
            (["feature", "allergicReaction"], 2, "Fever, rash, and eosinophilia suggest drug-induced AIN."),
            (["sediment", "whiteCells"], 2, "White cell casts or eosinophiluria can be seen in drug-induced AIN."),
            (["biopsy", "acuteTubulointerstitialNephritis"], 3, "AIN pattern on biopsy supports drug-induced etiology."),
            (["feature", "symptomsResolveOnWithdrawal"], 4, "Improvement after drug withdrawal is highly supportive."),
        ],
        "source_abbr": "KDIGO",
        "source_year": 2021,
        "source_title": "KDIGO 2021 Glomerular Diseases Guideline",
    },
}


class Command(BaseCommand):
    help = "Seed the knowledge base with expanded disease profiles (200+ rules)"

    def handle(self, *args, **options):
        source_cache = {}
        seq = 0
        total_rules = 0
        admin_user = User.objects.filter(is_superuser=True).first()
        for disease_id, profile in DISEASE_RULES.items():
            abbr = profile["source_abbr"]
            year = profile["source_year"]
            key = f"{abbr}-{year}"
            if key not in source_cache:
                source, created = GuidelineSource.objects.get_or_create(
                    abbreviation=abbr,
                    version_year=year,
                    defaults={
                        "title": profile["source_title"],
                        "effective_date": f"{year}-01-01",
                    },
                )
                source_cache[key] = source

            _FIELD_MAP = {"feature": "features", "lab": "labs"}

            for rule_path, weight, explanation in profile["rules"]:
                seq += 1
                entry_id = f"KB-{disease_id.upper()}-{seq:03d}"

                if isinstance(rule_path, list):
                    field = _FIELD_MAP.get(rule_path[0], rule_path[0])
                    conditions = [
                        {"field": field, "operator": "eq", "value": rule_path[1]}
                    ]
                elif rule_path == "egfrTrend_rapid_sustained":
                    conditions = [
                        {"field": "egfrTrend", "operator": "eq", "value": "rapidDecline"}
                    ]
                elif rule_path == "egfrTrend_dialysis_requiring":
                    conditions = [
                        {"field": "egfrTrend", "operator": "eq", "value": "rapidDecline"},
                        {"field": "features", "operator": "contains", "value": "oliguria"},
                    ]
                else:
                    conditions = [
                        {"field": "features", "operator": "contains", "value": rule_path}
                    ]

                today = timezone.now().date()
                next_review = today.replace(year=today.year + 1)

                KnowledgeBaseEntry.objects.get_or_create(
                    entry_id=entry_id,
                    defaults={
                        "disease_id": disease_id,
                        "rule_data": {
                            "conditions": conditions,
                            "weight": weight,
                            "explanation": explanation,
                            "base_score": profile["base"],
                            "disease_name": profile["name"],
                        },
                        "source": source_cache[key],
                        "status": KnowledgeBaseEntry.Status.ACTIVE,
                        "effective_date": f"{year}-01-01",
                        # Governance fields (V8 Layer 4)
                        "explanation": explanation,
                        "confidence_score": 75.0,
                        "guideline_chapter": DISEASE_CHAPTERS.get(disease_id, ""),
                        "evidence_url": DISEASE_URLS.get(disease_id, ""),
                        "author": admin_user,
                        "approved_by": admin_user,
                        "approved_at": timezone.now(),
                        "next_review_date": next_review,
                        "knowledge_version": "6.5",
                        "date_validated": today,
                        "recommendation_id": f"KDIGO-{year}-{disease_id.upper()}-{seq:03d}",
                    },
                )
                total_rules += 1

        count = KnowledgeBaseEntry.objects.count()
        self.stdout.write(self.style.SUCCESS(
            f"Seeded {total_rules} rules across {len(DISEASE_RULES)} diseases "
            f"(total KB entries: {count})"
        ))
