# Generated by Django 6.0.6 on 2026-07-20 17:08

import clinical_evidence.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('encounters', '0003_clinicalencounter_clinician_response_and_more'),
        ('knowledge', '0009_alter_recommendationaudit_evidence_grade'),
        ('patients', '0007_longitudinal_gn_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_type', models.CharField(choices=[('pubmed', 'PubMed (NCBI E-utilities)'), ('europe_pmc', 'Europe PMC'), ('semantic_scholar', 'Semantic Scholar'), ('openalex', 'OpenAlex'), ('crossref', 'Crossref'), ('vera', 'Vera'), ('openai', 'OpenAI GPT'), ('perplexity', 'Perplexity Sonar')], max_length=30, unique=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('priority', models.PositiveSmallIntegerField(default=10, help_text='Lower = queried first')),
                ('api_key_encrypted', models.TextField(blank=True, default='')),
                ('api_base_url', models.URLField(blank=True, default='')),
                ('extra_config', models.JSONField(blank=True, default=dict)),
                ('max_retries', models.PositiveSmallIntegerField(default=3)),
                ('timeout_seconds', models.PositiveSmallIntegerField(default=30)),
                ('rate_limit_per_minute', models.PositiveSmallIntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Provider configuration',
                'ordering': ['priority', 'provider_type'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total_queries', models.PositiveIntegerField(default=0)),
                ('total_results', models.PositiveIntegerField(default=0)),
                ('cache_hit_rate', models.FloatField(default=0.0)),
                ('avg_latency_ms', models.FloatField(default=0.0)),
                ('provider_uptime', models.JSONField(default=dict)),
                ('validations_run', models.PositiveIntegerField(default=0)),
                ('conflicts_detected', models.PositiveIntegerField(default=0)),
                ('alerts_generated', models.PositiveIntegerField(default=0)),
                ('knowledge_gaps_identified', models.PositiveIntegerField(default=0)),
                ('summary', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Evidence analytics',
                'verbose_name_plural': 'Evidence analytics',
                'indexes': [models.Index(fields=['-date'], name='clinical_ev_date_cb2838_idx')],
            },
        ),
        migrations.CreateModel(
            name='EvidenceAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('actor', models.CharField(blank=True, default='', max_length=100)),
                ('resource_type', models.CharField(max_length=50)),
                ('resource_id', models.CharField(max_length=50)),
                ('payload', models.JSONField(default=dict)),
                ('audit_hash', models.CharField(max_length=64, unique=True)),
                ('knowledge_version', models.CharField(blank=True, default='', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Evidence audit log',
                'indexes': [models.Index(fields=['-timestamp'], name='clinical_ev_timesta_8ff2b5_idx'), models.Index(fields=['action', 'resource_type'], name='clinical_ev_action_a5d8f9_idx')],
            },
        ),
        migrations.CreateModel(
            name='EvidenceCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(max_length=128, unique=True)),
                ('cache_type', models.CharField(choices=[('search', 'Search results'), ('summary', 'Evidence summary'), ('ai', 'AI provider response'), ('guideline', 'Guideline match')], max_length=30)),
                ('data', models.JSONField()),
                ('ttl_seconds', models.PositiveIntegerField(default=3600)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Evidence cache',
                'indexes': [models.Index(fields=['cache_type', 'expires_at'], name='clinical_ev_cache_t_fa2c30_idx'), models.Index(fields=['-created_at'], name='clinical_ev_created_ae7715_idx')],
            },
        ),
        migrations.CreateModel(
            name='EvidenceQuery',
            fields=[
                ('query_id', models.CharField(default=clinical_evidence.models._default_query_id, max_length=30, primary_key=True, serialize=False)),
                ('disease_id', models.CharField(blank=True, default='', help_text='GDES disease identifier if context-specific', max_length=50)),
                ('query_text', models.TextField()),
                ('query_type', models.CharField(default='clinical', help_text='clinical, guideline, drug, safety', max_length=30)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('max_results', models.PositiveSmallIntegerField(default=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('provider_count', models.PositiveSmallIntegerField(default=0)),
                ('result_count', models.PositiveSmallIntegerField(default=0)),
                ('is_cached', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='encounters.clinicalencounter')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.patient')),
            ],
            options={
                'verbose_name': 'Evidence query',
                'verbose_name_plural': 'Evidence queries',
            },
        ),
        migrations.CreateModel(
            name='EvidenceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('pubmed', 'PubMed (NCBI E-utilities)'), ('europe_pmc', 'Europe PMC'), ('semantic_scholar', 'Semantic Scholar'), ('openalex', 'OpenAlex'), ('crossref', 'Crossref'), ('vera', 'Vera'), ('openai', 'OpenAI GPT'), ('perplexity', 'Perplexity Sonar')], max_length=30)),
                ('title', models.TextField()),
                ('authors', models.TextField(blank=True, default='')),
                ('journal', models.CharField(blank=True, default='', max_length=300)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('pmid', models.CharField(blank=True, default='', max_length=30)),
                ('pmcid', models.CharField(blank=True, default='', max_length=30)),
                ('doi', models.CharField(blank=True, default='', max_length=200)),
                ('abstract', models.TextField(blank=True, default='')),
                ('url', models.URLField(blank=True, default='', max_length=500)),
                ('evidence_level', models.CharField(blank=True, choices=[('1a', '1a — Meta-analysis of RCTs'), ('1b', '1b — Individual RCT'), ('2a', '2a — Systematic review of cohort studies'), ('2b', '2b — Individual cohort study'), ('3a', '3a — Systematic review of case-control'), ('3b', '3b — Individual case-control study'), ('4', '4 — Case series'), ('5', '5 — Expert opinion'), ('gl', 'Clinical guideline'), ('fda', 'FDA / EMA safety alert')], default='', max_length=10)),
                ('study_design', models.CharField(blank=True, choices=[('meta_analysis', 'Meta-analysis'), ('systematic_review', 'Systematic review'), ('rct', 'Randomised controlled trial'), ('cohort_prospective', 'Prospective cohort'), ('cohort_retrospective', 'Retrospective cohort'), ('case_control', 'Case-control'), ('cross_sectional', 'Cross-sectional'), ('case_series', 'Case series'), ('case_report', 'Case report'), ('narrative_review', 'Narrative review'), ('guideline', 'Clinical practice guideline'), ('fda_alert', 'FDA / EMA safety communication'), ('editorial', 'Editorial / commentary'), ('letter', 'Letter to editor'), ('other', 'Other')], default='', max_length=30)),
                ('citation_count', models.IntegerField(blank=True, null=True)),
                ('journal_impact', models.FloatField(blank=True, null=True)),
                ('sample_size', models.IntegerField(blank=True, null=True)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('mesh_terms', models.JSONField(blank=True, default=list)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('relevance_score', models.FloatField(blank=True, help_text='Provider-assigned relevance 0-1', null=True)),
                ('rank', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='clinical_evidence.evidencequery')),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinical_evidence.providerconfiguration')),
            ],
            options={
                'verbose_name': 'Evidence result',
            },
        ),
        migrations.CreateModel(
            name='EvidencePackage',
            fields=[
                ('package_id', models.CharField(default=clinical_evidence.models._default_package_id, max_length=30, primary_key=True, serialize=False)),
                ('ai_summary', models.TextField(blank=True, default='')),
                ('ai_confidence', models.FloatField(blank=True, null=True)),
                ('ai_response_raw', models.JSONField(blank=True, default=dict)),
                ('ai_provider', models.CharField(blank=True, default='', max_length=30)),
                ('overall_confidence', models.PositiveSmallIntegerField(blank=True, choices=[(95, 'Very High (95-100%)'), (80, 'High (80-94%)'), (60, 'Moderate (60-79%)'), (40, 'Low (40-59%)'), (20, 'Very Low (20-39%)'), (5, 'Insufficient (<20%)')], null=True)),
                ('guideline_match', models.CharField(blank=True, default='', help_text='Matched guideline identifier', max_length=30)),
                ('governance_hash', models.CharField(blank=True, default='', max_length=64)),
                ('knowledge_version', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='clinical_evidence.evidencequery')),
                ('contradictory_results', models.ManyToManyField(related_name='contradictory_packages', to='clinical_evidence.evidenceresult')),
                ('neutral_results', models.ManyToManyField(related_name='neutral_packages', to='clinical_evidence.evidenceresult')),
                ('supporting_results', models.ManyToManyField(related_name='supporting_packages', to='clinical_evidence.evidenceresult')),
            ],
            options={
                'verbose_name': 'Evidence package',
            },
        ),
        migrations.CreateModel(
            name='EvidenceCitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apa', models.TextField(blank=True, default='')),
                ('vancouver', models.TextField(blank=True, default='')),
                ('bibtex', models.TextField(blank=True, default='')),
                ('ris', models.TextField(blank=True, default='')),
                ('mla', models.TextField(blank=True, default='')),
                ('chicago', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='citation', to='clinical_evidence.evidenceresult')),
            ],
            options={
                'verbose_name': 'Evidence citation',
            },
        ),
        migrations.CreateModel(
            name='EvidenceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_text', models.TextField()),
                ('key_findings', models.JSONField(blank=True, default=list)),
                ('limitations', models.JSONField(blank=True, default=list)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('ai_provider', models.CharField(blank=True, default='', max_length=30)),
                ('citation_count', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='clinical_evidence.evidencequery')),
            ],
            options={
                'verbose_name': 'Evidence summary',
            },
        ),
        migrations.CreateModel(
            name='GuidelineRecommendation',
            fields=[
                ('guideline_source', models.CharField(choices=[('KDIGO', 'KDIGO — Kidney Disease: Improving Global Outcomes'), ('ERA', 'ERA — European Renal Association'), ('ASN', 'ASN — American Society of Nephrology'), ('ISN', 'ISN — International Society of Nephrology'), ('NKF', 'NKF/KDOQI — National Kidney Foundation'), ('other', 'Other guideline body')], max_length=30)),
                ('recommendation_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('disease_id', models.CharField(blank=True, default='', max_length=50)),
                ('title', models.TextField()),
                ('recommendation_text', models.TextField()),
                ('evidence_grade', models.CharField(blank=True, default='', max_length=20)),
                ('recommendation_strength', models.CharField(blank=True, default='', max_length=50)),
                ('guideline_version', models.CharField(blank=True, default='', max_length=30)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('url', models.URLField(blank=True, default='', max_length=500)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Guideline recommendation',
                'indexes': [models.Index(fields=['guideline_source', 'disease_id'], name='clinical_ev_guideli_a5de5e_idx'), models.Index(fields=['is_active'], name='clinical_ev_is_acti_fc3f4a_idx')],
            },
        ),
        migrations.CreateModel(
            name='EvidenceConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('critical', 'Critical — Safety alert or drug withdrawal'), ('high', 'High — New RCT contradicts guideline'), ('medium', 'Medium — New systematic review differs'), ('low', 'Low — Minor discrepancy'), ('info', 'Informational — New evidence available')], default='medium', max_length=20)),
                ('conflict_type', models.CharField(blank=True, default='', max_length=50)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('affected_disease', models.CharField(blank=True, default='', max_length=50)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, default='')),
                ('governance_hash', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='clinical_evidence.evidencepackage')),
                ('contradictory_results', models.ManyToManyField(related_name='conflict_contradictory', to='clinical_evidence.evidenceresult')),
                ('supporting_results', models.ManyToManyField(related_name='conflict_supporting', to='clinical_evidence.evidenceresult')),
                ('affected_guideline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinical_evidence.guidelinerecommendation')),
            ],
            options={
                'verbose_name': 'Evidence conflict',
            },
        ),
        migrations.CreateModel(
            name='EvidenceAlert',
            fields=[
                ('alert_id', models.CharField(default=clinical_evidence.models._default_alert_id, max_length=30, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('new_rct', 'New RCT published'), ('new_guideline', 'New guideline released'), ('safety_alert', 'FDA/EMA safety alert'), ('drug_withdrawal', 'Drug withdrawal'), ('contradiction', 'Evidence contradiction detected'), ('guideline_update', 'Guideline update available'), ('knowledge_gap', 'Knowledge gap identified')], max_length=30)),
                ('severity', models.CharField(choices=[('critical', 'Critical — Safety alert or drug withdrawal'), ('high', 'High — New RCT contradicts guideline'), ('medium', 'Medium — New systematic review differs'), ('low', 'Low — Minor discrepancy'), ('info', 'Informational — New evidence available')], default='info', max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('disease_id', models.CharField(blank=True, default='', max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_results', models.ManyToManyField(blank=True, to='clinical_evidence.evidenceresult')),
                ('related_guideline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinical_evidence.guidelinerecommendation')),
            ],
            options={
                'verbose_name': 'Evidence alert',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeGap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_id', models.CharField(max_length=50)),
                ('gap_type', models.CharField(choices=[('missing_rule', 'Missing clinical rule'), ('outdated_evidence', 'Outdated evidence reference'), ('new_treatment', 'New treatment not in KB'), ('safety_update', 'Safety information update'), ('guideline_change', 'Guideline recommendation changed'), ('contradiction', 'KB contradicts current evidence')], max_length=30)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('recommended_action', models.TextField(blank=True, default='')),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('is_addressed', models.BooleanField(default=False)),
                ('addressed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('addressed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('evidence_results', models.ManyToManyField(blank=True, to='clinical_evidence.evidenceresult')),
            ],
            options={
                'verbose_name': 'Knowledge gap',
            },
        ),
        migrations.CreateModel(
            name='EvidenceUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_type', models.CharField(choices=[('daily_refresh', 'Daily literature refresh'), ('guideline_scan', 'Weekly guideline scan'), ('provider_sync', 'Provider data sync'), ('manual', 'Manual import')], max_length=30)),
                ('summary', models.TextField(blank=True, default='')),
                ('new_results', models.PositiveIntegerField(default=0)),
                ('updated_results', models.PositiveIntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinical_evidence.providerconfiguration')),
            ],
            options={
                'verbose_name': 'Evidence update',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProviderHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('degraded', 'Degraded'), ('disabled', 'Disabled'), ('error', 'Error')], default='active', max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('latency_ms', models.FloatField(blank=True, null=True)),
                ('error_rate', models.FloatField(default=0.0)),
                ('quota_remaining', models.IntegerField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_message', models.TextField(blank=True, default='')),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('checked_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_logs', to='clinical_evidence.providerconfiguration')),
            ],
            options={
                'verbose_name': 'Provider health',
                'verbose_name_plural': 'Provider health metrics',
            },
        ),
        migrations.CreateModel(
            name='ProviderRateLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_start', models.DateTimeField()),
                ('request_count', models.PositiveIntegerField(default=0)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_limits', to='clinical_evidence.providerconfiguration')),
            ],
            options={
                'verbose_name': 'Provider rate limit',
            },
        ),
        migrations.CreateModel(
            name='RecommendationValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('verified', 'Verified — Recommendation matches evidence'), ('minor', 'Minor difference — Recommendation aligns broadly'), ('major', 'Major difference — Recommendation diverges from evidence'), ('conflicting', 'Conflicting evidence — Contradictory studies found'), ('unverifiable', 'Unable to verify — Insufficient evidence'), ('pending', 'Validation pending')], default='pending', max_length=20)),
                ('confidence_score', models.PositiveSmallIntegerField(blank=True, choices=[(95, 'Very High (95-100%)'), (80, 'High (80-94%)'), (60, 'Moderate (60-79%)'), (40, 'Low (40-59%)'), (20, 'Very Low (20-39%)'), (5, 'Insufficient (<20%)')], null=True)),
                ('summary', models.TextField(blank=True, default='')),
                ('details', models.JSONField(blank=True, default=dict)),
                ('governance_hash', models.CharField(blank=True, default='', max_length=64)),
                ('validated_by', models.CharField(default='system', help_text='system, ai, or clinician username', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('encountered_at', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='encounters.clinicalencounter')),
                ('gdes_recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_validations', to='knowledge.recommendationaudit')),
                ('matched_guideline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinical_evidence.guidelinerecommendation')),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validations', to='clinical_evidence.evidencepackage')),
            ],
            options={
                'verbose_name': 'Recommendation validation',
            },
        ),
        migrations.AddIndex(
            model_name='evidencequery',
            index=models.Index(fields=['-created_at'], name='clinical_ev_created_65e593_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencequery',
            index=models.Index(fields=['disease_id'], name='clinical_ev_disease_69d10f_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencequery',
            index=models.Index(fields=['query_type'], name='clinical_ev_query_t_e203bb_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencepackage',
            index=models.Index(fields=['-created_at'], name='clinical_ev_created_4bad86_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencepackage',
            index=models.Index(fields=['overall_confidence'], name='clinical_ev_overall_b52a62_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencesummary',
            index=models.Index(fields=['-created_at'], name='clinical_ev_created_65abb5_idx'),
        ),
        migrations.AddIndex(
            model_name='evidenceconflict',
            index=models.Index(fields=['severity'], name='clinical_ev_severit_a89b39_idx'),
        ),
        migrations.AddIndex(
            model_name='evidenceconflict',
            index=models.Index(fields=['is_resolved', '-created_at'], name='clinical_ev_is_reso_457107_idx'),
        ),
        migrations.AddIndex(
            model_name='evidenceconflict',
            index=models.Index(fields=['conflict_type'], name='clinical_ev_conflic_663a27_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencealert',
            index=models.Index(fields=['-created_at'], name='clinical_ev_created_07acff_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencealert',
            index=models.Index(fields=['alert_type', 'is_dismissed'], name='clinical_ev_alert_t_296756_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencealert',
            index=models.Index(fields=['severity'], name='clinical_ev_severit_cb52fc_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgegap',
            index=models.Index(fields=['disease_id', 'gap_type'], name='clinical_ev_disease_d28eaf_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgegap',
            index=models.Index(fields=['priority'], name='clinical_ev_priorit_b6d4cf_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgegap',
            index=models.Index(fields=['is_addressed'], name='clinical_ev_is_addr_dde627_idx'),
        ),
        migrations.AddIndex(
            model_name='evidenceresult',
            index=models.Index(fields=['query', 'rank'], name='clinical_ev_query_i_babe19_idx'),
        ),
        migrations.AddIndex(
            model_name='evidenceresult',
            index=models.Index(fields=['pmid'], name='clinical_ev_pmid_990b44_idx'),
        ),
        migrations.AddIndex(
            model_name='evidenceresult',
            index=models.Index(fields=['doi'], name='clinical_ev_doi_5d4db8_idx'),
        ),
        migrations.AddIndex(
            model_name='evidenceresult',
            index=models.Index(fields=['source_type'], name='clinical_ev_source__58b739_idx'),
        ),
        migrations.AddIndex(
            model_name='providerhealth',
            index=models.Index(fields=['provider', '-checked_at'], name='clinical_ev_provide_080856_idx'),
        ),
        migrations.AddIndex(
            model_name='providerhealth',
            index=models.Index(fields=['status'], name='clinical_ev_status_1951a1_idx'),
        ),
        migrations.AddIndex(
            model_name='providerratelimit',
            index=models.Index(fields=['provider', 'window_start'], name='clinical_ev_provide_cfeed0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='providerratelimit',
            unique_together={('provider', 'window_start')},
        ),
        migrations.AddIndex(
            model_name='recommendationvalidation',
            index=models.Index(fields=['outcome'], name='clinical_ev_outcome_78565e_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationvalidation',
            index=models.Index(fields=['-created_at'], name='clinical_ev_created_f3979f_idx'),
        ),
    ]
