# Generated by Django 6.0.6 on 2026-07-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_evidence', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='evidenceresult',
            name='clinical_ev_query_i_babe19_idx',
        ),
        migrations.AlterField(
            model_name='evidenceresult',
            name='source_type',
            field=models.CharField(choices=[('pubmed', 'PubMed (NCBI E-utilities)'), ('europe_pmc', 'Europe PMC'), ('semantic_scholar', 'Semantic Scholar'), ('openalex', 'OpenAlex'), ('crossref', 'Crossref'), ('vera', 'Vera'), ('vera_web', 'Vera Health (web session)'), ('openai', 'OpenAI GPT'), ('perplexity', 'Perplexity Sonar')], max_length=30),
        ),
        migrations.AlterField(
            model_name='providerconfiguration',
            name='provider_type',
            field=models.CharField(choices=[('pubmed', 'PubMed (NCBI E-utilities)'), ('europe_pmc', 'Europe PMC'), ('semantic_scholar', 'Semantic Scholar'), ('openalex', 'OpenAlex'), ('crossref', 'Crossref'), ('vera', 'Vera'), ('vera_web', 'Vera Health (web session)'), ('openai', 'OpenAI GPT'), ('perplexity', 'Perplexity Sonar')], max_length=30, unique=True),
        ),
        migrations.AddIndex(
            model_name='evidenceresult',
            index=models.Index(fields=['query', 'source_type'], name='clinical_ev_query_i_4c0af4_idx'),
        ),
        migrations.RemoveField(
            model_name='evidenceresult',
            name='rank',
        ),
    ]
