# Generated by Django 6.0.6 on 2026-06-19 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('encounters', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('loinc', models.CharField(blank=True, max_length=20)),
                ('default_unit', models.CharField(blank=True, max_length=20)),
                ('value_type', models.CharField(choices=[('numeric', 'Numeric'), ('qualitative', 'Qualitative (pos/neg/text)')], default='numeric', max_length=12)),
                ('ref_low', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('ref_high', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('is_derived', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LabOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_date', models.DateField()),
                ('status', models.CharField(choices=[('ordered', 'Ordered'), ('collected', 'Sample collected'), ('resulted', 'Resulted'), ('cancelled', 'Cancelled')], default='ordered', max_length=12)),
                ('notes', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_orders', to='encounters.clinicalencounter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to='patients.patient')),
            ],
            options={
                'ordering': ['-ordered_date'],
            },
        ),
        migrations.CreateModel(
            name='LabOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='labs.laborder')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='labs.labtest')),
            ],
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_numeric', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('value_text', models.CharField(blank=True, max_length=120)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('sample_date', models.DateField(blank=True, null=True)),
                ('result_date', models.DateField()),
                ('flag', models.CharField(blank=True, choices=[('', 'Normal'), ('L', 'Low'), ('H', 'High')], max_length=1)),
                ('source', models.CharField(choices=[('lab', 'Laboratory'), ('manual', 'Manual entry'), ('derived', 'Derived (computed)')], default='lab', max_length=8)),
                ('formula_version', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('derived_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivations', to='labs.labresult')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='labs.laborderitem')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to='patients.patient')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='labs.labtest')),
            ],
            options={
                'ordering': ['patient', 'test__code', 'result_date'],
            },
        ),
        migrations.CreateModel(
            name='LabPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('tests', models.ManyToManyField(related_name='panels', to='labs.labtest')),
            ],
        ),
        migrations.AddIndex(
            model_name='laborder',
            index=models.Index(fields=['patient', 'ordered_date'], name='labs_labord_patient_80eeb4_idx'),
        ),
        migrations.AddIndex(
            model_name='labresult',
            index=models.Index(fields=['patient', 'test', 'result_date'], name='labs_labres_patient_ab69d8_idx'),
        ),
        migrations.AddConstraint(
            model_name='laborderitem',
            constraint=models.UniqueConstraint(fields=('order', 'test'), name='uniq_order_test'),
        ),
    ]
