# Generated by Django 5.2.16 on 2026-09-27 14:09

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0001_initial'),
        ('patients', '0009_patient_condition_provenance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labresult',
            options={'base_manager_name': 'all_objects', 'ordering': ['patient', 'test__code', 'result_date']},
        ),
        migrations.AlterModelManagers(
            name='labresult',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='labresult',
            name='correction_reason',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='labresult',
            name='entered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labresult',
            name='entry_path',
            field=models.CharField(blank=True, choices=[('guided', 'Results page'), ('baseline', 'Baseline form'), ('api', 'API'), ('admin', 'Admin'), ('import', 'Import'), ('fhir', 'FHIR'), ('derived', 'Derived'), ('reconcile', 'Reconciliation'), ('other', 'Other')], max_length=10),
        ),
        migrations.AddField(
            model_name='labresult',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AddField(
            model_name='labresult',
            name='is_current',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='labresult',
            name='source_report_id',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='labresult',
            name='specimen_id',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='labresult',
            name='supersedes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='labs.labresult'),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='source',
            field=models.CharField(choices=[('lab', 'Laboratory'), ('manual', 'Manual entry'), ('derived', 'Derived (computed)'), ('legacy', 'Legacy value (reconciled from an older form)')], default='lab', max_length=8),
        ),
        migrations.AddConstraint(
            model_name='labresult',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('patient', 'idempotency_key'), name='uniq_labresult_idempotency_key'),
        ),
    ]
